/*
 * @(#)Aaingreso.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Aaingreso generated by hbm2java
 */
public class Aaingreso implements Serializable {

    private static final long serialVersionUID = 1L;
    private BigDecimal aaiPtjePond;
    private ViaIngreso aaiViaIng;
    private AaingresoId id;

    /**
     *
     */
    public Aaingreso() {
    }

    /**
     * Method description
     *
     * @return
     */
    public AaingresoId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(AaingresoId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public BigDecimal getAaiPtjePond() {
        return this.aaiPtjePond;
    }

    /**
     * Method description
     *
     * @param aaiPtjePond
     */
    public void setAaiPtjePond(BigDecimal aaiPtjePond) {
        this.aaiPtjePond = aaiPtjePond;
    }

    /**
     * Method description
     *
     * @return
     */
    public ViaIngreso getAaiViaIng() {
        return this.aaiViaIng;
    }

    /**
     * Method description
     *
     * @param aaiViaIng
     */
    public void setAaiViaIng(ViaIngreso aaiViaIng) {
        this.aaiViaIng = aaiViaIng;
    }
}
