/*
 * @(#)AaingresoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */


package domain.model;


//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;


/**
 * AaingresoId generated by hbm2java
 */
public class AaingresoId implements Serializable {
    private static final long serialVersionUID = 1L;
    private Integer           aaiAnoIng;
    private Integer           aaiCcarr;
    private Integer           aaiRut;
    private Integer           aaiSemIng;

    /**
     *
     */
    public AaingresoId() {}

    /**
     * Method description
     *
     * @return
     */
    public Integer getAaiRut() {
        return this.aaiRut;
    }

    /**
     * Method description
     *
     * @param aaiRut
     */
    public void setAaiRut(Integer aaiRut) {
        this.aaiRut = aaiRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAaiCcarr() {
        return this.aaiCcarr;
    }

    /**
     * Method description
     *
     * @param aaiCcarr
     */
    public void setAaiCcarr(Integer aaiCcarr) {
        this.aaiCcarr = aaiCcarr;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAaiAnoIng() {
        return this.aaiAnoIng;
    }

    /**
     * Method description
     *
     * @param aaiAnoIng
     */
    public void setAaiAnoIng(Integer aaiAnoIng) {
        this.aaiAnoIng = aaiAnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAaiSemIng() {
        return this.aaiSemIng;
    }

    /**
     * Method description
     *
     * @param aaiSemIng
     */
    public void setAaiSemIng(Integer aaiSemIng) {
        this.aaiSemIng = aaiSemIng;
    }
}
