/*
 * @(#)ActaCalificacion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.*;

/**
 * Acta generated by hbm2java
 */
public class ActaCalificacion implements Serializable {

    private static final long serialVersionUID = 1L;
    private Set<ActaCalificacionNomina> actaCalificacionNominas = new HashSet<>(0);
    private String acalTipo;
    private Curso curso;
    private EstadoActa estadoActa;
    private ActaCalificacionId id;
    private String acalTipoAlu;

    /**
     *
     */
    public ActaCalificacion() {
    }

    /**
     * Method description
     *
     * @return
     */
    public ActaCalificacionId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(ActaCalificacionId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return this.curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     * Method description
     *
     * @return
     */
    public EstadoActa getEstadoActa() {
        return estadoActa;
    }

    /**
     * Method description
     *
     * @param estadoActa
     */
    public void setEstadoActa(EstadoActa estadoActa) {
        this.estadoActa = estadoActa;
    }

    /**
     * Method description
     *
     * @return
     */
    public Set<ActaCalificacionNomina> getActaCalificacionNominas() {
        return this.actaCalificacionNominas;
    }

    /**
     * Method description
     *
     * @param actaCalificacionNominas
     */
    public void setActaCalificacionNominas(Set<ActaCalificacionNomina> actaCalificacionNominas) {
        this.actaCalificacionNominas = actaCalificacionNominas;
    }

    /**
     *
     * @return
     */
    public String getAcalTipo() {
        return acalTipo;
    }

    /**
     *
     * @param acalTipo
     */
    public void setAcalTipo(String acalTipo) {
        this.acalTipo = acalTipo;
    }

    /**
     *
     * @return
     */
    public String getAcalTipoAlu() {
        return acalTipoAlu;
    }

    /**
     *
     * @param acalTipoAlu
     */
    public void setAcalTipoAlu(String acalTipoAlu) {
        this.acalTipoAlu = acalTipoAlu;
    }
}
