/*
 * @(#)ActaCalificacionNominaId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ActaCalifiacionId generated by hbm2java
 */
public class ActaCalificacionNominaId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer acanAgno;
    private Integer acanAgnoIng;
    private Integer acanCodCar;
    private Integer acanFolio;
    private Integer acanRut;
    private Integer acanSem;
    private Integer acanSemIng;

    /**
     *
     */
    public ActaCalificacionNominaId() {
    }

    /**
     *
     * @return
     */
    public Integer getAcanAgno() {
        return acanAgno;
    }

    /**
     *
     * @param acanAgno
     */
    public void setAcanAgno(Integer acanAgno) {
        this.acanAgno = acanAgno;
    }

    /**
     *
     * @return
     */
    public Integer getAcanAgnoIng() {
        return acanAgnoIng;
    }

    /**
     *
     * @param acanAgnoIng
     */
    public void setAcanAgnoIng(Integer acanAgnoIng) {
        this.acanAgnoIng = acanAgnoIng;
    }

    /**
     *
     * @return
     */
    public Integer getAcanCodCar() {
        return acanCodCar;
    }

    /**
     *
     * @param acanCodCar
     */
    public void setAcanCodCar(Integer acanCodCar) {
        this.acanCodCar = acanCodCar;
    }

    /**
     *
     * @return
     */
    public Integer getAcanFolio() {
        return acanFolio;
    }

    /**
     *
     * @param acanFolio
     */
    public void setAcanFolio(Integer acanFolio) {
        this.acanFolio = acanFolio;
    }

    /**
     *
     * @return
     */
    public Integer getAcanRut() {
        return acanRut;
    }

    /**
     *
     * @param acanRut
     */
    public void setAcanRut(Integer acanRut) {
        this.acanRut = acanRut;
    }

    /**
     *
     * @return
     */
    public Integer getAcanSem() {
        return acanSem;
    }

    /**
     *
     * @param acanSem
     */
    public void setAcanSem(Integer acanSem) {
        this.acanSem = acanSem;
    }

    /**
     *
     * @return
     */
    public Integer getAcanSemIng() {
        return acanSemIng;
    }

    /**
     *
     * @param acanSemIng
     */
    public void setAcanSemIng(Integer acanSemIng) {
        this.acanSemIng = acanSemIng;
    }
}
