/*
 * @(#)ActaCalificacionId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ActaId generated by hbm2java
 */
public class ActaCalificacionId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer acalAgno;
    private Integer acalFolio;
    private Integer acalSem;

    /**
     *
     */
    public ActaCalificacionId() {
    }

    /**
     *
     * @return
     */
    public Integer getAcalAgno() {
        return acalAgno;
    }

    /**
     *
     * @param acalAgno
     */
    public void setAcalAgno(Integer acalAgno) {
        this.acalAgno = acalAgno;
    }

    /**
     *
     * @return
     */
    public Integer getAcalFolio() {
        return acalFolio;
    }

    /**
     *
     * @param acalFolio
     */
    public void setAcalFolio(Integer acalFolio) {
        this.acalFolio = acalFolio;
    }

    /**
     *
     * @return
     */
    public Integer getAcalSem() {
        return acalSem;
    }

    /**
     *
     * @param acalSem
     */
    public void setAcalSem(Integer acalSem) {
        this.acalSem = acalSem;
    }    
}
