/*
 * @(#)ActaConvalidacion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;

/**
 * Acta generated by hbm2java
 */
public class ActaConvalidacion implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer acoAgno;
    private String acoEstado;
    private Integer acoFolio;
    private Integer acoSem;
    private AluCar aluCar;
    private ConvalidacionSolicitud solicitud;

    /**
     *
     */
    public ActaConvalidacion() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getAcoAgno() {
        return acoAgno;
    }

    /**
     * Method description
     *
     *
     * @param acoAgno
     */
    public void setAcoAgno(Integer acoAgno) {
        this.acoAgno = acoAgno;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getAcoSem() {
        return acoSem;
    }

    /**
     * Method description
     *
     *
     * @param acoSem
     */
    public void setAcoSem(Integer acoSem) {
        this.acoSem = acoSem;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getAcoEstado() {
        return acoEstado;
    }

    /**
     * Method description
     *
     *
     * @param acoEstado
     */
    public void setAcoEstado(String acoEstado) {
        this.acoEstado = acoEstado;
    }

    /**
     *
     * @return
     */
    public AluCar getAluCar() {
        return aluCar;
    }

    /**
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }



    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getAcoFolio() {
        return acoFolio;
    }

    /**
     * Method description
     *
     *
     * @param acoFolio
     */
    public void setAcoFolio(Integer acoFolio) {
        this.acoFolio = acoFolio;
    }

    public ConvalidacionSolicitud getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(ConvalidacionSolicitud solicitud) {
        this.solicitud = solicitud;
    }
}
