/*
 * @(#)ActaConvalidacionAsignatura.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Acta generated by hbm2java
 */
public class ActaConvalidacionAsignatura implements Serializable {

    private static final long serialVersionUID = 1L;
    private String acoaCursada;
    private BigDecimal acoaNota;
    private ActaConvalidacion actaConvalidacion;
    private ActaConvalidacionAsignaturaId id;

    /**
     *
     */
    public ActaConvalidacionAsignatura() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public ActaConvalidacionAsignaturaId getId() {
        return id;
    }

    /**
     * Method description
     *
     *
     * @param id
     */
    public void setId(ActaConvalidacionAsignaturaId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getAcoaCursada() {
        return acoaCursada;
    }

    /**
     * Method description
     *
     *
     * @param acoaCursada
     */
    public void setAcoaCursada(String acoaCursada) {
        this.acoaCursada = acoaCursada;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public BigDecimal getAcoaNota() {
        return acoaNota;
    }

    /**
     * Method description
     *
     *
     * @param acoaNota
     */
    public void setAcoaNota(BigDecimal acoaNota) {
        this.acoaNota = acoaNota;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public ActaConvalidacion getActaConvalidacion() {
        return actaConvalidacion;
    }

    /**
     * Method description
     *
     *
     * @param actaConvalidacion
     */
    public void setActaConvalidacion(ActaConvalidacion actaConvalidacion) {
        this.actaConvalidacion = actaConvalidacion;
    }
}
