/*
 * @(#)ActaConvalidacionAsignaturaId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ActaId generated by hbm2java
 */
public class ActaConvalidacionAsignaturaId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer acoaAsign;
    private Integer acoaFolio;

    /**
     *
     */
    public ActaConvalidacionAsignaturaId() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getAcoaFolio() {
        return acoaFolio;
    }

    /**
     * Method description
     *
     *
     * @param acoaFolio
     */
    public void setAcoaFolio(Integer acoaFolio) {
        this.acoaFolio = acoaFolio;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getAcoaAsign() {
        return acoaAsign;
    }

    /**
     * Method description
     *
     *
     * @param acoaAsign
     */
    public void setAcoaAsign(Integer acoaAsign) {
        this.acoaAsign = acoaAsign;
    }
}
