/*
 * @(#)ActaCalificacionNomina.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * ActaCalificacionNomina generated by hbm2java
 */
public class ActaCalificacionNomina implements Serializable {

    private static final long serialVersionUID = 1L;
    private String acanConcep;
    private BigDecimal acanFinal;
    private BigDecimal acanLab;
    private BigDecimal acanTeo;
    private ActaCalificacion actaCalificacion;
    private AluCar aluCar;
    private ActaCalificacionNominaId id;

    /**
     *
     */
    public ActaCalificacionNomina() {
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAcanConcep() {
        return acanConcep;
    }

    /**
     * Method description
     *
     * @param acanConcep
     */
    public void setAcanConcep(String acanConcep) {
        this.acanConcep = acanConcep;
    }

    /**
     * Method description
     *
     * @return
     */
    public BigDecimal getAcanFinal() {
        return acanFinal;
    }

    /**
     * Method description
     *
     * @param acanFinal
     */
    public void setAcanFinal(BigDecimal acanFinal) {
        this.acanFinal = acanFinal;
    }

    /**
     * Method description
     *
     * @return
     */
    public BigDecimal getAcanLab() {
        return acanLab;
    }

    /**
     * Method description
     *
     * @param acanLab
     */
    public void setAcanLab(BigDecimal acanLab) {
        this.acanLab = acanLab;
    }

    /**
     * Method description
     *
     * @return
     */
    public BigDecimal getAcanTeo() {
        return acanTeo;
    }

    /**
     * Method description
     *
     * @param acanTeo
     */
    public void setAcanTeo(BigDecimal acanTeo) {
        this.acanTeo = acanTeo;
    }

    /**
     *
     * @return
     */
    public ActaCalificacion getActaCalificacion() {
        return actaCalificacion;
    }

    /**
     *
     * @param actaCalificacion
     */
    public void setActaCalificacion(ActaCalificacion actaCalificacion) {
        this.actaCalificacion = actaCalificacion;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public ActaCalificacionNominaId getId() {
        return id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(ActaCalificacionNominaId id) {
        this.id = id;
    }

    /**
     * BUSINESS LOGIC
     *
     * @return
     */

    /**
     * Method description
     *
     * @return
     */
    public String getSituacion() {
        String situacion = "";

        if (this.acanFinal != null) {
            situacion = this.acanFinal.compareTo(new BigDecimal("4")) >= 0
                    ? "A"
                    : "R";
        }

        if (this.acanConcep != null) {
            String concepto = this.acanConcep;

            situacion = "AD".equals(concepto) || "A".equals(concepto) || "B".equals(concepto) || "C".equals(concepto)
                    ? "A"
                    : "R";
        }

        return situacion;
    }
}
