/*
 * @(#)ActaCalificacionId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ActaId generated by hbm2java
 */
public class ActaPracticaNominaId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer apranFolio;
    private Integer apranRut;
    private Integer apranCodCar;
    private Integer apranAgnoIng;
    private Integer apranSemIng;

    /**
     *
     */
    public ActaPracticaNominaId() {
    }

    /**
     *
     * @return
     */
    public Integer getApranFolio() {
        return apranFolio;
    }

    /**
     *
     * @param apranFolio
     */
    public void setApranFolio(Integer apranFolio) {
        this.apranFolio = apranFolio;
    }

    /**
     *
     * @return
     */
    public Integer getApranRut() {
        return apranRut;
    }

    /**
     *
     * @param apranRut
     */
    public void setApranRut(Integer apranRut) {
        this.apranRut = apranRut;
    }

    /**
     *
     * @return
     */
    public Integer getApranCodCar() {
        return apranCodCar;
    }

    /**
     *
     * @param apranCodCar
     */
    public void setApranCodCar(Integer apranCodCar) {
        this.apranCodCar = apranCodCar;
    }

    /**
     *
     * @return
     */
    public Integer getApranAgnoIng() {
        return apranAgnoIng;
    }

    /**
     *
     * @param apranAgnoIng
     */
    public void setApranAgnoIng(Integer apranAgnoIng) {
        this.apranAgnoIng = apranAgnoIng;
    }

    /**
     *
     * @return
     */
    public Integer getApranSemIng() {
        return apranSemIng;
    }

    /**
     *
     * @param apranSemIng
     */
    public void setApranSemIng(Integer apranSemIng) {
        this.apranSemIng = apranSemIng;
    }
}
