/*
 * @(#)ActaCalificacionNomina.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.math.BigDecimal;

/**
 * ActaCalificacionNomina generated by hbm2java
 */
public class ActaPracticaNomina implements Serializable {

    private static final long serialVersionUID = 1L;

    private BigDecimal apranNotaEmp;
    private BigDecimal apranNotaCoord;
    private ActaPractica actaPractica;
    private AluCar aluCar;
    private ActaPracticaNominaId id;

    /**
     *
     */
    public ActaPracticaNomina() {
    }

    public BigDecimal getApranNotaEmp() {
        return apranNotaEmp;
    }

    public void setApranNotaEmp(BigDecimal apranNotaEmp) {
        this.apranNotaEmp = apranNotaEmp;
    }

    public BigDecimal getApranNotaCoord() {
        return apranNotaCoord;
    }

    public void setApranNotaCoord(BigDecimal apranNotaCoord) {
        this.apranNotaCoord = apranNotaCoord;
    }



    /**
     *
     * @return
     */
    public ActaPractica getActaPractica() {
        return actaPractica;
    }

    /**
     *
     * @param actaPractica
     */
    public void setActaPractica(ActaPractica actaPractica) {
        this.actaPractica = actaPractica;
    }

    /**
     *
     * @return
     */
    public AluCar getAluCar() {
        return aluCar;
    }

    /**
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     *
     * @return
     */
    public ActaPracticaNominaId getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(ActaPracticaNominaId id) {
        this.id = id;
    }
}
