/*
 * @(#)ActaConvalidacion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;

/**
 * Acta generated by hbm2java
 */
public class ActaPractica implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer apraAgno;
    private String apraEstado;
    private Integer apraFolio;
    private Integer apraSem;
    private Asignatura asignatura;
    private Integer apraPorcEmp;
    private Integer apraPorcCoord;
    private String apraTipo;

    /**
     *
     */
    public ActaPractica() {
    }

    /**
     *
     * @return
     */
    public Integer getApraAgno() {
        return apraAgno;
    }

    /**
     *
     * @param apraAgno
     */
    public void setApraAgno(Integer apraAgno) {
        this.apraAgno = apraAgno;
    }

    /**
     *
     * @return
     */
    public String getApraEstado() {
        return apraEstado;
    }

    /**
     *
     * @param apraEstado
     */
    public void setApraEstado(String apraEstado) {
        this.apraEstado = apraEstado;
    }

    /**
     *
     * @return
     */
    public Integer getApraFolio() {
        return apraFolio;
    }

    /**
     *
     * @param apraFolio
     */
    public void setApraFolio(Integer apraFolio) {
        this.apraFolio = apraFolio;
    }

    /**
     *
     * @return
     */
    public Integer getApraSem() {
        return apraSem;
    }

    /**
     *
     * @param apraSem
     */
    public void setApraSem(Integer apraSem) {
        this.apraSem = apraSem;
    }

    /**
     *
     * @return
     */
    public Asignatura getAsignatura() {
        return asignatura;
    }

    /**
     *
     * @param asignatura
     */
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    public Integer getApraPorcEmp() {
        return apraPorcEmp;
    }

    public void setApraPorcEmp(Integer apraPorcEmp) {
        this.apraPorcEmp = apraPorcEmp;
    }

    public Integer getApraPorcCoord() {
        return apraPorcCoord;
    }

    public void setApraPorcCoord(Integer apraPorcCoord) {
        this.apraPorcCoord = apraPorcCoord;
    }

    public String getApraTipo() {
        return apraTipo;
    }

    public void setApraTipo(String apraTipo) {
        this.apraTipo = apraTipo;
    }
}
