package domain.model;
// Generated 14-08-2014 03:40:22 PM by Hibernate Tools 3.2.1.GA

/**
 * ActividadEconomica generated by hbm2java
 */
public class ActividadEconomica implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer aceCod;
    private String aceDes;

    /**
     *
     */
    public ActividadEconomica() {
    }

    /**
     *
     * @param aceCod
     */
    public ActividadEconomica(Integer aceCod) {
        this.aceCod = aceCod;
    }

    /**
     *
     * @return
     */
    public Integer getAceCod() {
        return this.aceCod;
    }

    /**
     *
     * @param aceCod
     */
    public void setAceCod(Integer aceCod) {
        this.aceCod = aceCod;
    }

    /**
     *
     * @return
     */
    public String getAceDes() {
        return this.aceDes;
    }

    /**
     *
     * @param aceDes
     */
    public void setAceDes(String aceDes) {
        this.aceDes = aceDes;
    }
}
