/*
 * @(#)AluCarId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * AluCarId generated by hbm2java
 */
public class AluCarId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer acaAgnoIng;
    private Integer acaCodCar;
    private Integer acaRut;
    private Integer acaSemIng;

    /**
     *
     */
    public AluCarId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAcaRut() {
        return this.acaRut;
    }

    /**
     * Method description
     *
     * @param acaRut
     */
    public void setAcaRut(Integer acaRut) {
        this.acaRut = acaRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAcaCodCar() {
        return this.acaCodCar;
    }

    /**
     * Method description
     *
     * @param acaCodCar
     */
    public void setAcaCodCar(Integer acaCodCar) {
        this.acaCodCar = acaCodCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAcaAgnoIng() {
        return this.acaAgnoIng;
    }

    /**
     * Method description
     *
     * @param acaAgnoIng
     */
    public void setAcaAgnoIng(Integer acaAgnoIng) {
        this.acaAgnoIng = acaAgnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAcaSemIng() {
        return this.acaSemIng;
    }

    /**
     * Method description
     *
     * @param acaSemIng
     */
    public void setAcaSemIng(Integer acaSemIng) {
        this.acaSemIng = acaSemIng;
    }    
}
