/*
 * @(#)Alumno.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import javax.swing.*;
import static infrastructure.util.DateUtil.getDateGetterSetter;
import infrastructure.util.common.CommonUsersUtil;

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements Serializable {

    private static final long serialVersionUID = 1L;

    private String aluDirecAlu;
    private String aluDirecFam;
    private String aluDv;
    private String aluEmail;
    private String aluEmailUsach;
    private String aluEmailLaboral;
    private Integer aluEstCiv;
    private Date aluFechaNac;
    private String aluFonoAlu;
    private String aluFonoFam;
    private Date aluLastLogin;
    private String aluMaterno;
    private Integer aluNacionalidad;
    private String aluNombre;
    private String aluNombreSocial;
    private String aluPaterno;
    private Integer aluRut;
    private String aluSexo;
    private Integer aluSitMili;
    private Comuna comunaAlu;
    private Comuna comunaFam;
    private ImageIcon foto;
    private Pais pais;
    private Region regionByAluRegionAlu;
    private Region regionByAluRegionFam;
    private String aluFonoEmerg;
    private String aluContactoEmerg;


    /**
     *
     */
    public Alumno() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAluRut() {
        return this.aluRut;
    }

    /**
     * Method description
     *
     * @param aluRut
     */
    public void setAluRut(Integer aluRut) {
        this.aluRut = aluRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Pais getPais() {
        return this.pais;
    }

    /**
     * Method description
     *
     * @param pais
     */
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    /**
     * Method description
     *
     * @return
     */
    public Region getRegionByAluRegionFam() {
        return this.regionByAluRegionFam;
    }

    /**
     * Method description
     *
     * @param regionByAluRegionFam
     */
    public void setRegionByAluRegionFam(Region regionByAluRegionFam) {
        this.regionByAluRegionFam = regionByAluRegionFam;
    }

    /**
     * Method description
     *
     * @return
     */
    public Region getRegionByAluRegionAlu() {
        return this.regionByAluRegionAlu;
    }

    /**
     * Method description
     *
     * @param regionByAluRegionAlu
     */
    public void setRegionByAluRegionAlu(Region regionByAluRegionAlu) {
        this.regionByAluRegionAlu = regionByAluRegionAlu;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluDv() {
        return this.aluDv;
    }

    /**
     * Method description
     *
     * @param aluDv
     */
    public void setAluDv(String aluDv) {
        this.aluDv = aluDv;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluPaterno() {
        return this.aluPaterno;
    }

    /**
     * Method description
     *
     * @param aluPaterno
     */
    public void setAluPaterno(String aluPaterno) {
        this.aluPaterno = aluPaterno;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluMaterno() {
        return this.aluMaterno==null?"":this.aluMaterno;
    }

    /**
     * Method description
     *
     * @param aluMaterno
     */
    public void setAluMaterno(String aluMaterno) {
        this.aluMaterno = aluMaterno;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluNombre() {
        return this.aluNombre;
    }

    /**
     * Method description
     *
     * @param aluNombre
     */
    public void setAluNombre(String aluNombre) {
        this.aluNombre = aluNombre;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluSexo() {
        return this.aluSexo;
    }

    /**
     * Method description
     *
     * @param aluSexo
     */
    public void setAluSexo(String aluSexo) {
        this.aluSexo = aluSexo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluDirecFam() {
        return this.aluDirecFam;
    }

    /**
     * Method description
     *
     * @param aluDirecFam
     */
    public void setAluDirecFam(String aluDirecFam) {
        this.aluDirecFam = aluDirecFam;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluDirecAlu() {
        return this.aluDirecAlu;
    }

    /**
     * Method description
     *
     * @param aluDirecAlu
     */
    public void setAluDirecAlu(String aluDirecAlu) {
        this.aluDirecAlu = aluDirecAlu;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAluSitMili() {
        return this.aluSitMili;
    }

    /**
     * Method description
     *
     * @param aluSitMili
     */
    public void setAluSitMili(Integer aluSitMili) {
        this.aluSitMili = aluSitMili;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getAluFechaNac() {
        return getDateGetterSetter(aluFechaNac);
    }

    /**
     * Method description
     *
     * @param aluFechaNac
     */
    public void setAluFechaNac(Date aluFechaNac) {
        this.aluFechaNac = getDateGetterSetter(aluFechaNac);
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAluNacionalidad() {
        return this.aluNacionalidad;
    }

    /**
     * Method description
     *
     * @param aluNacionalidad
     */
    public void setAluNacionalidad(Integer aluNacionalidad) {
        this.aluNacionalidad = aluNacionalidad;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluFonoFam() {
        return this.aluFonoFam;
    }

    /**
     * Method description
     *
     * @param aluFonoFam
     */
    public void setAluFonoFam(String aluFonoFam) {
        this.aluFonoFam = aluFonoFam;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluFonoAlu() {
        return this.aluFonoAlu;
    }

    /**
     * Method description
     *
     * @param aluFonoAlu
     */
    public void setAluFonoAlu(String aluFonoAlu) {
        this.aluFonoAlu = aluFonoAlu;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAluEstCiv() {
        return this.aluEstCiv;
    }

    /**
     * Method description
     *
     * @param aluEstCiv
     */
    public void setAluEstCiv(Integer aluEstCiv) {
        this.aluEstCiv = aluEstCiv;
    }



    /**
     * Method description
     *
     * @return
     */
    public String getAluEmail() {
        return aluEmail;
    }

    /**
     * Method description
     *
     * @param aluEmail
     */
    public void setAluEmail(String aluEmail) {
        this.aluEmail = aluEmail;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluEmailUsach() {
        return aluEmailUsach;
    }

    /**
     *
     * @param aluEmailUsach
     */
    public void setAluEmailUsach(String aluEmailUsach) {
        this.aluEmailUsach = aluEmailUsach;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAluEmailLaboral() {
        return aluEmailLaboral;
    }

    /**
     * Method description
     *
     * @param aluEmailLaboral
     */
    public void setAluEmailLaboral(String aluEmailLaboral) {
        this.aluEmailLaboral = aluEmailLaboral;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getAluLastLogin() {
        return (this.aluLastLogin != null)
                ? new Date(this.aluLastLogin.getTime())
                : null;
    }

    /**
     * Method description
     *
     * @param aluLastLogin
     */
    public void setAluLastLogin(Date aluLastLogin) {
        if (aluLastLogin != null) {
            this.aluLastLogin = new Date(aluLastLogin.getTime());
        }
    }

    /**
     * Method description
     *
     * @return
     */
    public ImageIcon getFoto() {
        return foto;
    }

    /**
     * Method description
     *
     * @param foto
     */
    public void setFoto(ImageIcon foto) {
        this.foto = foto;
    }

    /**
     * Method description
     *
     * @return
     */
    public Comuna getComunaAlu() {
        return comunaAlu;
    }

    /**
     * Method description
     *
     * @param comunaAlu
     */
    public void setComunaAlu(Comuna comunaAlu) {
        this.comunaAlu = comunaAlu;
    }

    /**
     * Method description
     *
     * @return
     */
    public Comuna getComunaFam() {
        return comunaFam;
    }

    /**
     * Method description
     *
     * @param comunaFam
     */
    public void setComunaFam(Comuna comunaFam) {
        this.comunaFam = comunaFam;
    }

    public String getAluFonoEmerg() {
        return aluFonoEmerg;
    }

    public void setAluFonoEmerg(String aluFonoEmerg) {
        this.aluFonoEmerg = aluFonoEmerg;
    }

    public String getAluContactoEmerg() {
        return aluContactoEmerg;
    }

    public void setAluContactoEmerg(String aluContactoEmerg) {
        this.aluContactoEmerg = aluContactoEmerg;
    }


    /**
     * BUSINESS LOGIC
     *
     * @return
     */
    public String getNombre() {
        return CommonUsersUtil.getNombre(this.aluPaterno, this.aluMaterno, this.aluNombre);
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getNombreConSeparador() {
        return CommonUsersUtil.getNombreConSeparador(this.aluPaterno, this.aluMaterno, this.aluNombre);
    }

    public String getAluNombreSocial() {
        return aluNombreSocial;
    }

    public void setAluNombreSocial(String aluNombreSocial) {
        this.aluNombreSocial = aluNombreSocial;
    }
    
    

    /**
     * Method description
     *
     * @return
     */
    public String getNombreStd() {
        return CommonUsersUtil.getNombreStd(this.aluPaterno, this.aluMaterno, this.aluNombre);
    }
    
    public String getNombreSocialStd() {
        return CommonUsersUtil.getNombreStd(this.aluPaterno, this.aluMaterno, this.aluNombreSocial==null?this.aluNombre:this.aluNombreSocial);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreStdConSeparador() {
        return CommonUsersUtil.getNombreStdConSeparador(this.aluPaterno, this.aluMaterno, this.aluNombre);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreMensaje() {
        return CommonUsersUtil.getNombreMensaje(this.aluPaterno, this.aluMaterno, this.aluNombre);
    }
}
