package domain.model;
// Generated 14-08-2014 03:40:22 PM by Hibernate Tools 3.2.1.GA

/**
 * FichaLaboral generated by hbm2java
 */
public class AlumnoEmpleador implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer aemCorrel;
    private Empleador empleador;
    private Alumno alumno;
    private ActividadEconomica actividadEconomica;
    private Integer aemDesdeMes;
    private Integer aemDesdeAgno;
    private Integer aemHastaMes;
    private Integer aemHastaAgno;

    /**
     *
     */
    public AlumnoEmpleador() {
    }

    /**
     *
     * @return
     */
    public Integer getAemCorrel() {
        return this.aemCorrel;
    }

    /**
     *
     * @param aemCorrel
     */
    public void setAemCorrel(Integer aemCorrel) {
        this.aemCorrel = aemCorrel;
    }

    /**
     *
     * @return
     */
    public Empleador getEmpleador() {
        return this.empleador;
    }

    /**
     *
     * @param empleador
     */
    public void setEmpleador(Empleador empleador) {
        this.empleador = empleador;
    }



    /**
     *
     * @return
     */
    public Alumno getAlumno() {
        return this.alumno;
    }

    /**
     *
     * @param alumno
     */
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    /**
     *
     * @return
     */
    public ActividadEconomica getActividadEconomica() {
        return this.actividadEconomica;
    }

    /**
     *
     * @param actividadEconomica
     */
    public void setActividadEconomica(ActividadEconomica actividadEconomica) {
        this.actividadEconomica = actividadEconomica;
    }

    /**
     *
     * @return
     */
    public Integer getAemDesdeMes() {
        return this.aemDesdeMes;
    }

    /**
     *
     * @param aemDesdeMes
     */
    public void setAemDesdeMes(Integer aemDesdeMes) {
        this.aemDesdeMes = aemDesdeMes;
    }

    /**
     *
     * @return
     */
    public Integer getAemDesdeAgno() {
        return this.aemDesdeAgno;
    }

    /**
     *
     * @param aemDesdeAgno
     */
    public void setAemDesdeAgno(Integer aemDesdeAgno) {
        this.aemDesdeAgno = aemDesdeAgno;
    }

    /**
     *
     * @return
     */
    public Integer getAemHastaMes() {
        return this.aemHastaMes;
    }

    /**
     *
     * @param aemHastaMes
     */
    public void setAemHastaMes(Integer aemHastaMes) {
        this.aemHastaMes = aemHastaMes;
    }

    /**
     *
     * @return
     */
    public Integer getAemHastaAgno() {
        return this.aemHastaAgno;
    }

    /**
     *
     * @param aemHastaAgno
     */
    public void setAemHastaAgno(Integer aemHastaAgno) {
        this.aemHastaAgno = aemHastaAgno;
    }


}
