package domain.model;
// Generated 14-08-2014 03:40:22 PM by Hibernate Tools 3.2.1.GA

/**
 * AreaTrabajo generated by hbm2java
 */
public class AreaTrabajo implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer atraId;
    private String atraNombre;

    /**
     *
     */
    public AreaTrabajo() {
    }

    /**
     *
     * @param atraId
     */
    public AreaTrabajo(Integer atraId) {
        this.atraId = atraId;
    }

    /**
     *
     * @return
     */
    public Integer getAtraId() {
        return this.atraId;
    }

    /**
     *
     * @param atraId
     */
    public void setAtraId(Integer atraId) {
        this.atraId = atraId;
    }

    /**
     *
     * @return
     */
    public String getAtraNombre() {
        return this.atraNombre;
    }

    /**
     *
     * @param atraNombre
     */
    public void setAtraNombre(String atraNombre) {
        this.atraNombre = atraNombre;
    }
}
