package domain.model;
// Generated 14-08-2014 03:40:22 PM by Hibernate Tools 3.2.1.GA

/**
 * AreaEstudio generated by hbm2java
 */
public class AreaEstudio implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer aestId;
    private String aestNombre;

    /**
     *
     */
    public AreaEstudio() {
    }

    /**
     *
     * @param aestId
     */
    public AreaEstudio(Integer aestId) {
        this.aestId = aestId;
    }

    /**
     *
     * @return
     */
    public Integer getAestId() {
        return this.aestId;
    }

    /**
     *
     * @param aestId
     */
    public void setAestId(Integer aestId) {
        this.aestId = aestId;
    }

    /**
     *
     * @return
     */
    public String getAestNombre() {
        return this.aestNombre;
    }

    /**
     *
     * @param aestNombre
     */
    public void setAestNombre(String aestNombre) {
        this.aestNombre = aestNombre;
    }
}
