/*
 * @(#)Asistencia.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia implements Serializable {

    private static final long serialVersionUID = 1L;
    private String asisAsist;
    private Integer asisMinAtraso;
    private Horario horario;
    private AsistenciaId id;

    /**
     *
     */
    public Asistencia() {
    }

    /**
     * Method description
     *
     * @return
     */
    public AsistenciaId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(AsistenciaId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Horario getHorario() {
        return this.horario;
    }

    /**
     * Method description
     *
     * @param horario
     */
    public void setHorario(Horario horario) {
        this.horario = horario;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAsisMinAtraso() {
        return this.asisMinAtraso;
    }

    /**
     * Method description
     *
     * @param asisMinAtraso
     */
    public void setAsisMinAtraso(Integer asisMinAtraso) {
        this.asisMinAtraso = asisMinAtraso;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAsisAsist() {
        return this.asisAsist;
    }

    /**
     * Method description
     *
     * @param asisAsist
     */
    public void setAsisAsist(String asisAsist) {
        this.asisAsist = asisAsist;
    }
}
