/*
 * @(#)AsistenciaId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * AsistenciaId generated by hbm2java
 */
public class AsistenciaId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer asisAgno;
    private Integer asisAsign;
    private String asisCoord;
    private String asisDia;
    private String asisElect;
    private Date asisFecha;
    private Integer asisModulo;
    private Integer asisSecc;
    private Integer asisSem;
    private String asisComp;

    /**
     *
     */
    public AsistenciaId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAsisAsign() {
        return this.asisAsign;
    }

    /**
     * Method description
     *
     * @param asisAsign
     */
    public void setAsisAsign(Integer asisAsign) {
        this.asisAsign = asisAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAsisElect() {
        return this.asisElect;
    }

    /**
     * Method description
     *
     * @param asisElect
     */
    public void setAsisElect(String asisElect) {
        this.asisElect = asisElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAsisCoord() {
        return this.asisCoord;
    }

    /**
     * Method description
     *
     * @param asisCoord
     */
    public void setAsisCoord(String asisCoord) {
        this.asisCoord = asisCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAsisSecc() {
        return this.asisSecc;
    }

    /**
     * Method description
     *
     * @param asisSecc
     */
    public void setAsisSecc(Integer asisSecc) {
        this.asisSecc = asisSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAsisAgno() {
        return this.asisAgno;
    }

    /**
     * Method description
     *
     * @param asisAgno
     */
    public void setAsisAgno(Integer asisAgno) {
        this.asisAgno = asisAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAsisSem() {
        return this.asisSem;
    }

    /**
     * Method description
     *
     * @param asisSem
     */
    public void setAsisSem(Integer asisSem) {
        this.asisSem = asisSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAsisDia() {
        return this.asisDia;
    }

    /**
     * Method description
     *
     * @param asisDia
     */
    public void setAsisDia(String asisDia) {
        this.asisDia = asisDia;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAsisModulo() {
        return this.asisModulo;
    }

    /**
     * Method description
     *
     * @param asisModulo
     */
    public void setAsisModulo(Integer asisModulo) {
        this.asisModulo = asisModulo;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getAsisFecha() {
        return getDateGetterSetter(asisFecha);
    }

    /**
     * Method description
     *
     * @param asisFecha
     */
    public void setAsisFecha(Date asisFecha) {
        this.asisFecha = getDateGetterSetter(asisFecha);
    } 

    public String getAsisComp() {
        return asisComp;
    }

    public void setAsisComp(String asisComp) {
        this.asisComp = asisComp;
    }
}
