/*
 * @(#)Ayudante.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import infrastructure.util.ActionUtil;
import infrastructure.util.ContextUtil;
import static infrastructure.util.DateUtil.getDateGetterSetter;
import infrastructure.util.common.CommonCursoUtil;
import static infrastructure.util.common.CommonCursoUtil.getDistinctAsc;
import infrastructure.util.common.CommonUsersUtil;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * Ayudante generated by hbm2java
 */
public class Ayudante implements Serializable {

    private static final long serialVersionUID = 1L;
    private Set<CursoAyudante> cursos = new HashSet<>(0);
    private String ayuDv;
    private String ayuEmail;
    private Date ayuLastLogin;
    private String ayuMaterno;
    private String ayuNombre;
    private String ayuPaterno;
    private Integer ayuRut;
    private String ayuTipo;
    private List<Curso> carga;
    private List<Curso> cargaHistorica;
    private Region regionByAyuRegion;
    private Comuna comuna;
    private String ayuDirec;
    private String ayuFono;

    /**
     * Method description
     *
     * @return
     */
    public String getAyuDv() {
        return ayuDv;
    }

    /**
     * Method description
     *
     * @param ayuDv
     */
    public void setAyuDv(String ayuDv) {
        this.ayuDv = ayuDv;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAyuMaterno() {
        return ayuMaterno;
    }

    /**
     * Method description
     *
     * @param ayuMaterno
     */
    public void setAyuMaterno(String ayuMaterno) {
        this.ayuMaterno = ayuMaterno;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAyuNombre() {
        return ayuNombre;
    }

    /**
     * Method description
     *
     * @param ayuNombre
     */
    public void setAyuNombre(String ayuNombre) {
        this.ayuNombre = ayuNombre;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAyuPaterno() {
        return ayuPaterno;
    }

    /**
     * Method description
     *
     * @param ayuPaterno
     */
    public void setAyuPaterno(String ayuPaterno) {
        this.ayuPaterno = ayuPaterno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getAyuRut() {
        return ayuRut;
    }

    /**
     * Method description
     *
     * @param ayuRut
     */
    public void setAyuRut(Integer ayuRut) {
        this.ayuRut = ayuRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAyuTipo() {
        return ayuTipo;
    }

    /**
     * Method description
     *
     * @param ayuTipo
     */
    public void setAyuTipo(String ayuTipo) {
        this.ayuTipo = ayuTipo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getAyuEmail() {
        return ayuEmail;
    }

    /**
     * Method description
     *
     * @param ayuEmail
     */
    public void setAyuEmail(String ayuEmail) {
        this.ayuEmail = ayuEmail;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getAyuLastLogin() {
        return getDateGetterSetter(ayuLastLogin);
    }

    /**
     * Method description
     *
     * @param ayuLastLogin
     */
    public void setAyuLastLogin(Date ayuLastLogin) {
        this.ayuLastLogin = getDateGetterSetter(ayuLastLogin);
    }

    /**
     *
     * @return
     */
    public Region getRegionByAyuRegion() {
        return regionByAyuRegion;
    }

    /**
     *
     * @param regionByAyuRegion
     */
    public void setRegionByAyuRegion(Region regionByAyuRegion) {
        this.regionByAyuRegion = regionByAyuRegion;
    }

    /**
     *
     * @return
     */
    public Comuna getComuna() {
        return comuna;
    }

    /**
     *
     * @param comuna
     */
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }

    /**
     *
     * @return
     */
    public String getAyuDirec() {
        return ayuDirec;
    }

    /**
     *
     * @param ayuDirec
     */
    public void setAyuDirec(String ayuDirec) {
        this.ayuDirec = ayuDirec;
    }

    /**
     *
     * @return
     */
    public String getAyuFono() {
        return ayuFono;
    }

    /**
     *
     * @param ayuFono
     */
    public void setAyuFono(String ayuFono) {
        this.ayuFono = ayuFono;
    }

    /**
     *
     * @return
     */
    public Set<CursoAyudante> getCursos() {
        return cursos;
    }

    /**
     *
     * @param cursos
     */
    public void setCursos(Set<CursoAyudante> cursos) {
        this.cursos = cursos;
    }

    public List<Curso> getCargaHistorica() {
        return cargaHistorica;
    }

    public void setCargaHistorica(List<Curso> cargaHistorica) {
        this.cargaHistorica = cargaHistorica;
    }



    /**
     * BUSINESS LOGIC
     *
     * @return
     */
    public String getNombre() {
        return CommonUsersUtil.getNombre(this.ayuPaterno, this.ayuMaterno, this.ayuNombre);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreMensaje() {
        return CommonUsersUtil.getNombreMensaje(this.ayuPaterno, this.ayuMaterno, this.ayuNombre);
    }

    /**
     * Method description
     *
     * @return
     */
    public List<Curso> getCarga() {
        return carga;
    }

    /**
     * Method description
     */
    public void setCarga() {
        this.carga = getDistinctAsc(ContextUtil.getDAO().getAyudantePersistence(ActionUtil.getDBUser()).findCarga(
                        this.ayuRut));
    }


    public void setCargaHistorica() {
        this.cargaHistorica = CommonCursoUtil.getCargaHistoricaAyudante(this.ayuRut);
    }
}
