/*
 * @(#)CalificacionId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CalificacionId generated by hbm2java
 */
public class CalificacionId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer calAgno;
    private Integer calAgnoIng;
    private Integer calAsign;
    private Integer calCodCar;
    private String calElect;
    private Integer calRut;
    private Integer calSem;
    private Integer calSemIng;

    /**
     *
     */
    public CalificacionId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalRut() {
        return this.calRut;
    }

    /**
     * Method description
     *
     * @param calRut
     */
    public void setCalRut(Integer calRut) {
        this.calRut = calRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalCodCar() {
        return this.calCodCar;
    }

    /**
     * Method description
     *
     * @param calCodCar
     */
    public void setCalCodCar(Integer calCodCar) {
        this.calCodCar = calCodCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalAgnoIng() {
        return this.calAgnoIng;
    }

    /**
     * Method description
     *
     * @param calAgnoIng
     */
    public void setCalAgnoIng(Integer calAgnoIng) {
        this.calAgnoIng = calAgnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalSemIng() {
        return this.calSemIng;
    }

    /**
     * Method description
     *
     * @param calSemIng
     */
    public void setCalSemIng(Integer calSemIng) {
        this.calSemIng = calSemIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalAsign() {
        return this.calAsign;
    }

    /**
     * Method description
     *
     * @param calAsign
     */
    public void setCalAsign(Integer calAsign) {
        this.calAsign = calAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCalElect() {
        return this.calElect;
    }

    /**
     * Method description
     *
     * @param calElect
     */
    public void setCalElect(String calElect) {
        this.calElect = calElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalAgno() {
        return this.calAgno;
    }

    /**
     * Method description
     *
     * @param calAgno
     */
    public void setCalAgno(Integer calAgno) {
        this.calAgno = calAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalSem() {
        return this.calSem;
    }

    /**
     * Method description
     *
     * @param calSem
     */
    public void setCalSem(Integer calSem) {
        this.calSem = calSem;
    }    
}
