/*
 * @(#)CalificacionLogroAdicionalId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CalificacionOtroReqTitId generated by hbm2java
 */
public class CalificacionLogroAdicionalId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer claAgno;
    private Integer claAgnoIng;
    private Integer claCodCar;
    private Integer claReq;
    private Integer claRut;
    private Integer claSem;
    private Integer claSemIng;

    /**
     *
     */
    public CalificacionLogroAdicionalId() {
    }

    public Integer getClaAgno() {
        return claAgno;
    }

    public void setClaAgno(Integer claAgno) {
        this.claAgno = claAgno;
    }

    public Integer getClaAgnoIng() {
        return claAgnoIng;
    }

    public void setClaAgnoIng(Integer claAgnoIng) {
        this.claAgnoIng = claAgnoIng;
    }

    public Integer getClaCodCar() {
        return claCodCar;
    }

    public void setClaCodCar(Integer claCodCar) {
        this.claCodCar = claCodCar;
    }

    public Integer getClaReq() {
        return claReq;
    }

    public void setClaReq(Integer claReq) {
        this.claReq = claReq;
    }

    public Integer getClaRut() {
        return claRut;
    }

    public void setClaRut(Integer claRut) {
        this.claRut = claRut;
    }

    public Integer getClaSem() {
        return claSem;
    }

    public void setClaSem(Integer claSem) {
        this.claSem = claSem;
    }

    public Integer getClaSemIng() {
        return claSemIng;
    }

    public void setClaSemIng(Integer claSemIng) {
        this.claSemIng = claSemIng;
    }
}
