/*
 * @(#)Calificacion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Calificacion generated by hbm2java
 */
public class Calificacion implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Asignatura asignatura;
    private String calConcep;
    private String calCoord;
    private Integer calDocto;
    private Integer calElectAsign;
    private String calElectElect;
    private String calElectFlag;
    private BigDecimal calNotaFin;
    private Integer calSecc;
    private Long calSeq;
    private String calSitAlu;
    private Electivo electivo;
    private CalificacionId id;
    private String nombreFull;
    private ProcedenciaCalificacion procedenciaCalificacion;

    /**
     *
     */
    public Calificacion() {
    }

    /**
     * Method description
     *
     * @return
     */
    public CalificacionId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(CalificacionId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Asignatura getAsignatura() {
        return this.asignatura;
    }

    /**
     * Method description
     *
     * @param asignatura
     */
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCalCoord() {
        return this.calCoord;
    }

    /**
     * Method description
     *
     * @param calCoord
     */
    public void setCalCoord(String calCoord) {
        this.calCoord = calCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalSecc() {
        return this.calSecc;
    }

    /**
     * Method description
     *
     * @param calSecc
     */
    public void setCalSecc(Integer calSecc) {
        this.calSecc = calSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public BigDecimal getCalNotaFin() {
        return this.calNotaFin;
    }

    /**
     * Method description
     *
     * @param calNotaFin
     */
    public void setCalNotaFin(BigDecimal calNotaFin) {
        this.calNotaFin = calNotaFin;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCalConcep() {
        return this.calConcep;
    }

    /**
     * Method description
     *
     * @param calConcep
     */
    public void setCalConcep(String calConcep) {
        this.calConcep = calConcep;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCalSitAlu() {
        return this.calSitAlu;
    }

    /**
     * Method description
     *
     * @param calSitAlu
     */
    public void setCalSitAlu(String calSitAlu) {
        this.calSitAlu = calSitAlu;
    }

    /**
     * Method description
     *
     * @return
     */
    public Long getCalSeq() {
        return this.calSeq;
    }

    /**
     * Method description
     *
     * @param calSeq
     */
    public void setCalSeq(Long calSeq) {
        this.calSeq = calSeq;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCalDocto() {
        return this.calDocto;
    }

    /**
     * Method description
     *
     * @param calDocto
     */
    public void setCalDocto(Integer calDocto) {
        this.calDocto = calDocto;
    }

    /**
     * Method description
     *
     * @return
     */
    public ProcedenciaCalificacion getProcedenciaCalificacion() {
        return procedenciaCalificacion;
    }

    /**
     * Method description
     *
     * @param procedenciaCalificacion
     */
    public void setProcedenciaCalificacion(ProcedenciaCalificacion procedenciaCalificacion) {
        this.procedenciaCalificacion = procedenciaCalificacion;
    }

    /**
     * Method description
     *
     * @param nombreFull
     */
    public void setNombreFull(String nombreFull) {
        this.nombreFull = nombreFull;
    }

    /**
     * Method description
     *
     * @return
     */
    public Electivo getElectivo() {
        return electivo;
    }

    /**
     * Method description
     *
     * @param electivo
     */
    public void setElectivo(Electivo electivo) {
        this.electivo = electivo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreFull() {
        return nombreFull;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getCalElectAsign() {
        return calElectAsign;
    }

    /**
     * Method description
     *
     *
     * @param calElectAsign
     */
    public void setCalElectAsign(Integer calElectAsign) {
        this.calElectAsign = calElectAsign;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getCalElectElect() {
        return calElectElect;
    }

    /**
     * Method description
     *
     *
     * @param calElectElect
     */
    public void setCalElectElect(String calElectElect) {
        this.calElectElect = calElectElect;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getCalElectFlag() {
        return calElectFlag;
    }

    /**
     * Method description
     *
     *
     * @param calElectFlag
     */
    public void setCalElectFlag(String calElectFlag) {
        this.calElectFlag = calElectFlag;
    }
}
