/*
 * @(#)CalificacionLogroAdicional.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * CalificacionLogroAdicional generated by hbm2java
 */
public class CalificacionLogroAdicional implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private String claConcep;
    private Date claFecha;
    private Date claFechaDoct;
    private String claGlosa;
    private BigDecimal claNota;
    private Integer claNroDoct;
    private String claSitAlu;
    private CalificacionLogroAdicionalId id;
    private TrequisitoLogroAdicional trequisitoLogroAdicional;

    /**
     *
     */
    public CalificacionLogroAdicional() {
    }

    public AluCar getAluCar() {
        return aluCar;
    }

    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    public String getClaConcep() {
        return claConcep;
    }

    public void setClaConcep(String claConcep) {
        this.claConcep = claConcep;
    }

    public Date getClaFecha() {
        return claFecha;
    }

    public void setClaFecha(Date claFecha) {
        this.claFecha = claFecha;
    }

    public Date getClaFechaDoct() {
        return claFechaDoct;
    }

    public void setClaFechaDoct(Date claFechaDoct) {
        this.claFechaDoct = claFechaDoct;
    }

    public String getClaGlosa() {
        return claGlosa;
    }

    public void setClaGlosa(String claGlosa) {
        this.claGlosa = claGlosa;
    }

    public BigDecimal getClaNota() {
        return claNota;
    }

    public void setClaNota(BigDecimal claNota) {
        this.claNota = claNota;
    }

    public Integer getClaNroDoct() {
        return claNroDoct;
    }

    public void setClaNroDoct(Integer claNroDoct) {
        this.claNroDoct = claNroDoct;
    }

    public String getClaSitAlu() {
        return claSitAlu;
    }

    public void setClaSitAlu(String claSitAlu) {
        this.claSitAlu = claSitAlu;
    }

    public CalificacionLogroAdicionalId getId() {
        return id;
    }

    public void setId(CalificacionLogroAdicionalId id) {
        this.id = id;
    }

    public TrequisitoLogroAdicional getTrequisitoLogroAdicional() {
        return trequisitoLogroAdicional;
    }

    public void setTrequisitoLogroAdicional(TrequisitoLogroAdicional trequisitoLogroAdicional) {
        this.trequisitoLogroAdicional = trequisitoLogroAdicional;
    }

   
}
