/*
 * @(#)Carrera.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Carrera generated by hbm2java
 */
public class Carrera implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer carCod;
    private Especialidad especialidad;
    private Tcarrera tcarrera;
    private Tprograma tprograma;
    private String carRegimen;

    /**
     *
     */
    public Carrera() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCarCod() {
        return this.carCod;
    }

    /**
     * Method description
     *
     * @param carCod
     */
    public void setCarCod(Integer carCod) {
        this.carCod = carCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }

    /**
     * Method description
     *
     * @param especialidad
     */
    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }

    /**
     * Method description
     *
     * @return
     */
    public Tcarrera getTcarrera() {
        return this.tcarrera;
    }

    /**
     * Method description
     *
     * @param tcarrera
     */
    public void setTcarrera(Tcarrera tcarrera) {
        this.tcarrera = tcarrera;
    }

    public Tprograma getTprograma() {
        return tprograma;
    }

    public void setTprograma(Tprograma tprograma) {
        this.tprograma = tprograma;
    }

    public String getCarRegimen() {
        return carRegimen;
    }

    public void setCarRegimen(String carRegimen) {
        this.carRegimen = carRegimen;
    }
}
