/*
 * @(#)CcalidadId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CcalidadId generated by hbm2java
 */
public class CcalidadId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer ccaAgno;
    private Integer ccaAgnoIng;
    private Integer ccaCodCar;
    private Integer ccaRut;
    private Integer ccaSem;
    private Integer ccaSemIng;
    private Integer ccaTipoCal;

    /**
     *
     */
    public CcalidadId() {
    }

    /**
     *
     * @return
     */
    public Integer getCcaAgno() {
        return ccaAgno;
    }

    /**
     *
     * @param ccaAgno
     */
    public void setCcaAgno(Integer ccaAgno) {
        this.ccaAgno = ccaAgno;
    }

    /**
     *
     * @return
     */
    public Integer getCcaAgnoIng() {
        return ccaAgnoIng;
    }

    /**
     *
     * @param ccaAgnoIng
     */
    public void setCcaAgnoIng(Integer ccaAgnoIng) {
        this.ccaAgnoIng = ccaAgnoIng;
    }

    /**
     *
     * @return
     */
    public Integer getCcaCodCar() {
        return ccaCodCar;
    }

    /**
     *
     * @param ccaCodCar
     */
    public void setCcaCodCar(Integer ccaCodCar) {
        this.ccaCodCar = ccaCodCar;
    }

    /**
     *
     * @return
     */
    public Integer getCcaRut() {
        return ccaRut;
    }

    /**
     *
     * @param ccaRut
     */
    public void setCcaRut(Integer ccaRut) {
        this.ccaRut = ccaRut;
    }

    /**
     *
     * @return
     */
    public Integer getCcaSem() {
        return ccaSem;
    }

    /**
     *
     * @param ccaSem
     */
    public void setCcaSem(Integer ccaSem) {
        this.ccaSem = ccaSem;
    }

    /**
     *
     * @return
     */
    public Integer getCcaSemIng() {
        return ccaSemIng;
    }

    /**
     *
     * @param ccaSemIng
     */
    public void setCcaSemIng(Integer ccaSemIng) {
        this.ccaSemIng = ccaSemIng;
    }

    /**
     *
     * @return
     */
    public Integer getCcaTipoCal() {
        return ccaTipoCal;
    }

    /**
     *
     * @param ccaTipoCal
     */
    public void setCcaTipoCal(Integer ccaTipoCal) {
        this.ccaTipoCal = ccaTipoCal;
    }    
}
