/*
 * @(#)Ccalidad.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * Ccalidad generated by hbm2java
 */
public class Ccalidad implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Date ccaFecha;
    private CcalidadId id;
    private Tcalidad tcalidad;

    /**
     *
     */
    public Ccalidad() {
    }

    /**
     * Method description
     *
     * @return
     */
    public CcalidadId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(CcalidadId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Tcalidad getTcalidad() {
        return this.tcalidad;
    }

    /**
     * Method description
     *
     * @param tcalidad
     */
    public void setTcalidad(Tcalidad tcalidad) {
        this.tcalidad = tcalidad;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getCcaFecha() {
        return getDateGetterSetter(ccaFecha);
    }

    /**
     * Method description
     *
     * @param ccaFecha
     */
    public void setCcaFecha(Date ccaFecha) {
        this.ccaFecha = getDateGetterSetter(ccaFecha);
    }
}
