/*
 * @(#)ComentarioEncuestaDocente.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ComentarioEncuestaDocente generated by hbm2java
 */
public class ComentarioEncuestaDocente implements Serializable {

    private static final long serialVersionUID = 1L;
    private String cedComen1;
    private String cedComen2;
    private String cedComen3;
    private Integer cedCorrel;
    private CursoProfesor cursoProfesor;
    private EncuestaDocente encuestaDocente;
    private Integer cedCorrelAlu;
    private Integer cedRut;

    /**
     *
     */
    public ComentarioEncuestaDocente() {
    }

    /**
     *
     * @return
     */
    public EncuestaDocente getEncuestaDocente() {
        return encuestaDocente;
    }

    /**
     *
     * @param encuestaDocente
     */
    public void setEncuestaDocente(EncuestaDocente encuestaDocente) {
        this.encuestaDocente = encuestaDocente;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public CursoProfesor getCursoProfesor() {
        return cursoProfesor;
    }

    /**
     * Method description
     *
     *
     * @param cursoProfesor
     */
    public void setCursoProfesor(CursoProfesor cursoProfesor) {
        this.cursoProfesor = cursoProfesor;
    }

    /**
     *
     * @return
     */
    public String getCedComen1() {
        return cedComen1;
    }

    /**
     *
     * @param cedComen1
     */
    public void setCedComen1(String cedComen1) {
        this.cedComen1 = cedComen1;
    }

    /**
     *
     * @return
     */
    public String getCedComen2() {
        return cedComen2;
    }

    /**
     *
     * @param cedComen2
     */
    public void setCedComen2(String cedComen2) {
        this.cedComen2 = cedComen2;
    }

    /**
     *
     * @return
     */
    public Integer getCedCorrel() {
        return cedCorrel;
    }

    /**
     *
     * @param cedCorrel
     */
    public void setCedCorrel(Integer cedCorrel) {
        this.cedCorrel = cedCorrel;
    }

    /**
     *
     * @return
     */
    public String getCedComen3() {
        return cedComen3;
    }

    /**
     *
     * @param cedComen3
     */
    public void setCedComen3(String cedComen3) {
        this.cedComen3 = cedComen3;
    }

    public Integer getCedCorrelAlu() {
        return cedCorrelAlu;
    }

    public void setCedCorrelAlu(Integer cedCorrelAlu) {
        this.cedCorrelAlu = cedCorrelAlu;
    }

    public Integer getCedRut() {
        return cedRut;
    }

    public void setCedRut(Integer cedRut) {
        this.cedRut = cedRut;
    }
}
