/*
 * @(#)ComentarioEncuestaAyudante.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ComentarioEncuestaDocente generated by hbm2java
 */
public class ComentarioEncuestaAyudante implements Serializable {

    private static final long serialVersionUID = 1L;
    private String ceaComen1;
    private String ceaComen2;
    private Integer ceaCorrel;
    private CursoAyudante cursoAyudante;
    private EncuestaAyudante encuestaAyudante;

    /**
     *
     */
    public ComentarioEncuestaAyudante() {
    }

    /**
     *
     * @return
     */
    public String getCeaComen1() {
        return ceaComen1;
    }

    /**
     *
     * @param ceaComen1
     */
    public void setCeaComen1(String ceaComen1) {
        this.ceaComen1 = ceaComen1;
    }

    /**
     *
     * @return
     */
    public String getCeaComen2() {
        return ceaComen2;
    }

    /**
     *
     * @param ceaComen2
     */
    public void setCeaComen2(String ceaComen2) {
        this.ceaComen2 = ceaComen2;
    }

    /**
     *
     * @return
     */
    public Integer getCeaCorrel() {
        return ceaCorrel;
    }

    /**
     *
     * @param ceaCorrel
     */
    public void setCeaCorrel(Integer ceaCorrel) {
        this.ceaCorrel = ceaCorrel;
    }

    /**
     *
     * @return
     */
    public CursoAyudante getCursoAyudante() {
        return cursoAyudante;
    }

    /**
     *
     * @param cursoAyudante
     */
    public void setCursoAyudante(CursoAyudante cursoAyudante) {
        this.cursoAyudante = cursoAyudante;
    }

    /**
     *
     * @return
     */
    public EncuestaAyudante getEncuestaAyudante() {
        return encuestaAyudante;
    }

    /**
     *
     * @param encuestaAyudante
     */
    public void setEncuestaAyudante(EncuestaAyudante encuestaAyudante) {
        this.encuestaAyudante = encuestaAyudante;
    }
}
