/*
 * @(#)CursoEnctaId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * CursoEnctaId generated by hbm2java
 */
public class CursoEncuestaDocenteId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer cedAgno;
    private Integer cedAsign;
    private String cedCoord;
    private String cedElect;
    private BigDecimal cedProArea;
    private BigDecimal cedPromCur;
    private Integer cedSecc;
    private Integer cedSem;
    private String cedComp;

    /**
     *
     */
    public CursoEncuestaDocenteId() {
    }

    /**
     *
     * @return
     */
    public Integer getCedAgno() {
        return cedAgno;
    }

    /**
     *
     * @param cedAgno
     */
    public void setCedAgno(Integer cedAgno) {
        this.cedAgno = cedAgno;
    }

    /**
     *
     * @return
     */
    public Integer getCedAsign() {
        return cedAsign;
    }

    /**
     *
     * @param cedAsign
     */
    public void setCedAsign(Integer cedAsign) {
        this.cedAsign = cedAsign;
    }

    /**
     *
     * @return
     */
    public String getCedCoord() {
        return cedCoord;
    }

    /**
     *
     * @param cedCoord
     */
    public void setCedCoord(String cedCoord) {
        this.cedCoord = cedCoord;
    }

    /**
     *
     * @return
     */
    public String getCedElect() {
        return cedElect;
    }

    /**
     *
     * @param cedElect
     */
    public void setCedElect(String cedElect) {
        this.cedElect = cedElect;
    }

    /**
     *
     * @return
     */
    public BigDecimal getCedProArea() {
        return cedProArea;
    }

    /**
     *
     * @param cedProArea
     */
    public void setCedProArea(BigDecimal cedProArea) {
        this.cedProArea = cedProArea;
    }

    /**
     *
     * @return
     */
    public BigDecimal getCedPromCur() {
        return cedPromCur;
    }

    /**
     *
     * @param cedPromCur
     */
    public void setCedPromCur(BigDecimal cedPromCur) {
        this.cedPromCur = cedPromCur;
    }

    /**
     *
     * @return
     */
    public Integer getCedSecc() {
        return cedSecc;
    }

    /**
     *
     * @param cedSecc
     */
    public void setCedSecc(Integer cedSecc) {
        this.cedSecc = cedSecc;
    }

    /**
     *
     * @return
     */
    public Integer getCedSem() {
        return cedSem;
    }

    /**
     *
     * @param cedSem
     */
    public void setCedSem(Integer cedSem) {
        this.cedSem = cedSem;
    }

    public String getCedComp() {
        return cedComp;
    }

    public void setCedComp(String cedComp) {
        this.cedComp = cedComp;
    }
}
