/*
 * @(#)CursoCarrera.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CursoCarrera generated by hbm2java
 */
public class CursoCarrera implements Serializable {

    private static final long serialVersionUID = 1L;
    private Curso curso;
    private CursoCarreraId id;
    private Mencion mencion;

    /**
     *
     */
    public CursoCarrera() {
    }

    /**
     *
     * @param id
     */
    public CursoCarrera(CursoCarreraId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public CursoCarreraId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(CursoCarreraId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Mencion getMencion() {
        return mencion;
    }

    /**
     * Method description
     *
     * @param mencion
     */
    public void setMencion(Mencion mencion) {
        this.mencion = mencion;
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
}
