/*
 * @(#)CursoEncuestaAyudanteId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * CursoEnctaId generated by hbm2java
 */
public class CursoEncuestaAyudanteId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer ceaAgno;
    private Integer ceaAsign;
    private String ceaCoord;
    private String ceaElect;
    private BigDecimal ceaProArea;
    private BigDecimal ceaPromCur;
    private Integer ceaSecc;
    private Integer ceaSem;
    private String ceaComp;

    /**
     *
     */
    public CursoEncuestaAyudanteId() {
    }

    /**
     *
     * @return
     */
    public Integer getCeaAgno() {
        return ceaAgno;
    }

    /**
     *
     * @param ceaAgno
     */
    public void setCeaAgno(Integer ceaAgno) {
        this.ceaAgno = ceaAgno;
    }

    /**
     *
     * @return
     */
    public Integer getCeaAsign() {
        return ceaAsign;
    }

    /**
     *
     * @param ceaAsign
     */
    public void setCeaAsign(Integer ceaAsign) {
        this.ceaAsign = ceaAsign;
    }

    /**
     *
     * @return
     */
    public String getCeaCoord() {
        return ceaCoord;
    }

    /**
     *
     * @param ceaCoord
     */
    public void setCeaCoord(String ceaCoord) {
        this.ceaCoord = ceaCoord;
    }

    /**
     *
     * @return
     */
    public String getCeaElect() {
        return ceaElect;
    }

    /**
     *
     * @param ceaElect
     */
    public void setCeaElect(String ceaElect) {
        this.ceaElect = ceaElect;
    }

    /**
     *
     * @return
     */
    public BigDecimal getCeaProArea() {
        return ceaProArea;
    }

    /**
     *
     * @param ceaProArea
     */
    public void setCeaProArea(BigDecimal ceaProArea) {
        this.ceaProArea = ceaProArea;
    }

    /**
     *
     * @return
     */
    public BigDecimal getCeaPromCur() {
        return ceaPromCur;
    }

    /**
     *
     * @param ceaPromCur
     */
    public void setCeaPromCur(BigDecimal ceaPromCur) {
        this.ceaPromCur = ceaPromCur;
    }

    /**
     *
     * @return
     */
    public Integer getCeaSecc() {
        return ceaSecc;
    }

    /**
     *
     * @param ceaSecc
     */
    public void setCeaSecc(Integer ceaSecc) {
        this.ceaSecc = ceaSecc;
    }

    /**
     *
     * @return
     */
    public Integer getCeaSem() {
        return ceaSem;
    }

    /**
     *
     * @param ceaSem
     */
    public void setCeaSem(Integer ceaSem) {
        this.ceaSem = ceaSem;
    }

    public String getCeaComp() {
        return ceaComp;
    }

    public void setCeaComp(String ceaComp) {
        this.ceaComp = ceaComp;
    }
}
