/*
 * @(#)CursoActualView.java
 *
 * Copyright (c) 2019 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;

/**
 * Curso generated by hbm2java
 */
public class CursoActualView implements Serializable {

    private static final long serialVersionUID = 1L;
    private CursoId id;
    private String tipo;

    /**
     *
     */
    public CursoActualView() {
    }

    public CursoId getId() {
        return id;
    }

    public void setId(CursoId id) {
        this.id = id;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}
