/*
 * @(#)CursoEncta.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CursoEncta generated by hbm2java
 */
public class CursoEncuestaDocente implements Serializable {

    private static final long serialVersionUID = 1L;
    private Curso curso;
    private EncuestaDocente encuestaDocente;
    private CursoEncuestaDocenteId id;

    /**
     *
     */
    public CursoEncuestaDocente() {
    }

    /**
     * Method description
     *
     * @return
     */
    public CursoEncuestaDocenteId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(CursoEncuestaDocenteId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return this.curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     *
     * @return
     */
    public EncuestaDocente getEncuestaDocente() {
        return encuestaDocente;
    }

    /**
     *
     * @param encuestaDocente
     */
    public void setEncuestaDocente(EncuestaDocente encuestaDocente) {
        this.encuestaDocente = encuestaDocente;
    }
}
