/*
 * @(#)CursoCarreraId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CursoCarreraId generated by hbm2java
 */
public class CursoCarreraId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer ccarAgno;
    private Integer ccarAsign;
    private Integer ccarCodCar;
    private Integer ccarCodMen;
    private String ccarCoord;
    private String ccarElect;
    private Integer ccarSecc;
    private Integer ccarSem;
    private String ccarComp;

    /**
     *
     */
    public CursoCarreraId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCcarAsign() {
        return this.ccarAsign;
    }

    /**
     * Method description
     *
     * @param ccarAsign
     */
    public void setCcarAsign(Integer ccarAsign) {
        this.ccarAsign = ccarAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCcarElect() {
        return this.ccarElect;
    }

    /**
     * Method description
     *
     * @param ccarElect
     */
    public void setCcarElect(String ccarElect) {
        this.ccarElect = ccarElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCcarCoord() {
        return this.ccarCoord;
    }

    /**
     * Method description
     *
     * @param ccarCoord
     */
    public void setCcarCoord(String ccarCoord) {
        this.ccarCoord = ccarCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCcarSecc() {
        return this.ccarSecc;
    }

    /**
     * Method description
     *
     * @param ccarSecc
     */
    public void setCcarSecc(Integer ccarSecc) {
        this.ccarSecc = ccarSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCcarAgno() {
        return this.ccarAgno;
    }

    /**
     * Method description
     *
     * @param ccarAgno
     */
    public void setCcarAgno(Integer ccarAgno) {
        this.ccarAgno = ccarAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCcarSem() {
        return this.ccarSem;
    }

    /**
     * Method description
     *
     * @param ccarSem
     */
    public void setCcarSem(Integer ccarSem) {
        this.ccarSem = ccarSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCcarCodCar() {
        return this.ccarCodCar;
    }

    /**
     * Method description
     *
     * @param ccarCodCar
     */
    public void setCcarCodCar(Integer ccarCodCar) {
        this.ccarCodCar = ccarCodCar;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getCcarCodMen() {
        return ccarCodMen;
    }

    /**
     * Method description
     *
     *
     * @param ccarCodMen
     */
    public void setCcarCodMen(Integer ccarCodMen) {
        this.ccarCodMen = ccarCodMen;
    }  

    public String getCcarComp() {
        return ccarComp;
    }

    public void setCcarComp(String ccarComp) {
        this.ccarComp = ccarComp;
    }
}
