/*
 * @(#)CursoAyudante.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;

/**
 * CursoAyudante generated by hbm2java
 */
public class CursoAyudante implements Serializable {

    private static final long serialVersionUID = 1L;
    private Ayudante ayudante;
    private Character cayuTipo;
    private CursoActualView cursoActual;
    private CursoAyudanteId id;
    private Curso curso;

    /**
     *
     */
    public CursoAyudante() {
    }

    /**
     * Method description
     *
     * @return
     */
    public CursoAyudanteId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(CursoAyudanteId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Character getCayuTipo() {
        return this.cayuTipo;
    }

    /**
     * Method description
     *
     * @param cayuTipo
     */
    public void setCayuTipo(Character cayuTipo) {
        this.cayuTipo = cayuTipo;
    }

    /**
     * Method description
     *
     * @return
     */
    public Ayudante getAyudante() {
        return ayudante;
    }

    /**
     * Method description
     *
     * @param ayudante
     */
    public void setAyudante(Ayudante ayudante) {
        this.ayudante = ayudante;
    }

    /**
     * Method description
     *
     * @return
     */
    public CursoActualView getCursoActual() {
        return cursoActual;
    }

    /**
     * Method description
     *
     * @param cursoActual
     */
    public void setCursoActual(CursoActualView cursoActual) {
        this.cursoActual = cursoActual;
    }

    /**
     *
     * @return
     */
    public Curso getCurso() {
        return curso;
    }

    /**
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
}
