/*
 * @(#)CursoEncuestaAyudante.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CursoEncta generated by hbm2java
 */
public class CursoEncuestaAyudante implements Serializable {

    private static final long serialVersionUID = 1L;
    private Curso curso;
    private EncuestaAyudante encuestaAyudante;
    private CursoEncuestaAyudanteId id;

    /**
     *
     */
    public CursoEncuestaAyudante() {
    }

    /**
     *
     * @return
     */
    public Curso getCurso() {
        return curso;
    }

    /**
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     *
     * @return
     */
    public EncuestaAyudante getEncuestaAyudante() {
        return encuestaAyudante;
    }

    /**
     *
     * @param encuestaAyudante
     */
    public void setEncuestaAyudante(EncuestaAyudante encuestaAyudante) {
        this.encuestaAyudante = encuestaAyudante;
    }

    /**
     *
     * @return
     */
    public CursoEncuestaAyudanteId getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(CursoEncuestaAyudanteId id) {
        this.id = id;
    }
}
