/*
 * @(#)Curso.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.*;
import infrastructure.support.InscripcionSupport;
import infrastructure.util.ActionUtil;
import infrastructure.util.ContextUtil;
import static infrastructure.util.FormatUtil.normalizaFileName;
import infrastructure.util.common.CommonCursoUtil;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
/**
 * Curso generated by hbm2java
 */
public class Curso implements Serializable {

    private static final long serialVersionUID = 1L;
    private Asignatura asignatura;
    private Integer curCupoDis;
    private Integer curCupoIni;
    private Integer curInscritos;
    private String curEstado;
    private Date curFechaInicio;
    private Date curFechaTermino;
    private Integer curPondCat;
    private Integer curPondLab;
    private CursoActualView cursoActual;
    private Electivo electivo;
    private List<Evaluacion> evaluacionList;
    private CursoId id;
    private String curModalEval;
    private String curTipo;
    private String curJorDiurno;
    private String curJorVesp;
    private CursoEspejo espejo;
    private String curEnableProf;
    private String curEnableAyu;
    private String curEnableLab;

    /// VIRTUALES
    private String curProfesores;
    private String curAyudantes;
    private String curHorario;
    private String curSalas;
    private String curNombre;
    private Integer inscritos;

    /**
     *
     */
    public Curso() {
    }

    /**
     * BUSINESS LOGIC
     *
     * @param paramCurso
     */
    public Curso(String paramCurso) {
        this.id = CommonCursoUtil.getId(paramCurso);
    }

    /**
     * Method description
     *
     * @return
     */
    public CursoId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(CursoId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Asignatura getAsignatura() {
        return this.asignatura;
    }

    /**
     * Method description
     *
     * @param asignatura
     */
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCurPondCat() {
        return this.curPondCat;
    }

    /**
     * Method description
     *
     * @param curPondCat
     */
    public void setCurPondCat(Integer curPondCat) {
        this.curPondCat = curPondCat;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCurPondLab() {
        return this.curPondLab;
    }

    /**
     * Method description
     *
     * @param curPondLab
     */
    public void setCurPondLab(Integer curPondLab) {
        this.curPondLab = curPondLab;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCurCupoIni() {
        return this.curCupoIni;
    }

    /**
     * Method description
     *
     * @param curCupoIni
     */
    public void setCurCupoIni(Integer curCupoIni) {
        this.curCupoIni = curCupoIni;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCurCupoDis() {
        return this.curCupoDis;
    }

    /**
     * Method description
     *
     * @param curCupoDis
     */
    public void setCurCupoDis(Integer curCupoDis) {
        this.curCupoDis = curCupoDis;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCurEstado() {
        return this.curEstado;
    }

    /**
     * Method description
     *
     * @param curEstado
     */
    public void setCurEstado(String curEstado) {
        this.curEstado = curEstado;
    }

    public String getCurTipo() {
        return curTipo;
    }

    public void setCurTipo(String curTipo) {
        this.curTipo = curTipo;
    }

    public String getCurJorDiurno() {
        return curJorDiurno;
    }

    public void setCurJorDiurno(String curJorDiurno) {
        this.curJorDiurno = curJorDiurno;
    }

    public String getCurJorVesp() {
        return curJorVesp;
    }

    public void setCurJorVesp(String curJorVesp) {
        this.curJorVesp = curJorVesp;
    }

    public String getCurProfesores() {
        return curProfesores;
    }

    public void setCurProfesores(String curProfesores) {
        this.curProfesores = curProfesores;
    }

    public String getCurAyudantes() {
        return curAyudantes;
    }

    public void setCurAyudantes(String curAyudantes) {
        this.curAyudantes = curAyudantes;
    }

    public String getCurHorario() {
        return curHorario;
    }

    public void setCurHorario(String curHorario) {
        this.curHorario = curHorario;
    }

    public String getCurSalas() {
        return curSalas;
    }

    public void setCurSalas(String curSalas) {
        this.curSalas = curSalas;
    }

    public String getCurNombre() {
        return curNombre;
    }

    public void setCurNombre(String curNombre) {
        this.curNombre = curNombre;
    }

    public Integer getInscritos() {
        return inscritos;
    }

    public void setInscritos(Integer inscritos) {
        this.inscritos = inscritos;
    }

    /**
     *
     * @return
     */
    public String getCurModalEval() {
        return curModalEval;
    }

    /**
     *
     * @param curModalEval
     */
    public void setCurModalEval(String curModalEval) {
        this.curModalEval = curModalEval;
    }

    public Integer getCurInscritos() {
        return curInscritos;
    }

    public void setCurInscritos(Integer curInscritos) {
        this.curInscritos = curInscritos;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getCurFechaInicio() {
        return this.curFechaInicio != null
                ? new Date(this.curFechaInicio.getTime())
                : null;
    }

    /**
     * Method description
     *
     * @param curFechaInicio
     */
    public void setCurFechaInicio(Date curFechaInicio) {
        if (curFechaInicio != null) {
            this.curFechaInicio = new Date(curFechaInicio.getTime());
        }
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getCurFechaTermino() {
        return this.curFechaTermino != null
                ? new Date(this.curFechaTermino.getTime())
                : null;
    }

    /**
     * Method description
     *
     * @param curFechaTermino
     */
    public void setCurFechaTermino(Date curFechaTermino) {
        if (curFechaTermino != null) {
            this.curFechaTermino = new Date(curFechaTermino.getTime());
        }
    }

    /**
     * Method description
     *
     * @return
     */
    public Electivo getElectivo() {
        return electivo;
    }

    /**
     * Method description
     *
     * @param electivo
     */
    public void setElectivo(Electivo electivo) {
        this.electivo = electivo;
    }

    /**
     * Method description
     *
     * @return
     */
    public CursoActualView getCursoActual() {
        return cursoActual;
    }

    /**
     * Method description
     *
     * @param cursoActual
     */
    public void setCursoActual(CursoActualView cursoActual) {
        this.cursoActual = cursoActual;
    }

    /**
     * Method description
     *
     * @return
     */
    public List<Evaluacion> getEvaluacionList() {
        return evaluacionList;
    }

    /**
     * Method description
     *
     * @param evaluacionList
     */
    public void setEvaluacionList(List<Evaluacion> evaluacionList) {
        this.evaluacionList = evaluacionList;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreNormalizado() {
        return normalizaFileName(getNombreFull());
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreFull() {
        return getNombreCurso(200);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreCorto() {
        return getNombreCurso(50);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreHorario() {
        return getNombre(40);
    }

    private String getNombre(int largo) {
        String nombreRet = this.getCurNombre();

        if (nombreRet.length() > largo) {
            int li = nombreRet.lastIndexOf(' ');

            if (li > 0) {
                String s2 = nombreRet.substring(li + 1, nombreRet.length());

                if (s2.length() <= largo / 2) {
                    String s1 = nombreRet.substring(0, largo - 5 - s2.length());

                    nombreRet = s1 + " ... " + s2;
                } else {
                    nombreRet = nombreRet.substring(0, largo);
                }
            } else {
                nombreRet = nombreRet.substring(0, largo);
            }
        }

        return nombreRet;
    }

    /**
     * Method description
     *
     * @param largo
     * @return
     */
    private String getNombreCurso(int largo) {
        return id.getCodigo(" ") + " " + getNombre(largo);
    }

    /**
     *
     * @param sep
     * @return
     */
    public String getCodigo(String sep) {
        return id.getCodigo(sep);
    }

    /**
     *
     * @param sep
     * @return
     */
    public String getCodigoCorto(String sep) {
        return id.getCodigoCorto(sep);
    }

    /**
     * Method description
     *
     * @param userType
     * @param userTypeShort
     * @param rut
     * @param isAutoridad
     * @return
     */
    public boolean cursoPropio(String userType, String userTypeShort, Integer rut, boolean isAutoridad) {
        return ("PR".equals(userTypeShort) || isAutoridad)
                && ContextUtil.getDAO().getCursoProfesorRepository(userType).exists(this, rut);
    }

    public boolean puedeEliminar(Integer carrera, Integer mencion, Integer asign, String userTypeShort, Integer rut) {        
        return ContextUtil.getDAO().getScalarRepository(ActionUtil.getDBUser()).puedeEliminar(carrera, mencion, asign, rut, userTypeShort) == 1;
    }

    /**
     * Method description
     *
     * @return
     */
    public List<AluCar> getNominaAlumnos() {
        return InscripcionSupport.getNomina(ContextUtil.getDAO().getInscripcionRepository(ActionUtil.getDBUser()).findNomina(this));
    }

    public List<AluCar> getNominaAlumnosRanking() {
        return InscripcionSupport.getNomina(ContextUtil.getDAO().getInscripcionRepository(ActionUtil.getDBUser()).findNominaRanking(this));
    }

    public List<Integer> getRutAlumnos() {
        return ContextUtil.getDAO().getInscripcionRepository(ActionUtil.getDBUser()).getRutInscritos(this.getId());
    }

    /**
     * Method description
     *
     * @return
     */
    public boolean notasFinales() {
        return !evaluacionList.isEmpty()
                && evaluacionList.stream().noneMatch(evaluacion -> "SN".equals(evaluacion.getEvalStatus()));
    }

    /**
     * Method description
     *
     * @return
     */
    public boolean getPuedeEmitir() {
        boolean retValue = false;

        if (notasFinales()
                && !ContextUtil.getDAO().getActaCalificacionRepository(ActionUtil.getDBUser()).puedeEmitir(this).isEmpty()) {
            retValue = true;
        }

        return retValue;
    }

    /**
     * Method description
     *
     * @return
     */
    public boolean getPuedePonerNotasParciales() {
        return "SI".equals(ContextUtil.getDAO().getScalarRepository(ActionUtil.getDBUser()).getPuedePonerNotas(id.getCurAsign(), id.getCurElect(), id.getCurCoord(), id.getCurSecc(), id.getCurAgno(), id.getCurSem()));
    }

    /**
     *
     * @param modo
     */
    public void setModoEvaluacion(String modo) {
        ContextUtil.getDAO().getCursoRepository(ActionUtil.getDBUser()).setModoEvaluacion(id, modo);
        this.curModalEval = modo;
    }

    public CursoEspejo getEspejo() {
        return espejo;
    }

    public void setEspejo(CursoEspejo espejo) {
        this.espejo = espejo;
    }

    public String getCurEnableProf() {
        return curEnableProf;
    }

    public void setCurEnableProf(String curEnableProf) {
        this.curEnableProf = curEnableProf;
    }

    public String getCurEnableAyu() {
        return curEnableAyu;
    }

    public void setCurEnableAyu(String curEnableAyu) {
        this.curEnableAyu = curEnableAyu;
    }

    public String getCurEnableLab() {
        return curEnableLab;
    }

    public void setCurEnableLab(String curEnableLab) {
        this.curEnableLab = curEnableLab;
    }
}
