/*
 * @(#)CursoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CursoId generated by hbm2java
 */
public class CursoId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer curAgno;
    private Integer curAsign;
    private String curCoord;
    private String curElect;
    private Integer curSecc;
    private Integer curSem;
    private String curComp;

    /**
     *
     */
    public CursoId() {
    }


    /**
     * Method description
     *
     * @return
     */
    public Integer getCurAsign() {
        return this.curAsign;
    }

    /**
     * Method description
     *
     * @param curAsign
     */
    public void setCurAsign(Integer curAsign) {
        this.curAsign = curAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCurElect() {
        return this.curElect;
    }

    /**
     * Method description
     *
     * @param curElect
     */
    public void setCurElect(String curElect) {
        this.curElect = curElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCurCoord() {
        return this.curCoord;
    }

    /**
     * Method description
     *
     * @param curCoord
     */
    public void setCurCoord(String curCoord) {
        this.curCoord = curCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCurSecc() {
        return this.curSecc;
    }

    /**
     * Method description
     *
     * @param curSecc
     */
    public void setCurSecc(Integer curSecc) {
        this.curSecc = curSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCurAgno() {
        return this.curAgno;
    }

    /**
     * Method description
     *
     * @param curAgno
     */
    public void setCurAgno(Integer curAgno) {
        this.curAgno = curAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCurSem() {
        return this.curSem;
    }

    /**
     * Method description
     *
     * @param curSem
     */
    public void setCurSem(Integer curSem) {
        this.curSem = curSem;
    }

    /**
     *
     * @param sep
     * @return
     */
    public String getCodigo(String sep) {
        return getCodigoCorto(sep) + sep + this.getCurAgno() + sep + this.getCurSem();
    }

    /**
     *
     * @param sep
     * @return
     */
    public String getCodigoCorto(String sep) {
        return this.getCurAsign() + sep + this.getCurElect() + sep + this.getCurCoord() + sep + this.getCurSecc();
    } 

    public String getCurComp() {
        return curComp;
    }

    public void setCurComp(String curComp) {
        this.curComp = curComp;
    }    
}
