/*
 * @(#)CursoAyudanteId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * CursoAyudanteId generated by hbm2java
 */
public class CursoAyudanteId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer cayuAgno;
    private Integer cayuAsign;
    private String cayuCoord;
    private String cayuElect;
    private Integer cayuRut;
    private Integer cayuSecc;
    private Integer cayuSem;
    private String cayuComp;

    /**
     *
     */
    public CursoAyudanteId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCayuAsign() {
        return this.cayuAsign;
    }

    /**
     * Method description
     *
     * @param cayuAsign
     */
    public void setCayuAsign(Integer cayuAsign) {
        this.cayuAsign = cayuAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCayuElect() {
        return this.cayuElect;
    }

    /**
     * Method description
     *
     * @param cayuElect
     */
    public void setCayuElect(String cayuElect) {
        this.cayuElect = cayuElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getCayuCoord() {
        return this.cayuCoord;
    }

    /**
     * Method description
     *
     * @param cayuCoord
     */
    public void setCayuCoord(String cayuCoord) {
        this.cayuCoord = cayuCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCayuSecc() {
        return this.cayuSecc;
    }

    /**
     * Method description
     *
     * @param cayuSecc
     */
    public void setCayuSecc(Integer cayuSecc) {
        this.cayuSecc = cayuSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCayuAgno() {
        return this.cayuAgno;
    }

    /**
     * Method description
     *
     * @param cayuAgno
     */
    public void setCayuAgno(Integer cayuAgno) {
        this.cayuAgno = cayuAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCayuSem() {
        return this.cayuSem;
    }

    /**
     * Method description
     *
     * @param cayuSem
     */
    public void setCayuSem(Integer cayuSem) {
        this.cayuSem = cayuSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getCayuRut() {
        return this.cayuRut;
    }

    /**
     * Method description
     *
     * @param cayuRut
     */
    public void setCayuRut(Integer cayuRut) {
        this.cayuRut = cayuRut;
    } 

    public String getCayuComp() {
        return cayuComp;
    }

    public void setCayuComp(String cayuComp) {
        this.cayuComp = cayuComp;
    }
}
