/*
 * @(#)Derecho.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Derecho generated by hbm2java
 */
public class Derecho implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Asignatura asignatura;
    private Integer derCred;
    private Integer derMencion;
    private Integer derNiv;
    private Integer derTipo;
    private DerechoId id;
    private Malla malla;
    private String derForce;
    private Integer derAgno;
    private Integer derSem;

    /**
     *
     */
    public Derecho() {
    }

    /**
     * Method description
     *
     * @return
     */
    public DerechoId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(DerechoId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Malla getMalla() {
        return this.malla;
    }

    /**
     * Method description
     *
     * @param malla
     */
    public void setMalla(Malla malla) {
        this.malla = malla;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getDerCred() {
        return this.derCred;
    }

    /**
     * Method description
     *
     * @param derCred
     */
    public void setDerCred(Integer derCred) {
        this.derCred = derCred;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getDerNiv() {
        return this.derNiv;
    }

    /**
     * Method description
     *
     * @param derNiv
     */
    public void setDerNiv(Integer derNiv) {
        this.derNiv = derNiv;
    }

    /**
     * Method description
     *
     * @return
     */
    public Asignatura getAsignatura() {
        return asignatura;
    }

    /**
     * Method description
     *
     * @param asignatura
     */
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getDerMencion() {
        return derMencion;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getDerTipo() {
        return derTipo;
    }

    /**
     * Method description
     *
     *
     * @param derTipo
     */
    public void setDerTipo(Integer derTipo) {
        this.derTipo = derTipo;
    }

    /**
     * Method description
     *
     * @param derMencion
     */
    public void setDerMencion(Integer derMencion) {
        this.derMencion = derMencion;
    }

    public String getDerForce() {
        return derForce;
    }

    public void setDerForce(String derForce) {
        this.derForce = derForce;
    }

    public Integer getDerAgno() {
        return derAgno;
    }

    public void setDerAgno(Integer derAgno) {
        this.derAgno = derAgno;
    }

    public Integer getDerSem() {
        return derSem;
    }

    public void setDerSem(Integer derSem) {
        this.derSem = derSem;
    }
}
