/*
 * @(#)DerechoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * DerechoId generated by hbm2java
 */
public class DerechoId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer derAgnoIng;
    private Integer derAsign;
    private Integer derCodCar;
    private Integer derRut;
    private Integer derSemIng;

    /**
     *
     */
    public DerechoId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getDerRut() {
        return this.derRut;
    }

    /**
     * Method description
     *
     * @param derRut
     */
    public void setDerRut(Integer derRut) {
        this.derRut = derRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getDerCodCar() {
        return this.derCodCar;
    }

    /**
     * Method description
     *
     * @param derCodCar
     */
    public void setDerCodCar(Integer derCodCar) {
        this.derCodCar = derCodCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getDerAgnoIng() {
        return this.derAgnoIng;
    }

    /**
     * Method description
     *
     * @param derAgnoIng
     */
    public void setDerAgnoIng(Integer derAgnoIng) {
        this.derAgnoIng = derAgnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getDerSemIng() {
        return this.derSemIng;
    }

    /**
     * Method description
     *
     * @param derSemIng
     */
    public void setDerSemIng(Integer derSemIng) {
        this.derSemIng = derSemIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getDerAsign() {
        return this.derAsign;
    }

    /**
     * Method description
     *
     * @param derAsign
     */
    public void setDerAsign(Integer derAsign) {
        this.derAsign = derAsign;
    }
}
