/*
 * @(#)ElectivoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ElectivoId generated by hbm2java
 */
public class ElectivoId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer eleAgno;
    private Integer eleAsign;
    private String eleElect;
    private Integer eleSem;

    /**
     *
     */
    public ElectivoId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEleAsign() {
        return this.eleAsign;
    }

    /**
     * Method description
     *
     * @param eleAsign
     */
    public void setEleAsign(Integer eleAsign) {
        this.eleAsign = eleAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getEleElect() {
        return this.eleElect;
    }

    /**
     * Method description
     *
     * @param eleElect
     */
    public void setEleElect(String eleElect) {
        this.eleElect = eleElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEleAgno() {
        return this.eleAgno;
    }

    /**
     * Method description
     *
     * @param eleAgno
     */
    public void setEleAgno(Integer eleAgno) {
        this.eleAgno = eleAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEleSem() {
        return this.eleSem;
    }

    /**
     * Method description
     *
     * @param eleSem
     */
    public void setEleSem(Integer eleSem) {
        this.eleSem = eleSem;
    }
}
