/*
 * @(#)Electivo.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Electivo generated by hbm2java
 */
public class Electivo implements Serializable {

    private static final long serialVersionUID = 1L;
    private Asignatura asignatura;
    private Area area;
    private String eleNom;
    private Integer minor;
    private ElectivoId id;
    private String eleTipo;

    /**
     *
     */
    public Electivo() {
    }

    /**
     * Method description
     *
     * @return
     */
    public ElectivoId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(ElectivoId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Asignatura getAsignatura() {
        return this.asignatura;
    }

    /**
     * Method description
     *
     * @param asignatura
     */
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getEleNom() {
        return this.eleNom;
    }

    /**
     * Method description
     *
     * @param eleNom
     */
    public void setEleNom(String eleNom) {
        this.eleNom = eleNom;
    }

    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public Integer getMinor() {
        return minor;
    }

    public void setMinor(Integer minor) {
        this.minor = minor;
    }
    
    public String getEleTipo() {
        return eleTipo;
    }

    public void setEleTipo(String eleTipo) {
        this.eleTipo = eleTipo;
    }
}
