/*
 * @(#)EmisionNomina.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 13-09-2010 05:58:20 PM by Hibernate Tools 3.2.1.GA

/**
 * EmisionNomina generated by hbm2java
 */
public class EmisionNomina implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer emiAgno;
    private Integer emiCorrel;
    private Date emiFecha;
    private String emiReali;
    private Integer emiSem;
    private Integer emiTipo;

    /**
     *
     */
    public EmisionNomina() {
    }

    /**
     *
     * @param emiCorrel
     */
    public EmisionNomina(int emiCorrel) {
        this.emiCorrel = emiCorrel;
    }

    /**
     * Method description
     *
     * @return
     */
    public int getEmiCorrel() {
        return this.emiCorrel;
    }

    /**
     * Method description
     *
     * @param emiCorrel
     */
    public void setEmiCorrel(int emiCorrel) {
        this.emiCorrel = emiCorrel;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEmiAgno() {
        return this.emiAgno;
    }

    /**
     * Method description
     *
     * @param emiAgno
     */
    public void setEmiAgno(Integer emiAgno) {
        this.emiAgno = emiAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEmiSem() {
        return this.emiSem;
    }

    /**
     * Method description
     *
     * @param emiSem
     */
    public void setEmiSem(Integer emiSem) {
        this.emiSem = emiSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEmiTipo() {
        return this.emiTipo;
    }

    /**
     * Method description
     *
     * @param emiTipo
     */
    public void setEmiTipo(Integer emiTipo) {
        this.emiTipo = emiTipo;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getEmiFecha() {
        return getDateGetterSetter(emiFecha);
    }

    /**
     * Method description
     *
     * @param emiFecha
     */
    public void setEmiFecha(Date emiFecha) {
        this.emiFecha = getDateGetterSetter(emiFecha);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getEmiReali() {
        return this.emiReali;
    }

    /**
     * Method description
     *
     * @param emiReali
     */
    public void setEmiReali(String emiReali) {
        this.emiReali = emiReali;
    }
}
