/*
 * @(#)Empleador.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 03-05-2011 07:30:48 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Empleador generated by hbm2java
 */
public class Empleador implements Serializable {

    private static final long serialVersionUID = 1L;
    private ActividadEconomica actividadEconomica;
    private String empDv;
    private String empNombre;
    private Integer empRut;
    private String empTipoEmpleador;

    /**
     *
     */
    public Empleador() {
    }

        /**
     *
     * @return
     */
    public ActividadEconomica getActividadEconomica() {
        return this.actividadEconomica;
    }

    /**
     *
     * @param actividadEconomica
     */
    public void setActividadEconomica(ActividadEconomica actividadEconomica) {
        this.actividadEconomica = actividadEconomica;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getEmpDv() {
        return empDv;
    }

    /**
     * Method description
     *
     * @param empDv
     */
    public void setEmpDv(String empDv) {
        this.empDv = empDv;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getEmpNombre() {
        return empNombre;
    }

    /**
     * Method description
     *
     * @param empNombre
     */
    public void setEmpNombre(String empNombre) {
        this.empNombre = empNombre;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEmpRut() {
        return empRut;
    }

    /**
     * Method description
     *
     * @param empRut
     */
    public void setEmpRut(Integer empRut) {
        this.empRut = empRut;
    }

        /**
     *
     * @return
     */
    public String getEmpTipoEmpleador() {
        return this.empTipoEmpleador;
    }

    /**
     *
     * @param empTipoEmpleador
     */
    public void setEmpTipoEmpleador(String empTipoEmpleador) {
        this.empTipoEmpleador = empTipoEmpleador;
    }
}
