/*
 * @(#)EncuestaAyudanteCarreraId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 12-05-2011 10:29:31 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * EncuestaCarreraId generated by hbm2java
 */
public class EncuestaAyudanteCarreraId implements Serializable {

    private static final long serialVersionUID = 1L;
    private int eacCodCar;
    private int eacCodMen;
    private int eacEnc;

    /**
     *
     */
    public EncuestaAyudanteCarreraId() {
    }

    /**
     *
     * @return
     */
    public int getEacCodCar() {
        return eacCodCar;
    }

    /**
     *
     * @param eacCodCar
     */
    public void setEacCodCar(int eacCodCar) {
        this.eacCodCar = eacCodCar;
    }

    /**
     *
     * @return
     */
    public int getEacCodMen() {
        return eacCodMen;
    }

    /**
     *
     * @param eacCodMen
     */
    public void setEacCodMen(int eacCodMen) {
        this.eacCodMen = eacCodMen;
    }

    /**
     *
     * @return
     */
    public int getEacEnc() {
        return eacEnc;
    }

    /**
     *
     * @param eacEnc
     */
    public void setEacEnc(int eacEnc) {
        this.eacEnc = eacEnc;
    }
}
