/*
 * @(#)EncuestaAyudanteCarrera.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 12-05-2011 10:29:31 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * EncuestaCarrera generated by hbm2java
 */
public class EncuestaAyudanteCarrera implements Serializable {

    private static final long serialVersionUID = 1L;
    private EncuestaAyudante encuestaAyudante;
    private EncuestaAyudanteCarreraId id;
    private Mencion mencion;

    /**
     *
     */
    public EncuestaAyudanteCarrera() {
    }

    /**
     *
     * @return
     */
    public EncuestaAyudante getEncuestaAyudante() {
        return encuestaAyudante;
    }

    /**
     *
     * @param encuestaAyudante
     */
    public void setEncuestaAyudante(EncuestaAyudante encuestaAyudante) {
        this.encuestaAyudante = encuestaAyudante;
    }

    /**
     *
     * @return
     */
    public EncuestaAyudanteCarreraId getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(EncuestaAyudanteCarreraId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Mencion getMencion() {
        return mencion;
    }

    /**
     *
     * @param mencion
     */
    public void setMencion(Mencion mencion) {
        this.mencion = mencion;
    }

}
