/*
 * @(#)EncuestaDocente.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * EncuestaDocente generated by hbm2java
 */
public class EncuestaDocente implements Serializable {

    private static final long serialVersionUID = 1L;
    private Set<EncuestaDocenteCarrera> encuestaCarreras = new HashSet<>(0);
    private Integer edoAgno;
    private Integer edoCiclo;
    private Integer edoNro;
    private Integer edoNroPreg;
    private String edoTipo;

    /**
     *
     */
    public EncuestaDocente() {
    }

    /**
     *
     * @return
     */
    public Integer getEdoAgno() {
        return edoAgno;
    }

    /**
     *
     * @param edoAgno
     */
    public void setEdoAgno(Integer edoAgno) {
        this.edoAgno = edoAgno;
    }

    /**
     *
     * @return
     */
    public Integer getEdoCiclo() {
        return edoCiclo;
    }

    /**
     *
     * @param edoCiclo
     */
    public void setEdoCiclo(Integer edoCiclo) {
        this.edoCiclo = edoCiclo;
    }

    /**
     *
     * @return
     */
    public Integer getEdoNro() {
        return edoNro;
    }

    /**
     *
     * @param edoNro
     */
    public void setEdoNro(Integer edoNro) {
        this.edoNro = edoNro;
    }

    /**
     *
     * @return
     */
    public Integer getEdoNroPreg() {
        return edoNroPreg;
    }

    /**
     *
     * @param edoNroPreg
     */
    public void setEdoNroPreg(Integer edoNroPreg) {
        this.edoNroPreg = edoNroPreg;
    }

    /**
     *
     * @return
     */
    public String getEdoTipo() {
        return edoTipo;
    }

    /**
     *
     * @param edoTipo
     */
    public void setEdoTipo(String edoTipo) {
        this.edoTipo = edoTipo;
    }

    /**
     *
     * @return
     */
    public Set<EncuestaDocenteCarrera> getEncuestaCarreras() {
        return encuestaCarreras;
    }

    /**
     *
     * @param encuestaCarreras
     */
    public void setEncuestaCarreras(Set<EncuestaDocenteCarrera> encuestaCarreras) {
        this.encuestaCarreras = encuestaCarreras;
    }
}
