/*
 * @(#)EncuestaAyudante.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * EncuestaDocente generated by hbm2java
 */
public class EncuestaAyudante implements Serializable {

    private static final long serialVersionUID = 1L;
    private Set<EncuestaAyudanteCarrera> encuestaCarreras = new HashSet<>(0);
    private Integer enaAgno;
    private Integer enaCiclo;
    private Integer enaNro;
    private Integer enaNroPreg;
    private String enaTipo;

    /**
     *
     */
    public EncuestaAyudante() {
    }

    /**
     *
     * @return
     */
    public Integer getEnaAgno() {
        return enaAgno;
    }

    /**
     *
     * @param enaAgno
     */
    public void setEnaAgno(Integer enaAgno) {
        this.enaAgno = enaAgno;
    }

    /**
     *
     * @return
     */
    public Integer getEnaCiclo() {
        return enaCiclo;
    }

    /**
     *
     * @param enaCiclo
     */
    public void setEnaCiclo(Integer enaCiclo) {
        this.enaCiclo = enaCiclo;
    }

    /**
     *
     * @return
     */
    public Integer getEnaNro() {
        return enaNro;
    }

    /**
     *
     * @param enaNro
     */
    public void setEnaNro(Integer enaNro) {
        this.enaNro = enaNro;
    }

    /**
     *
     * @return
     */
    public Integer getEnaNroPreg() {
        return enaNroPreg;
    }

    /**
     *
     * @param enaNroPreg
     */
    public void setEnaNroPreg(Integer enaNroPreg) {
        this.enaNroPreg = enaNroPreg;
    }

    /**
     *
     * @return
     */
    public String getEnaTipo() {
        return enaTipo;
    }

    /**
     *
     * @param enaTipo
     */
    public void setEnaTipo(String enaTipo) {
        this.enaTipo = enaTipo;
    }        

    /**
     *
     * @return
     */
    public Set<EncuestaAyudanteCarrera> getEncuestaCarreras() {
        return encuestaCarreras;
    }

    /**
     *
     * @param encuestaCarreras
     */
    public void setEncuestaCarreras(Set<EncuestaAyudanteCarrera> encuestaCarreras) {
        this.encuestaCarreras = encuestaCarreras;
    }
}
