/*
 * @(#)EncuestaDocenteCarrera.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 12-05-2011 10:29:31 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * EncuestaDocenteCarrera generated by hbm2java
 */
public class EncuestaDocenteCarrera implements Serializable {

    private static final long serialVersionUID = 1L;
    private EncuestaDocente encuestaDocente;
    private EncuestaDocenteCarreraId id;
    private Mencion mencion;

    /**
     *
     */
    public EncuestaDocenteCarrera() {
    }

    /**
     *
     * @return
     */
    public EncuestaDocente getEncuestaDocente() {
        return encuestaDocente;
    }

    /**
     *
     * @param encuestaDocente
     */
    public void setEncuestaDocente(EncuestaDocente encuestaDocente) {
        this.encuestaDocente = encuestaDocente;
    }

    /**
     * Method description
     *
     * @return
     */
    public EncuestaDocenteCarreraId getId() {
        return id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(EncuestaDocenteCarreraId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Mencion getMencion() {
        return mencion;
    }

    /**
     * Method description
     *
     * @param mencion
     */
    public void setMencion(Mencion mencion) {
        this.mencion = mencion;
    }
}
