/*
 * @(#)EncuestaDocenteCarreraId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 12-05-2011 10:29:31 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * EncuestaDocenteCarreraId generated by hbm2java
 */
public class EncuestaDocenteCarreraId implements Serializable {

    private static final long serialVersionUID = 1L;
    private int edcCodCar;
    private int edcCodMen;
    private int edcEnc;

    /**
     *
     */
    public EncuestaDocenteCarreraId() {
    }

    /**
     *
     * @return
     */
    public int getEdcCodCar() {
        return edcCodCar;
    }

    /**
     *
     * @param edcCodCar
     */
    public void setEdcCodCar(int edcCodCar) {
        this.edcCodCar = edcCodCar;
    }

    /**
     *
     * @return
     */
    public int getEdcCodMen() {
        return edcCodMen;
    }

    /**
     *
     * @param edcCodMen
     */
    public void setEdcCodMen(int edcCodMen) {
        this.edcCodMen = edcCodMen;
    }

    /**
     *
     * @return
     */
    public int getEdcEnc() {
        return edcEnc;
    }

    /**
     *
     * @param edcEnc
     */
    public void setEdcEnc(int edcEnc) {
        this.edcEnc = edcEnc;
    }
}
