/*
 * @(#)EquivalenciaId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * EquivalenciaId generated by hbm2java
 */
public class EquivalenciaId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer equAgnoIng;
    private Integer equAgnoOri;
    private Integer equAsign;
    private Integer equAsignOri;
    private Integer equCodCar;
    private String equElect;
    private String equElectOri;
    private Integer equRut;
    private Integer equSemIng;
    private Integer equSemOri;

    private Integer equAgno;
    private Integer equSem;

    /**
     *
     */
    public EquivalenciaId() {
    }

    public Integer getEquAgnoIng() {
        return equAgnoIng;
    }

    public void setEquAgnoIng(Integer equAgnoIng) {
        this.equAgnoIng = equAgnoIng;
    }

    public Integer getEquAgnoOri() {
        return equAgnoOri;
    }

    public void setEquAgnoOri(Integer equAgnoOri) {
        this.equAgnoOri = equAgnoOri;
    }

    public Integer getEquAsign() {
        return equAsign;
    }

    public void setEquAsign(Integer equAsign) {
        this.equAsign = equAsign;
    }

    public Integer getEquAsignOri() {
        return equAsignOri;
    }

    public void setEquAsignOri(Integer equAsignOri) {
        this.equAsignOri = equAsignOri;
    }

    public Integer getEquCodCar() {
        return equCodCar;
    }

    public void setEquCodCar(Integer equCodCar) {
        this.equCodCar = equCodCar;
    }

    public String getEquElect() {
        return equElect;
    }

    public void setEquElect(String equElect) {
        this.equElect = equElect;
    }

    public String getEquElectOri() {
        return equElectOri;
    }

    public void setEquElectOri(String equElectOri) {
        this.equElectOri = equElectOri;
    }

    public Integer getEquRut() {
        return equRut;
    }

    public void setEquRut(Integer equRut) {
        this.equRut = equRut;
    }

    public Integer getEquSemIng() {
        return equSemIng;
    }

    public void setEquSemIng(Integer equSemIng) {
        this.equSemIng = equSemIng;
    }

    public Integer getEquSemOri() {
        return equSemOri;
    }

    public void setEquSemOri(Integer equSemOri) {
        this.equSemOri = equSemOri;
    }

    public Integer getEquAgno() {
        return equAgno;
    }

    public void setEquAgno(Integer equAgno) {
        this.equAgno = equAgno;
    }

    public Integer getEquSem() {
        return equSem;
    }

    public void setEquSem(Integer equSem) {
        this.equSem = equSem;
    }


}
