/*
 * @(#)EquivNotaMagister.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * EquivNotaMagister generated by hbm2java
 */
public class EquivNotaMagister implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer eqnmCeroCien;
    private Character eqnmConcepto;
    private BigDecimal eqnmUnoSiete;

    /**
     *
     */
    public EquivNotaMagister() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEqnmCeroCien() {
        return this.eqnmCeroCien;
    }

    /**
     * Method description
     *
     * @param eqnmCeroCien
     */
    public void setEqnmCeroCien(Integer eqnmCeroCien) {
        this.eqnmCeroCien = eqnmCeroCien;
    }

    /**
     * Method description
     *
     * @return
     */
    public BigDecimal getEqnmUnoSiete() {
        return this.eqnmUnoSiete;
    }

    /**
     * Method description
     *
     * @param eqnmUnoSiete
     */
    public void setEqnmUnoSiete(BigDecimal eqnmUnoSiete) {
        this.eqnmUnoSiete = eqnmUnoSiete;
    }

    /**
     * Method description
     *
     * @return
     */
    public Character getEqnmConcepto() {
        return this.eqnmConcepto;
    }

    /**
     * Method description
     *
     * @param eqnmConcepto
     */
    public void setEqnmConcepto(Character eqnmConcepto) {
        this.eqnmConcepto = eqnmConcepto;
    }
}
