/*
 * @(#)Equivalencia.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Equivalencia generated by hbm2java
 */
public class Equivalencia implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private String equCoordOri;
    private Integer equDoctoOri;
    private String equProcOri;
    private Integer equSeccOri;
    private EquivalenciaId id;

    /**
     *
     */
    public Equivalencia() {
    }

    /**
     * Method description
     *
     * @return
     */
    public EquivalenciaId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(EquivalenciaId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getEquCoordOri() {
        return this.equCoordOri;
    }

    /**
     * Method description
     *
     * @param equCoordOri
     */
    public void setEquCoordOri(String equCoordOri) {
        this.equCoordOri = equCoordOri;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEquSeccOri() {
        return this.equSeccOri;
    }

    /**
     * Method description
     *
     * @param equSeccOri
     */
    public void setEquSeccOri(Integer equSeccOri) {
        this.equSeccOri = equSeccOri;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getEquProcOri() {
        return equProcOri;
    }

    /**
     * Method description
     *
     *
     * @param equProcOri
     */
    public void setEquProcOri(String equProcOri) {
        this.equProcOri = equProcOri;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getEquDoctoOri() {
        return equDoctoOri;
    }

    /**
     * Method description
     *
     *
     * @param equDoctoOri
     */
    public void setEquDoctoOri(Integer equDoctoOri) {
        this.equDoctoOri = equDoctoOri;
    }
}
