/*
 * @(#)EquivNota.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * EquivNota generated by hbm2java
 */
public class EquivNota implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer eqnCeroCien;
    private BigDecimal eqnUnoSiete;

    /**
     *
     */
    public EquivNota() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getEqnCeroCien() {
        return this.eqnCeroCien;
    }

    /**
     * Method description
     *
     * @param eqnCeroCien
     */
    public void setEqnCeroCien(Integer eqnCeroCien) {
        this.eqnCeroCien = eqnCeroCien;
    }

    /**
     * Method description
     *
     * @return
     */
    public BigDecimal getEqnUnoSiete() {
        return this.eqnUnoSiete;
    }

    /**
     * Method description
     *
     * @param eqnUnoSiete
     */
    public void setEqnUnoSiete(BigDecimal eqnUnoSiete) {
        this.eqnUnoSiete = eqnUnoSiete;
    }
}
