/*
 * @(#)EstadoCivil.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Comuna generated by hbm2java
 */
public class EstadoCivil implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer ecivCod;
    private String ecivDes;

    /**
     *
     */
    public EstadoCivil() {
    }

    /**
     *
     * @return
     */
    public Integer getEcivCod() {
        return ecivCod;
    }

    /**
     *
     * @param ecivCod
     */
    public void setEcivCod(Integer ecivCod) {
        this.ecivCod = ecivCod;
    }

    /**
     *
     * @return
     */
    public String getEcivDes() {
        return ecivDes;
    }

    /**
     *
     * @param ecivDes
     */
    public void setEcivDes(String ecivDes) {
        this.ecivDes = ecivDes;
    }

}
