/*
 * @(#)AluCarId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * AluCarId generated by hbm2java
 */
public class ExamenComision implements Serializable {

    private static final long serialVersionUID = 1L;
    private ExamenComisionId id;
    private Profesor profesor;
    private BigDecimal exacNotaTrabajo;
    private BigDecimal exacNotaExamen;
    private Examen examen;
    
    

    /**
     *
     */
    public ExamenComision() {
    }

    public ExamenComisionId getId() {
        return id;
    }

    public void setId(ExamenComisionId id) {
        this.id = id;
    }

    public Profesor getProfesor() {
        return profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    public BigDecimal getExacNotaTrabajo() {
        return exacNotaTrabajo;
    }

    public void setExacNotaTrabajo(BigDecimal exacNotaTrabajo) {
        this.exacNotaTrabajo = exacNotaTrabajo;
    }

    public BigDecimal getExacNotaExamen() {
        return exacNotaExamen;
    }

    public void setExacNotaExamen(BigDecimal exacNotaExamen) {
        this.exacNotaExamen = exacNotaExamen;
    }

    public Examen getExamen() {
        return examen;
    }

    public void setExamen(Examen examen) {
        this.examen = examen;
    }    
}
