/*
 * @(#)AluCarId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * AluCarId generated by hbm2java
 */
public class ExamenComisionId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer exacFolioExa;
    private Integer exacRutProf;   

    /**
     *
     */
    public ExamenComisionId() {
    }

    public Integer getExacFolioExa() {
        return exacFolioExa;
    }

    public void setExacFolioExa(Integer exacFolioExa) {
        this.exacFolioExa = exacFolioExa;
    }

    public Integer getExacRutProf() {
        return exacRutProf;
    }

    public void setExacRutProf(Integer exacRutProf) {
        this.exacRutProf = exacRutProf;
    }    
}
