/*
 * @(#)AluCarId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.util.Date;

/**
 * AluCarId generated by hbm2java
 */
public class Examen implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Integer exaAgno;
    private Integer exaSem;
    private Integer exaTrabajo;
    private Date exaFechaTrabajo;
    private Date exaFechaExamen;
    private Integer exaPorcTrabajo;
    private Integer exaPorcExamen;
    private Integer exaFolio;    

    /**
     *
     */
    public Examen() {
    }

    public AluCar getAluCar() {
        return aluCar;
    }

    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }
   
    public Integer getExaAgno() {
        return exaAgno;
    }

    public void setExaAgno(Integer exaAgno) {
        this.exaAgno = exaAgno;
    }

    public Integer getExaSem() {
        return exaSem;
    }

    public void setExaSem(Integer exaSem) {
        this.exaSem = exaSem;
    }

    public Integer getExaTrabajo() {
        return exaTrabajo;
    }

    public void setExaTrabajo(Integer exaTrabajo) {
        this.exaTrabajo = exaTrabajo;
    }

    public Date getExaFechaTrabajo() {
        return exaFechaTrabajo;
    }

    public void setExaFechaTrabajo(Date exaFechaTrabajo) {
        this.exaFechaTrabajo = exaFechaTrabajo;
    }

    public Date getExaFechaExamen() {
        return exaFechaExamen;
    }

    public void setExaFechaExamen(Date exaFechaExamen) {
        this.exaFechaExamen = exaFechaExamen;
    }

    public Integer getExaPorcTrabajo() {
        return exaPorcTrabajo;
    }

    public void setExaPorcTrabajo(Integer exaPorcTrabajo) {
        this.exaPorcTrabajo = exaPorcTrabajo;
    }

    public Integer getExaPorcExamen() {
        return exaPorcExamen;
    }

    public void setExaPorcExamen(Integer exaPorcExamen) {
        this.exaPorcExamen = exaPorcExamen;
    }

    public Integer getExaFolio() {
        return exaFolio;
    }

    public void setExaFolio(Integer exaFolio) {
        this.exaFolio = exaFolio;
    }    
}
