/*
 * @(#)ExpedienteLogroId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 12-08-2013 03:30:52 PM by Hibernate Tools 3.2.1.GA
/**
 * ExpedienteLogroId generated by hbm2java
 */
public class ExpedienteLogroId implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private int explAgnoIng;
    private int explCodCar;
    private int explRut;
    private int explSemIng;
    private int explCorrel;

    /**
     *
     */
    public ExpedienteLogroId() {
    }

    /**
     *
     * @param explRut
     * @param explCodCar
     * @param explAgnoIng
     * @param explSemIng
     * @param explCorrel
     */
    public ExpedienteLogroId(int explRut, int explCodCar, int explAgnoIng, int explSemIng, int explCorrel) {
        this.explRut = explRut;
        this.explCodCar = explCodCar;
        this.explAgnoIng = explAgnoIng;
        this.explSemIng = explSemIng;
        this.explCorrel = explCorrel;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public int getExplRut() {
        return this.explRut;
    }

    /**
     * Method description
     *
     *
     * @param explRut
     */
    public void setExplRut(int explRut) {
        this.explRut = explRut;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public int getExplCodCar() {
        return this.explCodCar;
    }

    /**
     * Method description
     *
     *
     * @param explCodCar
     */
    public void setExplCodCar(int explCodCar) {
        this.explCodCar = explCodCar;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public int getExplAgnoIng() {
        return this.explAgnoIng;
    }

    /**
     * Method description
     *
     *
     * @param explAgnoIng
     */
    public void setExplAgnoIng(int explAgnoIng) {
        this.explAgnoIng = explAgnoIng;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public int getExplSemIng() {
        return this.explSemIng;
    }

    /**
     * Method description
     *
     *
     * @param explSemIng
     */
    public void setExplSemIng(int explSemIng) {
        this.explSemIng = explSemIng;
    }

    public int getExplCorrel() {
        return explCorrel;
    }

    public void setExplCorrel(int explCorrel) {
        this.explCorrel = explCorrel;
    }
}
