/*
 * @(#)ExpedienteLogro.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.util.Date;

//Generated 12-08-2013 03:30:52 PM by Hibernate Tools 3.2.1.GA
/**
 * ExpedienteLogro generated by hbm2java
 */
public class ExpedienteLogro implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private AluCar aluCar;
    private ExpedienteLogroId id;
    private ExpedienteNomina nomina;
    private PlanLogro planLogro;

    private Integer explAgnoLogroAcad;
    private Integer explSemLogroAcad;
    private Date explFecLogroAcad;
    private Integer explAgnoLogroAdm;
    private Integer explSemLogroAdm;
    private Date explFecLogroAdm;

    private Integer explNumResol;
    private Date explFecResol;
    private Integer explNumExp;
    private Date explFecExp;
    private Integer explNumOrd;
    private Date explFecOrd;
    private String explCodPago;
    private String explDocPago;
    private String explGenero;
    private String explRol;
    private String explEstado;
    private Integer explSol;

    /**
     *
     */
    public ExpedienteLogro() {
    }

    /**
     *
     * @param id
     * @param aluCar
     */
    public ExpedienteLogro(ExpedienteLogroId id, AluCar aluCar) {
        this.id = id;
        this.aluCar = aluCar;
    }

    public AluCar getAluCar() {
        return aluCar;
    }

    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    public ExpedienteLogroId getId() {
        return id;
    }

    public void setId(ExpedienteLogroId id) {
        this.id = id;
    }

    public Integer getExplAgnoLogroAcad() {
        return explAgnoLogroAcad;
    }

    public void setExplAgnoLogroAcad(Integer explAgnoLogroAcad) {
        this.explAgnoLogroAcad = explAgnoLogroAcad;
    }

    public Integer getExplSemLogroAcad() {
        return explSemLogroAcad;
    }

    public void setExplSemLogroAcad(Integer explSemLogroAcad) {
        this.explSemLogroAcad = explSemLogroAcad;
    }

    public Date getExplFecLogroAcad() {
        return explFecLogroAcad;
    }

    public void setExplFecLogroAcad(Date explFecLogroAcad) {
        this.explFecLogroAcad = explFecLogroAcad;
    }

    public Integer getExplAgnoLogroAdm() {
        return explAgnoLogroAdm;
    }

    public void setExplAgnoLogroAdm(Integer explAgnoLogroAdm) {
        this.explAgnoLogroAdm = explAgnoLogroAdm;
    }

    public Integer getExplSemLogroAdm() {
        return explSemLogroAdm;
    }

    public void setExplSemLogroAdm(Integer explSemLogroAdm) {
        this.explSemLogroAdm = explSemLogroAdm;
    }

    public Date getExplFecLogroAdm() {
        return explFecLogroAdm;
    }

    public void setExplFecLogroAdm(Date explFecLogroAdm) {
        this.explFecLogroAdm = explFecLogroAdm;
    }

    public Integer getExplNumResol() {
        return explNumResol;
    }

    public void setExplNumResol(Integer explNumResol) {
        this.explNumResol = explNumResol;
    }

    public Date getExplFecResol() {
        return explFecResol;
    }

    public void setExplFecResol(Date explFecResol) {
        this.explFecResol = explFecResol;
    }

    public ExpedienteNomina getNomina() {
        return nomina;
    }

    public void setNomina(ExpedienteNomina nomina) {
        this.nomina = nomina;
    }

    public Integer getExplNumExp() {
        return explNumExp;
    }

    public void setExplNumExp(Integer explNumExp) {
        this.explNumExp = explNumExp;
    }

    public Date getExplFecExp() {
        return explFecExp;
    }

    public void setExplFecExp(Date explFecExp) {
        this.explFecExp = explFecExp;
    }

    public Integer getExplNumOrd() {
        return explNumOrd;
    }

    public void setExplNumOrd(Integer explNumOrd) {
        this.explNumOrd = explNumOrd;
    }

    public Date getExplFecOrd() {
        return explFecOrd;
    }

    public void setExplFecOrd(Date explFecOrd) {
        this.explFecOrd = explFecOrd;
    }

    public String getExplCodPago() {
        return explCodPago;
    }

    public void setExplCodPago(String explCodPago) {
        this.explCodPago = explCodPago;
    }

    public String getExplDocPago() {
        return explDocPago;
    }

    public void setExplDocPago(String explDocPago) {
        this.explDocPago = explDocPago;
    }

    public String getExplGenero() {
        return explGenero;
    }

    public void setExplGenero(String explGenero) {
        this.explGenero = explGenero;
    }

    public String getExplRol() {
        return explRol;
    }

    public void setExplRol(String explRol) {
        this.explRol = explRol;
    }

    public PlanLogro getPlanLogro() {
        return planLogro;
    }

    public void setPlanLogro(PlanLogro planLogro) {
        this.planLogro = planLogro;
    }

    public String getExplEstado() {
        return explEstado;
    }

    public void setExplEstado(String explEstado) {
        this.explEstado = explEstado;
    }

    public Integer getExplSol() {
        return explSol;
    }

    public void setExplSol(Integer explSol) {
        this.explSol = explSol;
    }
    
}
