package domain.model;
// Generated 14-08-2014 03:40:22 PM by Hibernate Tools 3.2.1.GA

/**
 * FichaEstudio generated by hbm2java
 */
public class FichaEstudio implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer festCorrel;
    private Alumno alumno;
    private Pais pais;
    private AreaEstudio areaEstudio;
    private InstitucionEducacional institucionEducacional;
    private Testudio testudio;
    private EstadoEstudio estadoEstudio;
    private String festOtraInstitucion;
    private String festNombreEstudio;
    private Integer festDesdeMes;
    private Integer festDesdeAgno;
    private Integer festHastaMes;
    private Integer festHastaAgno;

    /**
     *
     */
    public FichaEstudio() {
    }

    /**
     *
     * @param festCorrel
     */
    public FichaEstudio(Integer festCorrel) {
        this.festCorrel = festCorrel;
    }

    /**
     *
     * @param festCorrel
     * @param alumno
     * @param pais
     * @param areaEstudio
     * @param institucionEducacional
     * @param testudio
     * @param estadoEstudio
     * @param festOtraInstitucion
     * @param festNombreEstudio
     * @param festDesdeMes
     * @param festDesdeAgno
     * @param festHastaMes
     * @param festHastaAgno
     */
    public FichaEstudio(Integer festCorrel, Alumno alumno, Pais pais, AreaEstudio areaEstudio, InstitucionEducacional institucionEducacional, Testudio testudio, EstadoEstudio estadoEstudio, String festOtraInstitucion, String festNombreEstudio, Integer festDesdeMes, Integer festDesdeAgno, Integer festHastaMes, Integer festHastaAgno) {
        this.festCorrel = festCorrel;
        this.alumno = alumno;
        this.pais = pais;
        this.areaEstudio = areaEstudio;
        this.institucionEducacional = institucionEducacional;
        this.testudio = testudio;
        this.estadoEstudio = estadoEstudio;
        this.festOtraInstitucion = festOtraInstitucion;
        this.festNombreEstudio = festNombreEstudio;
        this.festDesdeMes = festDesdeMes;
        this.festDesdeAgno = festDesdeAgno;
        this.festHastaMes = festHastaMes;
        this.festHastaAgno = festHastaAgno;
    }

    /**
     *
     * @return
     */
    public Integer getFestCorrel() {
        return this.festCorrel;
    }

    /**
     *
     * @param festCorrel
     */
    public void setFestCorrel(Integer festCorrel) {
        this.festCorrel = festCorrel;
    }

    /**
     *
     * @return
     */
    public Alumno getAlumno() {
        return this.alumno;
    }

    /**
     *
     * @param alumno
     */
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

    /**
     *
     * @return
     */
    public Pais getPais() {
        return this.pais;
    }

    /**
     *
     * @param pais
     */
    public void setPais(Pais pais) {
        this.pais = pais;
    }

    /**
     *
     * @return
     */
    public AreaEstudio getAreaEstudio() {
        return this.areaEstudio;
    }

    /**
     *
     * @param areaEstudio
     */
    public void setAreaEstudio(AreaEstudio areaEstudio) {
        this.areaEstudio = areaEstudio;
    }

    /**
     *
     * @return
     */
    public InstitucionEducacional getInstitucionEducacional() {
        return this.institucionEducacional;
    }

    /**
     *
     * @param institucionEducacional
     */
    public void setInstitucionEducacional(InstitucionEducacional institucionEducacional) {
        this.institucionEducacional = institucionEducacional;
    }

    /**
     *
     * @return
     */
    public Testudio getTestudio() {
        return this.testudio;
    }

    /**
     *
     * @param testudio
     */
    public void setTestudio(Testudio testudio) {
        this.testudio = testudio;
    }

    /**
     *
     * @return
     */
    public EstadoEstudio getEstadoEstudio() {
        return this.estadoEstudio;
    }

    /**
     *
     * @param estadoEstudio
     */
    public void setEstadoEstudio(EstadoEstudio estadoEstudio) {
        this.estadoEstudio = estadoEstudio;
    }

    /**
     *
     * @return
     */
    public String getFestOtraInstitucion() {
        return this.festOtraInstitucion;
    }

    /**
     *
     * @param festOtraInstitucion
     */
    public void setFestOtraInstitucion(String festOtraInstitucion) {
        this.festOtraInstitucion = festOtraInstitucion;
    }

    /**
     *
     * @return
     */
    public String getFestNombreEstudio() {
        return this.festNombreEstudio;
    }

    /**
     *
     * @param festNombreEstudio
     */
    public void setFestNombreEstudio(String festNombreEstudio) {
        this.festNombreEstudio = festNombreEstudio;
    }

    /**
     *
     * @return
     */
    public Integer getFestDesdeMes() {
        return this.festDesdeMes;
    }

    /**
     *
     * @param festDesdeMes
     */
    public void setFestDesdeMes(Integer festDesdeMes) {
        this.festDesdeMes = festDesdeMes;
    }

    /**
     *
     * @return
     */
    public Integer getFestDesdeAgno() {
        return this.festDesdeAgno;
    }

    /**
     *
     * @param festDesdeAgno
     */
    public void setFestDesdeAgno(Integer festDesdeAgno) {
        this.festDesdeAgno = festDesdeAgno;
    }

    /**
     *
     * @return
     */
    public Integer getFestHastaMes() {
        return this.festHastaMes;
    }

    /**
     *
     * @param festHastaMes
     */
    public void setFestHastaMes(Integer festHastaMes) {
        this.festHastaMes = festHastaMes;
    }

    /**
     *
     * @return
     */
    public Integer getFestHastaAgno() {
        return this.festHastaAgno;
    }

    /**
     *
     * @param festHastaAgno
     */
    public void setFestHastaAgno(Integer festHastaAgno) {
        this.festHastaAgno = festHastaAgno;
    }

}
