package domain.model;
// Generated 14-08-2014 03:40:22 PM by Hibernate Tools 3.2.1.GA

/**
 * FichaLaboral generated by hbm2java
 */
public class FichaLaboral implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer flabCorrelFicha;
    private AlumnoEmpleador alumnoEmpleador;
    private Region region;
    private Comuna comuna;
    private String flabOtroLugar;
    private AreaTrabajo areaTrabajo;
    private String flabCargo;
    private TipoTrabajo tipoTrabajo;
    private Integer flabSueldo;
    private Integer flabDesdeMes;
    private Integer flabDesdeAgno;
    private Integer flabHastaMes;
    private Integer flabHastaAgno;
    private String flabDescripcion;

    /**
     *
     */
    public FichaLaboral() {
    }

    /**
     *
     * @return
     */
    public Integer getFlabCorrelFicha() {
        return this.flabCorrelFicha;
    }

    /**
     *
     * @param flabCorrelFicha
     */
    public void setFlabCorrelFicha(Integer flabCorrelFicha) {
        this.flabCorrelFicha = flabCorrelFicha;
    }

    /**
     *
     * @return
     */

    public AlumnoEmpleador getAlumnoEmpleador() {
        return this.alumnoEmpleador;
    }

    /**
     *
     * @param alumnoEmpleador
     */

    public void setAlumnoEmpleador(AlumnoEmpleador alumnoEmpleador) {
        this.alumnoEmpleador = alumnoEmpleador;
    }

    /**
     *
     * @return
     */
    public Region getRegion() {
        return this.region;
    }

    /**
     *
     * @param region
     */
    public void setRegion(Region region) {
        this.region = region;
    }
    /**
     *
     * @return
     */
    public Comuna getComuna() {
        return this.comuna;
    }

    /**
     *
     * @param comuna
     */
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }

    /**
     *
     * @return
     */
    public String getFlabOtroLugar() {
        return this.flabOtroLugar;
    }

    /**
     *
     * @param flabOtroLugar
     */
    public void setFlabOtroLugar(String flabOtroLugar) {
        this.flabOtroLugar = flabOtroLugar;
    }

    /**
     *
     * @return
     */
    public AreaTrabajo getAreaTrabajo() {
        return this.areaTrabajo;
    }

    /**
     *
     * @param areaTrabajo
     */
    public void setAreaTrabajo(AreaTrabajo areaTrabajo) {
        this.areaTrabajo = areaTrabajo;
    }


    /**
     *
     * @return
     */
    public String getFlabCargo() {
        return this.flabCargo;
    }

    /**
     *
     * @param flabCargo
     */
    public void setFlabCargo(String flabCargo) {
        this.flabCargo = flabCargo;
    }

    /**
     *
     * @return
     */
    public TipoTrabajo getTipoTrabajo() {
        return this.tipoTrabajo;
    }

    /**
     *
     * @param tipoTrabajo
     */
    public void setTipoTrabajo(TipoTrabajo tipoTrabajo) {
        this.tipoTrabajo = tipoTrabajo;
    }

    /**
     *
     * @return
     */
    public Integer getFlabSueldo() {
        return this.flabSueldo;
    }

    /**
     *
     * @param flabSueldo
     */
    public void setFlabSueldo(Integer flabSueldo) {
        this.flabSueldo = flabSueldo;
    }

    /**
     *
     * @return
     */
    public Integer getFlabDesdeMes() {
        return this.flabDesdeMes;
    }

    /**
     *
     * @param flabDesdeMes
     */
    public void setFlabDesdeMes(Integer flabDesdeMes) {
        this.flabDesdeMes = flabDesdeMes;
    }

    /**
     *
     * @return
     */
    public Integer getFlabDesdeAgno() {
        return this.flabDesdeAgno;
    }

    /**
     *
     * @param flabDesdeAgno
     */
    public void setFlabDesdeAgno(Integer flabDesdeAgno) {
        this.flabDesdeAgno = flabDesdeAgno;
    }

    /**
     *
     * @return
     */
    public Integer getFlabHastaMes() {
        return this.flabHastaMes;
    }

    /**
     *
     * @param flabHastaMes
     */
    public void setFlabHastaMes(Integer flabHastaMes) {
        this.flabHastaMes = flabHastaMes;
    }

    /**
     *
     * @return
     */
    public Integer getFlabHastaAgno() {
        return this.flabHastaAgno;
    }

    /**
     *
     * @param flabHastaAgno
     */
    public void setFlabHastaAgno(Integer flabHastaAgno) {
        this.flabHastaAgno = flabHastaAgno;
    }

    /**
     *
     * @return
     */
    public String getFlabDescripcion() {
        return this.flabDescripcion;
    }

    /**
     *
     * @param flabDescripcion
     */
    public void setFlabDescripcion(String flabDescripcion) {
        this.flabDescripcion = flabDescripcion;
    }

}
