/*
 * @(#)HorarioId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * HorarioId generated by hbm2java
 */
public class HorarioId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer horAgno;
    private Integer horAsign;
    private String horCoord;
    private String horDia;
    private String horElect;
    private Integer horModulo;
    private Integer horSecc;
    private Integer horSem;
    private String horComp;

    /**
     *
     */
    public HorarioId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getHorAsign() {
        return this.horAsign;
    }

    /**
     * Method description
     *
     * @param horAsign
     */
    public void setHorAsign(Integer horAsign) {
        this.horAsign = horAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getHorElect() {
        return this.horElect;
    }

    /**
     * Method description
     *
     * @param horElect
     */
    public void setHorElect(String horElect) {
        this.horElect = horElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getHorCoord() {
        return this.horCoord;
    }

    /**
     * Method description
     *
     * @param horCoord
     */
    public void setHorCoord(String horCoord) {
        this.horCoord = horCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getHorSecc() {
        return this.horSecc;
    }

    /**
     * Method description
     *
     * @param horSecc
     */
    public void setHorSecc(Integer horSecc) {
        this.horSecc = horSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getHorAgno() {
        return this.horAgno;
    }

    /**
     * Method description
     *
     * @param horAgno
     */
    public void setHorAgno(Integer horAgno) {
        this.horAgno = horAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getHorSem() {
        return this.horSem;
    }

    /**
     * Method description
     *
     * @param horSem
     */
    public void setHorSem(Integer horSem) {
        this.horSem = horSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getHorDia() {
        return this.horDia;
    }

    /**
     * Method description
     *
     * @param horDia
     */
    public void setHorDia(String horDia) {
        this.horDia = horDia;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getHorModulo() {
        return this.horModulo;
    }

    /**
     * Method description
     *
     * @param horModulo
     */
    public void setHorModulo(Integer horModulo) {
        this.horModulo = horModulo;
    }

    public String getHorComp() {
        return horComp;
    }

    public void setHorComp(String horComp) {
        this.horComp = horComp;
    }
}
