/*
 * @(#)Horario.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.awt.*;
import java.io.Serializable;
import infrastructure.util.FormatUtil;
import infrastructure.util.common.CommonHorarioUtil;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
/**
 * Horario generated by hbm2java
 */
public class Horario implements Serializable {

    private static final long serialVersionUID = 1L;
    private Curso curso;
    private Character horTipoClase;
    private HorarioId id;
    private Dia dia;
    private Integer horCorrelativo;
    private Sala sala;
    private Profesor profesor;

    /**
     *
     */
    public Horario() {
    }

    /**
     * Method description
     *
     * @return
     */
    public HorarioId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(HorarioId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return this.curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     * Method description
     *
     * @return
     */
    public Sala getSala() {
        return this.sala;
    }

    /**
     * Method description
     *
     * @param sala
     */
    public void setSala(Sala sala) {
        this.sala = sala;
    }

    /**
     * Method description
     *
     * @return
     */
    public Character getHorTipoClase() {
        return this.horTipoClase;
    }

    /**
     * Method description
     *
     * @param horTipoClase
     */
    public void setHorTipoClase(Character horTipoClase) {
        this.horTipoClase = horTipoClase;
    }

    public Integer getHorCorrelativo() {
        return horCorrelativo;
    }

    public void setHorCorrelativo(Integer horCorrelativo) {
        this.horCorrelativo = horCorrelativo;
    }
    

    public Dia getDia() {
        return dia;
    }

    public void setDia(Dia dia) {
        this.dia = dia;
    }
    
    /**
     * BUSINESS LOGIC
     *
     * @return 
     */

    public String getColorHexPorAsignatura() {
        return CommonHorarioUtil.getColorHexPorAsignatura(id.getHorAsign());
    }

    
    public Color getColorHexPorAsignaturaPDF() {        
        return FormatUtil.getColor(getColorHexPorAsignatura());
    }

    public Profesor getProfesor() {
        return profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }        
}
