/*
 * @(#)Inscripcion.java
 *
 * Copyright (c) 2019 FAE-USACH
 */
package domain.model;

import domain.model.AluCar;
import domain.model.Curso;
import domain.model.InscripcionId;
import java.io.Serializable;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * Inscripcion generated by hbm2java
 */
public class InscripcionCursoView implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Curso curso;
    private InscripcionId id;
    private String insCoord;
    private Integer insSecc;

    /**
     *
     */
    public InscripcionCursoView() {
    }

    /**
     * Method description
     *
     * @return
     */
    public InscripcionId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(InscripcionId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return this.curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }


    /**
     * Method description
     *
     * @return
     */
    public String getInsCoord() {
        return insCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsSecc() {
        return insSecc;
    }

    /**
     * Method description
     *
     * @param insCoord
     */
    public void setInsCoord(String insCoord) {
        this.insCoord = insCoord;
    }

    /**
     * Method description
     *
     * @param insSecc
     */
    public void setInsSecc(Integer insSecc) {
        this.insSecc = insSecc;
    }
}
