/*
 * @(#)InscripcionAdicionalLogro.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 07-abr-2012 18:41:03 by Hibernate Tools 3.2.1.GA

/**
 * InscripcionAdicionalLogro generated by hbm2java
 */
public class InscripcionAdicionalLogro implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private InscripcionAdicionalLogroId id;
    private Date ialFecha;
    private Date ialFechaSys;
    private String ialGlosa;
    private String ialReali;
    private TrequisitoLogroAdicional trequisitoLogroAdicional;

    /**
     *
     */
    public InscripcionAdicionalLogro() {
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public InscripcionAdicionalLogroId getId() {
        return id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(InscripcionAdicionalLogroId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getIalFecha() {
        return getDateGetterSetter(ialFecha);
    }

    /**
     * Method description
     *
     * @param ialFecha
     */
    public void setIalFecha(Date ialFecha) {
        this.ialFecha = getDateGetterSetter(ialFecha);
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getIalFechaSys() {
        return getDateGetterSetter(ialFechaSys);
    }

    /**
     * Method description
     *
     * @param ialFechaSys
     */
    public void setIalFechaSys(Date ialFechaSys) {
        this.ialFechaSys = getDateGetterSetter(ialFechaSys);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getIalGlosa() {
        return ialGlosa;
    }

    /**
     * Method description
     *
     * @param ialGlosa
     */
    public void setIalGlosa(String ialGlosa) {
        this.ialGlosa = ialGlosa;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getIalReali() {
        return ialReali;
    }

    /**
     * Method description
     *
     * @param ialReali
     */
    public void setIalReali(String ialReali) {
        this.ialReali = ialReali;
    }

    public TrequisitoLogroAdicional getTrequisitoLogroAdicional() {
        return trequisitoLogroAdicional;
    }

    public void setTrequisitoLogroAdicional(TrequisitoLogroAdicional trequisitoLogroAdicional) {
        this.trequisitoLogroAdicional = trequisitoLogroAdicional;
    }
}
