/*
 * @(#)Inscripcion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Curso curso;
    private InscripcionId id;
    private String insCoord;
    private Date insFecha;
    private String insProceso;
    private Integer insSecc;
    private Integer insRutReali;
    private String insForce;

    /**
     *
     */
    public Inscripcion() {
    }

    /**
     * Method description
     *
     * @return
     */
    public InscripcionId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(InscripcionId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return this.curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getInsFecha() {
        return getDateGetterSetter(insFecha);
    }

    /**
     * Method description
     *
     * @param insFecha
     */
    public void setInsFecha(Date insFecha) {
        this.insFecha = getDateGetterSetter(insFecha);
    }

    public String getInsProceso() {
        return insProceso;
    }

    public void setInsProceso(String insProceso) {
        this.insProceso = insProceso;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getInsCoord() {
        return insCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsSecc() {
        return insSecc;
    }

    /**
     * Method description
     *
     * @param insCoord
     */
    public void setInsCoord(String insCoord) {
        this.insCoord = insCoord;
    }

    /**
     * Method description
     *
     * @param insSecc
     */
    public void setInsSecc(Integer insSecc) {
        this.insSecc = insSecc;
    }

    /**
     *
     * @return
     */
    public Integer getInsRutReali() {
        return insRutReali;
    }

    /**
     *
     * @param insRutReali
     */
    public void setInsRutReali(Integer insRutReali) {
        this.insRutReali = insRutReali;
    }

    public String getInsForce() {
        return insForce;
    }

    public void setInsForce(String insForce) {
        this.insForce = insForce;
    }

}
