/*
 * @(#)InscripcionId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * InscripcionId generated by hbm2java
 */
public class InscripcionId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer insAgno;
    private Integer insAgnoIng;
    private Integer insAsign;
    private Integer insCodCar;
    private String insElect;
    private Integer insRut;
    private Integer insSem;
    private Integer insSemIng;
    private String insComp;

    /**
     *
     */
    public InscripcionId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsRut() {
        return this.insRut;
    }

    /**
     * Method description
     *
     * @param insRut
     */
    public void setInsRut(Integer insRut) {
        this.insRut = insRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsCodCar() {
        return this.insCodCar;
    }

    /**
     * Method description
     *
     * @param insCodCar
     */
    public void setInsCodCar(Integer insCodCar) {
        this.insCodCar = insCodCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsAgnoIng() {
        return this.insAgnoIng;
    }

    /**
     * Method description
     *
     * @param insAgnoIng
     */
    public void setInsAgnoIng(Integer insAgnoIng) {
        this.insAgnoIng = insAgnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsSemIng() {
        return this.insSemIng;
    }

    /**
     * Method description
     *
     * @param insSemIng
     */
    public void setInsSemIng(Integer insSemIng) {
        this.insSemIng = insSemIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsAsign() {
        return this.insAsign;
    }

    /**
     * Method description
     *
     * @param insAsign
     */
    public void setInsAsign(Integer insAsign) {
        this.insAsign = insAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getInsElect() {
        return this.insElect;
    }

    /**
     * Method description
     *
     * @param insElect
     */
    public void setInsElect(String insElect) {
        this.insElect = insElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsAgno() {
        return this.insAgno;
    }

    /**
     * Method description
     *
     * @param insAgno
     */
    public void setInsAgno(Integer insAgno) {
        this.insAgno = insAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getInsSem() {
        return this.insSem;
    }

    /**
     * Method description
     *
     * @param insSem
     */
    public void setInsSem(Integer insSem) {
        this.insSem = insSem;
    }

    public String getInsComp() {
        return insComp;
    }

    public void setInsComp(String insComp) {
        this.insComp = insComp;
    }
}
