/*
 * @(#)InscripcionAdicionalLogroId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 07-abr-2012 18:41:03 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * InscripcionAdicionalLogroId generated by hbm2java
 */
public class InscripcionAdicionalLogroId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer ialAgno;
    private Integer ialAgnoIng;
    private Integer ialCodCar;
    private Integer ialReqAdic;
    private Integer ialRut;
    private Integer ialSem;
    private Integer ialSemIng;

    /**
     *
     */
    public InscripcionAdicionalLogroId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getIalAgno() {
        return ialAgno;
    }

    /**
     * Method description
     *
     * @param ialAgno
     */
    public void setIalAgno(Integer ialAgno) {
        this.ialAgno = ialAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getIalAgnoIng() {
        return ialAgnoIng;
    }

    /**
     * Method description
     *
     * @param ialAgnoIng
     */
    public void setIalAgnoIng(Integer ialAgnoIng) {
        this.ialAgnoIng = ialAgnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getIalCodCar() {
        return ialCodCar;
    }

    /**
     * Method description
     *
     * @param ialCodCar
     */
    public void setIalCodCar(Integer ialCodCar) {
        this.ialCodCar = ialCodCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getIalReqAdic() {
        return ialReqAdic;
    }

    /**
     * Method description
     *
     * @param ialReqAdic
     */
    public void setIalReqAdic(Integer ialReqAdic) {
        this.ialReqAdic = ialReqAdic;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getIalRut() {
        return ialRut;
    }

    /**
     * Method description
     *
     * @param ialRut
     */
    public void setIalRut(Integer ialRut) {
        this.ialRut = ialRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getIalSem() {
        return ialSem;
    }

    /**
     * Method description
     *
     * @param ialSem
     */
    public void setIalSem(Integer ialSem) {
        this.ialSem = ialSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getIalSemIng() {
        return ialSemIng;
    }

    /**
     * Method description
     *
     * @param ialSemIng
     */
    public void setIalSemIng(Integer ialSemIng) {
        this.ialSemIng = ialSemIng;
    }
}
