package domain.model;
// Generated 12-08-2013 03:30:52 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

/**
 * LogActaId generated by hbm2java
 */
public class LogActaId implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private int logFolio;
    private short logAgno;
    private boolean logSem;
    private String logEstado;
    private Date logFecha;

    /**
     *
     */
    public LogActaId() {
    }

    /**
     *
     * @return
     */
    public int getLogFolio() {
        return this.logFolio;
    }

    /**
     *
     * @param logFolio
     */
    public void setLogFolio(int logFolio) {
        this.logFolio = logFolio;
    }

    /**
     *
     * @return
     */
    public short getLogAgno() {
        return this.logAgno;
    }

    /**
     *
     * @param logAgno
     */
    public void setLogAgno(short logAgno) {
        this.logAgno = logAgno;
    }

    /**
     *
     * @return
     */
    public boolean isLogSem() {
        return this.logSem;
    }

    /**
     *
     * @param logSem
     */
    public void setLogSem(boolean logSem) {
        this.logSem = logSem;
    }

    /**
     *
     * @return
     */
    public String getLogEstado() {
        return this.logEstado;
    }

    /**
     *
     * @param logEstado
     */
    public void setLogEstado(String logEstado) {
        this.logEstado = logEstado;
    }

    /**
     *
     * @return
     */
    public Date getLogFecha() {
        return getDateGetterSetter(logFecha);
    }

    /**
     *
     * @param logFecha
     */
    public void setLogFecha(Date logFecha) {
        this.logFecha = getDateGetterSetter(logFecha);
    }
}
