package domain.model;
// Generated 12-08-2013 03:30:52 PM by Hibernate Tools 3.2.1.GA

/**
 * LogActa generated by hbm2java
 */
public class LogActa implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private LogActaId id;
    private String logUsuario;
    private EstadoActa estadoActa;

    /**
     *
     */
    public LogActa() {
    }

    /**
     *
     * @param id
     */
    public LogActa(LogActaId id) {
        this.id = id;
    }

    /**
     *
     * @param id
     * @param logUsuario
     */
    public LogActa(LogActaId id, String logUsuario) {
        this.id = id;
        this.logUsuario = logUsuario;
    }

    /**
     *
     * @return
     */
    public LogActaId getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(LogActaId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getLogUsuario() {
        return this.logUsuario;
    }

    /**
     *
     * @param logUsuario
     */
    public void setLogUsuario(String logUsuario) {
        this.logUsuario = logUsuario;
    }

    /**
     *
     * @return
     */
    public EstadoActa getEstadoActa() {
        return estadoActa;
    }

    /**
     *
     * @param estadoActa
     */
    public void setEstadoActa(EstadoActa estadoActa) {
        this.estadoActa = estadoActa;
    }
}
