/*
 * @(#)LogCertificacion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * LogCertificacion generated by hbm2java
 */
public class LogCertificacion implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Integer lcertAgno;
    private Integer lcertAgnoIng;
    private Integer lcertCodCar;
    private Date lcertFecha;
    private Integer lcertFolio;
    private String lcertGlosa;
    private Integer lcertMencion;
    private String lcertObs;
    private Integer lcertRut;
    private Integer lcertSem;
    private Integer lcertSemIng;
    private Integer lcertTcertificado;
    private Integer lcertTramite;
    private String lcertUser;
    private String lcertVerificador;
    private Tcertificado tcertificado;
    private Tramite tramite;
    private Integer lcertRutEmite;

    /**
     *
     */
    public LogCertificacion() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertAgno() {
        return lcertAgno;
    }

    /**
     * Method description
     *
     * @param lcertAgno
     */
    public void setLcertAgno(Integer lcertAgno) {
        this.lcertAgno = lcertAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertAgnoIng() {
        return lcertAgnoIng;
    }

    /**
     * Method description
     *
     * @param lcertAgnoIng
     */
    public void setLcertAgnoIng(Integer lcertAgnoIng) {
        this.lcertAgnoIng = lcertAgnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertCodCar() {
        return lcertCodCar;
    }

    /**
     * Method description
     *
     * @param lcertCodCar
     */
    public void setLcertCodCar(Integer lcertCodCar) {
        this.lcertCodCar = lcertCodCar;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getLcertFecha() {
        return getDateGetterSetter(lcertFecha);
    }

    /**
     * Method description
     *
     * @param lcertFecha
     */
    public void setLcertFecha(Date lcertFecha) {
        this.lcertFecha = getDateGetterSetter(lcertFecha);
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertFolio() {
        return lcertFolio;
    }

    /**
     * Method description
     *
     * @param lcertFolio
     */
    public void setLcertFolio(Integer lcertFolio) {
        this.lcertFolio = lcertFolio;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getLcertGlosa() {
        return lcertGlosa;
    }

    /**
     * Method description
     *
     * @param lcertGlosa
     */
    public void setLcertGlosa(String lcertGlosa) {
        this.lcertGlosa = lcertGlosa;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertMencion() {
        return lcertMencion;
    }

    /**
     * Method description
     *
     * @param lcertMencion
     */
    public void setLcertMencion(Integer lcertMencion) {
        this.lcertMencion = lcertMencion;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertRut() {
        return lcertRut;
    }

    /**
     * Method description
     *
     * @param lcertRut
     */
    public void setLcertRut(Integer lcertRut) {
        this.lcertRut = lcertRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertSem() {
        return lcertSem;
    }

    /**
     * Method description
     *
     * @param lcertSem
     */
    public void setLcertSem(Integer lcertSem) {
        this.lcertSem = lcertSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertSemIng() {
        return lcertSemIng;
    }

    /**
     * Method description
     *
     * @param lcertSemIng
     */
    public void setLcertSemIng(Integer lcertSemIng) {
        this.lcertSemIng = lcertSemIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertTcertificado() {
        return lcertTcertificado;
    }

    /**
     * Method description
     *
     * @param lcertTcertificado
     */
    public void setLcertTcertificado(Integer lcertTcertificado) {
        this.lcertTcertificado = lcertTcertificado;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLcertTramite() {
        return lcertTramite;
    }

    /**
     * Method description
     *
     * @param lcertTramite
     */
    public void setLcertTramite(Integer lcertTramite) {
        this.lcertTramite = lcertTramite;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getLcertUser() {
        return lcertUser;
    }

    /**
     * Method description
     *
     * @param lcertUser
     */
    public void setLcertUser(String lcertUser) {
        this.lcertUser = lcertUser;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getLcertVerificador() {
        return lcertVerificador;
    }

    /**
     * Method description
     *
     * @param lcertVerificador
     */
    public void setLcertVerificador(String lcertVerificador) {
        this.lcertVerificador = lcertVerificador;
    }

    /**
     * Method description
     *
     * @return
     */
    public Tcertificado getTcertificado() {
        return tcertificado;
    }

    /**
     * Method description
     *
     * @param tcertificado
     */
    public void setTcertificado(Tcertificado tcertificado) {
        this.tcertificado = tcertificado;
    }

    /**
     * Method description
     *
     * @return
     */
    public Tramite getTramite() {
        return tramite;
    }

    /**
     * Method description
     *
     * @param tramite
     */
    public void setTramite(Tramite tramite) {
        this.tramite = tramite;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getLcertObs() {
        return lcertObs;
    }

    /**
     * Method description
     *
     * @param lcertObs
     */
    public void setLcertObs(String lcertObs) {
        this.lcertObs = lcertObs;
    }

    public Integer getLcertRutEmite() {
        return lcertRutEmite;
    }

    public void setLcertRutEmite(Integer lcertRutEmite) {
        this.lcertRutEmite = lcertRutEmite;
    }
}
