/*
 * @(#)LogInscripcion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 27-01-2011 09:49:35 AM by Hibernate Tools 3.2.1.GA

/**
 * LogInscripcion generated by hbm2java
 */
public class LogInscripcion implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Asignatura asignatura;
    private Curso curso;
    private Electivo electivo;
    private Integer logAgno;
    private Integer logAsign;
    private String logCoord;
    private int logCorrel;
    private String logElect;
    private Date logFecha;
    private Integer logSecc;
    private Integer logSem;
    private String logTipoMod;
    private String logUser;
    private ProcesoInscripcion procesoInscripcion;
    private Integer logRutReali;

    /**
     *
     */
    public LogInscripcion() {
    }

    /**
     * Method description
     *
     * @return
     */
    public int getLogCorrel() {
        return this.logCorrel;
    }

    /**
     * Method description
     *
     * @param logCorrel
     */
    public void setLogCorrel(int logCorrel) {
        this.logCorrel = logCorrel;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLogAsign() {
        return this.logAsign;
    }

    /**
     * Method description
     *
     * @param logAsign
     */
    public void setLogAsign(Integer logAsign) {
        this.logAsign = logAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getLogElect() {
        return this.logElect;
    }

    /**
     * Method description
     *
     * @param logElect
     */
    public void setLogElect(String logElect) {
        this.logElect = logElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getLogCoord() {
        return this.logCoord;
    }

    /**
     * Method description
     *
     * @param logCoord
     */
    public void setLogCoord(String logCoord) {
        this.logCoord = logCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLogSecc() {
        return this.logSecc;
    }

    /**
     * Method description
     *
     * @param logSecc
     */
    public void setLogSecc(Integer logSecc) {
        this.logSecc = logSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLogAgno() {
        return this.logAgno;
    }

    /**
     * Method description
     *
     * @param logAgno
     */
    public void setLogAgno(Integer logAgno) {
        this.logAgno = logAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getLogSem() {
        return this.logSem;
    }

    /**
     * Method description
     *
     * @param logSem
     */
    public void setLogSem(Integer logSem) {
        this.logSem = logSem;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getLogFecha() {
        return getDateGetterSetter(logFecha);
    }

    /**
     * Method description
     *
     * @param logFecha
     */
    public void setLogFecha(Date logFecha) {
        this.logFecha = getDateGetterSetter(logFecha);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getLogTipoMod() {
        return this.logTipoMod;
    }

    /**
     * Method description
     *
     * @param logTipoMod
     */
    public void setLogTipoMod(String logTipoMod) {
        this.logTipoMod = logTipoMod;
    }

    public ProcesoInscripcion getProcesoInscripcion() {
        return procesoInscripcion;
    }

    public void setProcesoInscripcion(ProcesoInscripcion procesoInscripcion) {
        this.procesoInscripcion = procesoInscripcion;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getLogUser() {
        return this.logUser;
    }

    /**
     * Method description
     *
     * @param logUser
     */
    public void setLogUser(String logUser) {
        this.logUser = logUser;
    }

    /**
     * Method description
     *
     * @return
     */
    public Asignatura getAsignatura() {
        return asignatura;
    }

    /**
     * Method description
     *
     * @param asignatura
     */
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     * Method description
     *
     * @return
     */
    public Electivo getElectivo() {
        return electivo;
    }

    /**
     * Method description
     *
     * @param electivo
     */
    public void setElectivo(Electivo electivo) {
        this.electivo = electivo;
    }

    public Integer getLogRutReali() {
        return logRutReali;
    }

    public void setLogRutReali(Integer logRutReali) {
        this.logRutReali = logRutReali;
    }
}
