/*
 * @(#)Malla.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Malla generated by hbm2java
 */
public class Malla implements Serializable {

    private static final long serialVersionUID = 1L;
    private Set<Asignatura> asignaturas = new HashSet<>(0);

    private Asignatura asignatura;
    private MallaId id;
    private Integer maCorrelElect;
    private Integer maCorrelVisual;
    private Unidad maUnidadDicta;
    private Integer maLineaVisual;
    private Integer maNivel;
    private Plan plan;

    /**
     *
     */
    public Malla() {
    }

    /**
     * Method description
     *
     * @return
     */
    public MallaId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(MallaId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Plan getPlan() {
        return this.plan;
    }

    /**
     * Method description
     *
     * @param plan
     */
    public void setPlan(Plan plan) {
        this.plan = plan;
    }

    /**
     * Method description
     *
     * @return
     */
    public Asignatura getAsignatura() {
        return this.asignatura;
    }

    /**
     * Method description
     *
     * @param asignatura
     */
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMaCorrelElect() {
        return maCorrelElect;
    }

    /**
     * Method description
     *
     *
     * @param maCorrelElect
     */
    public void setMaCorrelElect(Integer maCorrelElect) {
        this.maCorrelElect = maCorrelElect;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMaNivel() {
        return maNivel;
    }

    /**
     * Method description
     *
     *
     * @param maNivel
     */
    public void setMaNivel(Integer maNivel) {
        this.maNivel = maNivel;
    }

    public Unidad getMaUnidadDicta() {
        return maUnidadDicta;
    }

    public void setMaUnidadDicta(Unidad maUnidadDicta) {
        this.maUnidadDicta = maUnidadDicta;
    }   

    /**
     * Method description
     *
     * @return
     */
    public Set<Asignatura> getAsignaturas() {
        return this.asignaturas;
    }

    /**
     * Method description
     *
     * @param asignaturas
     */
    public void setAsignaturas(Set<Asignatura> asignaturas) {
        this.asignaturas = asignaturas;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMaLineaVisual() {
        return maLineaVisual;
    }

    /**
     * Method description
     *
     *
     * @param maLineaVisual
     */
    public void setMaLineaVisual(Integer maLineaVisual) {
        this.maLineaVisual = maLineaVisual;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMaCorrelVisual() {
        return maCorrelVisual;
    }

    /**
     * Method description
     *
     *
     * @param maCorrelVisual
     */
    public void setMaCorrelVisual(Integer maCorrelVisual) {
        this.maCorrelVisual = maCorrelVisual;
    }
}
