/*
 * @(#)MallaId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MallaId generated by hbm2java
 */
public class MallaId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer maAsign;
    private Integer maCodCar;
    private Integer maCodMen;
    private Integer maCodPlan;

    /**
     *
     */
    public MallaId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMaCodCar() {
        return this.maCodCar;
    }

    /**
     * Method description
     *
     * @param maCodCar
     */
    public void setMaCodCar(Integer maCodCar) {
        this.maCodCar = maCodCar;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMaCodPlan() {
        return maCodPlan;
    }

    /**
     * Method description
     *
     *
     * @param maCodPlan
     */
    public void setMaCodPlan(Integer maCodPlan) {
        this.maCodPlan = maCodPlan;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMaCodMen() {
        return maCodMen;
    }

    /**
     * Method description
     *
     *
     * @param maCodMen
     */
    public void setMaCodMen(Integer maCodMen) {
        this.maCodMen = maCodMen;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMaAsign() {
        return this.maAsign;
    }

    /**
     * Method description
     *
     * @param maAsign
     */
    public void setMaAsign(Integer maAsign) {
        this.maAsign = maAsign;
    }    
}
