/*
 * @(#)MaterialApoyo.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;
import infrastructure.util.common.CommonAlumnoUtil;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * MaterialApoyo generated by hbm2java
 */
public class MaterialApoyo implements Serializable {

    private static final long serialVersionUID = 1L;
    private Curso curso;
    private String matArchivo;
    private Integer matCorrel;
    private String matDescripcion;
    private Date matFechaArchivado;
    private Date matFechaHabilitacion;
    private String matPerfil;
    private Integer matRutAutor;
    private Integer matTipo;
    private Tmaterial tmaterial;

    /**
     *
     */
    public MaterialApoyo() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMatArchivo() {
        return matArchivo;
    }

    /**
     * Method description
     *
     * @param matArchivo
     */
    public void setMatArchivo(String matArchivo) {
        this.matArchivo = matArchivo;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMatCorrel() {
        return matCorrel;
    }

    /**
     * Method description
     *
     * @param matCorrel
     */
    public void setMatCorrel(Integer matCorrel) {
        this.matCorrel = matCorrel;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMatDescripcion() {
        return matDescripcion;
    }

    /**
     * Method description
     *
     * @param matDescripcion
     */
    public void setMatDescripcion(String matDescripcion) {
        this.matDescripcion = matDescripcion;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getMatFechaArchivado() {
        return getDateGetterSetter(matFechaArchivado);
    }

    /**
     * Method description
     *
     * @param matFechaArchivado
     */
    public void setMatFechaArchivado(Date matFechaArchivado) {
        this.matFechaArchivado = getDateGetterSetter(matFechaArchivado);
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getMatFechaHabilitacion() {
        return getDateGetterSetter(matFechaHabilitacion);
    }

    /**
     * Method description
     *
     * @param matFechaHabilitacion
     */
    public void setMatFechaHabilitacion(Date matFechaHabilitacion) {
        this.matFechaHabilitacion = getDateGetterSetter(matFechaHabilitacion);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMatPerfil() {
        return matPerfil;
    }

    /**
     * Method description
     *
     * @param matPerfil
     */
    public void setMatPerfil(String matPerfil) {
        this.matPerfil = matPerfil;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMatRutAutor() {
        return matRutAutor;
    }

    /**
     * Method description
     *
     * @param matRutAutor
     */
    public void setMatRutAutor(Integer matRutAutor) {
        this.matRutAutor = matRutAutor;
    }

    /**
     * Method description
     *
     * @return
     */
    public Tmaterial getTmaterial() {
        return tmaterial;
    }

    /**
     * Method description
     *
     * @param tmaterial
     */
    public void setTmaterial(Tmaterial tmaterial) {
        this.tmaterial = tmaterial;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMatTipo() {
        return matTipo;
    }

    /**
     * Method description
     *
     * @param matTipo
     */
    public void setMatTipo(Integer matTipo) {
        this.matTipo = matTipo;
    }
    
    public String getNombreAlumnoAutor()
    {
        return CommonAlumnoUtil.find(this.matRutAutor).getNombre();
    }
}
