/*
 * @(#)MatriculaHistorico.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * MatriculaHistorico generated by hbm2java
 */
public class MatriculaHistorico implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private MatriculaHistoricoId id;
    private Date mathFecha;

    /**
     *
     */
    public MatriculaHistorico() {
    }

    /**
     * Method description
     *
     * @return
     */
    public MatriculaHistoricoId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(MatriculaHistoricoId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getMathFecha() {
        return getDateGetterSetter(mathFecha);
    }

    /**
     * Method description
     *
     * @param mathFecha
     */
    public void setMathFecha(Date mathFecha) {
        this.mathFecha = getDateGetterSetter(mathFecha);
    }
}
