/*
 * @(#)MatriculaHistoricoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MatriculaHistoricoId generated by hbm2java
 */
public class MatriculaHistoricoId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer mathAgno;
    private Integer mathAgnoIng;
    private Integer mathCodCar;
    private Integer mathRut;
    private Integer mathSem;
    private Integer mathSemIng;

    /**
     *
     */
    public MatriculaHistoricoId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMathRut() {
        return this.mathRut;
    }

    /**
     * Method description
     *
     * @param mathRut
     */
    public void setMathRut(Integer mathRut) {
        this.mathRut = mathRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMathCodCar() {
        return this.mathCodCar;
    }

    /**
     * Method description
     *
     * @param mathCodCar
     */
    public void setMathCodCar(Integer mathCodCar) {
        this.mathCodCar = mathCodCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMathAgnoIng() {
        return this.mathAgnoIng;
    }

    /**
     * Method description
     *
     * @param mathAgnoIng
     */
    public void setMathAgnoIng(Integer mathAgnoIng) {
        this.mathAgnoIng = mathAgnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMathSemIng() {
        return this.mathSemIng;
    }

    /**
     * Method description
     *
     * @param mathSemIng
     */
    public void setMathSemIng(Integer mathSemIng) {
        this.mathSemIng = mathSemIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMathAgno() {
        return this.mathAgno;
    }

    /**
     * Method description
     *
     * @param mathAgno
     */
    public void setMathAgno(Integer mathAgno) {
        this.mathAgno = mathAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMathSem() {
        return this.mathSem;
    }

    /**
     * Method description
     *
     * @param mathSem
     */
    public void setMathSem(Integer mathSem) {
        this.mathSem = mathSem;
    }
   
}
