/*
 * @(#)Mencion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import infrastructure.util.ActionUtil;
import infrastructure.util.ContextUtil;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * Mencion generated by hbm2java
 */
public class Mencion implements Serializable {
    private static final long serialVersionUID = 1L;
    private Carrera carrera;
    private MencionId id;
    private String menNom;
    private Unidad unidad;
    private String menPrefijo;
    private String menPlanComun;
    private Integer atributoMenUnidad;

    /**
     *
     */
    public Mencion() {
    }

    /**
     *
     * @param carrera
     * @param mencion
     */
    public Mencion(Integer carrera, Integer mencion) {
        this.id = new MencionId();
        this.id.setMenCodCar(carrera);
        this.id.setMenCodMen(mencion);
    }

    /**
     * Method description
     *
     * @return
     */
    public MencionId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(MencionId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Carrera getCarrera() {
        return this.carrera;
    }

    /**
     * Method description
     *
     * @param carrera
     */
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMenNom() {
        return this.menNom;
    }

    /**
     * Method description
     *
     * @param menNom
     */
    public void setMenNom(String menNom) {
        this.menNom = menNom;
    }

    public Unidad getUnidad() {
        return unidad;
    }

    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreCarreraFull() {
        return  ContextUtil.getDAO().getMencionPersistence(ActionUtil.getDBUser()).getNombreCarreraFull(
                        this.id.getMenCodCar(), this.id.getMenCodMen());
    }

    public String getMenPrefijo() {
        return menPrefijo;
    }

    public void setMenPrefijo(String menPrefijo) {
        this.menPrefijo = menPrefijo;
    }

    public String getMenPlanComun() {
        return menPlanComun;
    }

    public void setMenPlanComun(String menPlanComun) {
        this.menPlanComun = menPlanComun;
    }

    public Integer getAtributoMenUnidad() {
        return atributoMenUnidad;
    }

    public void setAtributoMenUnidad(Integer atributoMenUnidad) {
        this.atributoMenUnidad = atributoMenUnidad;
    }
       
}
