/*
 * @(#)MencionId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MencionId generated by hbm2java
 */
public class MencionId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer menCodCar;
    private Integer menCodMen;

    /**
     *
     */
    public MencionId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMenCodCar() {
        return this.menCodCar;
    }

    /**
     * Method description
     *
     * @param menCodCar
     */
    public void setMenCodCar(Integer menCodCar) {
        this.menCodCar = menCodCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMenCodMen() {
        return this.menCodMen;
    }

    /**
     * Method description
     *
     * @param menCodMen
     */
    public void setMenCodMen(Integer menCodMen) {
        this.menCodMen = menCodMen;
    }
}
