/*
 * @(#)MencionInfoIntranet.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 16-03-2011 04:53:33 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MencionInfoIntranet generated by hbm2java
 */
public class MencionInfoIntranet implements Serializable {

    private static final long serialVersionUID = 1L;
    private MencionInfoIntranetId id;
    private Mencion mencion;
    private String miniUrlCalendarioAct;
    private String miniUrlNormativa;

    /**
     *
     */
    public MencionInfoIntranet() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public MencionInfoIntranetId getId() {
        return id;
    }

    /**
     * Method description
     *
     *
     * @param id
     */
    public void setId(MencionInfoIntranetId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getMiniUrlNormativa() {
        return miniUrlNormativa;
    }

    /**
     * Method description
     *
     *
     * @param miniUrlNormativa
     */
    public void setMiniUrlNormativa(String miniUrlNormativa) {
        this.miniUrlNormativa = miniUrlNormativa;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getMiniUrlCalendarioAct() {
        return miniUrlCalendarioAct;
    }

    /**
     * Method description
     *
     *
     * @param miniUrlCalendarioAct
     */
    public void setMiniUrlCalendarioAct(String miniUrlCalendarioAct) {
        this.miniUrlCalendarioAct = miniUrlCalendarioAct;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Mencion getMencion() {
        return mencion;
    }

    /**
     * Method description
     *
     *
     * @param mencion
     */
    public void setMencion(Mencion mencion) {
        this.mencion = mencion;
    }
}
