/*
 * @(#)MencionInfoIntranetId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MencionInfoIntranetId generated by hbm2java
 */
public class MencionInfoIntranetId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer miniCodCar;
    private Integer miniCodMen;

    /**
     *
     */
    public MencionInfoIntranetId() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMiniCodCar() {
        return miniCodCar;
    }

    /**
     * Method description
     *
     *
     * @param miniCodCar
     */
    public void setMiniCodCar(Integer miniCodCar) {
        this.miniCodCar = miniCodCar;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMiniCodMen() {
        return miniCodMen;
    }

    /**
     * Method description
     *
     *
     * @param miniCodMen
     */
    public void setMiniCodMen(Integer miniCodMen) {
        this.miniCodMen = miniCodMen;
    }
}
