/*
 * @(#)MensajeDestinatario.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MensajeDestinatario generated by hbm2java
 */
public class MensajeDestinatario implements Serializable {

    private static final long serialVersionUID = 1L;
    private MensajeDestinatarioId id;
    private Mensaje mensaje;
    private String msgdEstado;

    /**
     *
     */
    public MensajeDestinatario() {
    }

    /**
     * Method description
     *
     * @return
     */
    public MensajeDestinatarioId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(MensajeDestinatarioId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Mensaje getMensaje() {
        return this.mensaje;
    }

    /**
     * Method description
     *
     * @param mensaje
     */
    public void setMensaje(Mensaje mensaje) {
        this.mensaje = mensaje;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMsgdEstado() {
        return this.msgdEstado;
    }

    /**
     * Method description
     *
     * @param msgdEstado
     */
    public void setMsgdEstado(String msgdEstado) {
        this.msgdEstado = msgdEstado;
    }
}
