/*
 * @(#)MensajeAttach.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MensajeAttach generated by hbm2java
 */
public class MensajeAttach implements Serializable {

    private static final long serialVersionUID = 1L;
    private MensajeAttachId id;
    private String menaAttachFile;

    // private File menaFile;
    private Mensaje mensaje;

    /**
     *
     */
    public MensajeAttach() {
    }

    /**
     * Method description
     *
     * @return
     */
    public MensajeAttachId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(MensajeAttachId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Mensaje getMensaje() {
        return this.mensaje;
    }

    /**
     * Method description
     *
     * @param mensaje
     */
    public void setMensaje(Mensaje mensaje) {
        this.mensaje = mensaje;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getMenaAttachFile() {
        return menaAttachFile;
    }

    /**
     * Method description
     *
     *
     * @param menaAttachFile
     */
    public void setMenaAttachFile(String menaAttachFile) {
        this.menaAttachFile = menaAttachFile;
    }
}
