/*
 * @(#)Mensaje.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import org.apache.commons.lang3.StringUtils;
import static infrastructure.util.DateUtil.getDateGetterSetter;
import static infrastructure.util.DateUtil.getFormatedDate;
import static infrastructure.util.SystemParametersUtil.DATE_FULL_FORMAT;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje implements Serializable {

    private static final long serialVersionUID = 1L;
    private List<MensajeAttach> mensajeAttachList;
    private String msgAttach;
    private Integer msgCorrel;
    private String msgEstado;
    private Date msgFecha;
    private String msgIdSession;
    private String msgMsg;
    private String msgNombreEnv;
    private String msgPara;
    private String msgRolEnv;
    private Integer msgRutEnv;
    private String msgSubject;
    private TmensajeOrigen tmensajeOrigen;
    private String msgImagen;
    private String msgUrl;
    private String msgTipo;

    /**
     *
     */
    public Mensaje() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMsgCorrel() {
        return msgCorrel;
    }

    /**
     * Method description
     *
     * @param msgCorrel
     */
    public void setMsgCorrel(Integer msgCorrel) {
        this.msgCorrel = msgCorrel;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getMsgFecha() {
        return getDateGetterSetter(msgFecha);
    }

    /**
     * Method description
     *
     * @param msgFecha
     */
    public void setMsgFecha(Date msgFecha) {
        this.msgFecha = getDateGetterSetter(msgFecha);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMsgMsg() {
        return msgMsg;
    }

    /**
     * Method description
     *
     * @param msgMsg
     */
    public void setMsgMsg(String msgMsg) {
        this.msgMsg = msgMsg;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMsgNombreEnv() {
        return msgNombreEnv;
    }

    /**
     * Method description
     *
     * @param msgNombreEnv
     */
    public void setMsgNombreEnv(String msgNombreEnv) {
        this.msgNombreEnv = msgNombreEnv;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMsgPara() {
        return msgPara;
    }

    /**
     * Method description
     *
     * @param msgPara
     */
    public void setMsgPara(String msgPara) {
        this.msgPara = msgPara;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMsgRolEnv() {
        return msgRolEnv;
    }

    /**
     * Method description
     *
     * @param msgRolEnv
     */
    public void setMsgRolEnv(String msgRolEnv) {
        this.msgRolEnv = msgRolEnv;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMsgRutEnv() {
        return msgRutEnv;
    }

    /**
     * Method description
     *
     * @param msgRutEnv
     */
    public void setMsgRutEnv(Integer msgRutEnv) {
        this.msgRutEnv = msgRutEnv;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMsgSubject() {
        return msgSubject;
    }

    /**
     * Method description
     *
     * @param msgSubject
     */
    public void setMsgSubject(String msgSubject) {
        this.msgSubject = msgSubject;
    }

    /**
     * Method description
     *
     * @return
     */
    public TmensajeOrigen getTmensajeOrigen() {
        return tmensajeOrigen;
    }

    /**
     * Method description
     *
     * @param tmensajeOrigen
     */
    public void setTmensajeOrigen(TmensajeOrigen tmensajeOrigen) {
        this.tmensajeOrigen = tmensajeOrigen;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getFormatedFullDate() {
        return getFormatedDate(msgFecha, DATE_FULL_FORMAT);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMsgEstado() {
        return msgEstado;
    }

    /**
     * Method description
     *
     * @param msgEstado
     */
    public void setMsgEstado(String msgEstado) {
        this.msgEstado = msgEstado;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public List<MensajeAttach> getMensajeAttachList() {
        return mensajeAttachList;
    }

    /**
     * Method description
     *
     *
     * @param mensajeAttachList
     */
    public void setMensajeAttachList(List<MensajeAttach> mensajeAttachList) {
        this.mensajeAttachList = mensajeAttachList;
    }

    // LOGIC//
    /**
     * Method description
     *
     * @return
     */
    public String getNombreEnvShort() {
        return StringUtils.substring(this.msgNombreEnv, 0, 40);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getSubjectShort() {
        return StringUtils.substring(this.msgSubject, 0, 40);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getParatShort() {
        return StringUtils.substring(this.msgPara, 0, 40);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getMsgIdSession() {
        return msgIdSession;
    }

    /**
     * Method description
     *
     * @param msgIdSession
     */
    public void setMsgIdSession(String msgIdSession) {
        this.msgIdSession = msgIdSession;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getMsgAttach() {
        return msgAttach;
    }

    /**
     * Method description
     *
     *
     * @param msgAttach
     */
    public void setMsgAttach(String msgAttach) {
        this.msgAttach = msgAttach;
    }

    public String getMsgImagen() {
        return msgImagen;
    }

    public void setMsgImagen(String msgImagen) {
        this.msgImagen = msgImagen;
    }

    public String getMsgUrl() {
        return msgUrl;
    }

    public void setMsgUrl(String msgUrl) {
        this.msgUrl = msgUrl;
    }


    public String getMsgTipo() {
        return msgTipo;
    }

    public void setMsgTipo(String msgTipo) {
        this.msgTipo = msgTipo;
    }
    
    /**
     *
     * @return
     */
    public String getPara()
    {
        return this.msgPara.contains("_LISTA_")?"LISTA":this.msgPara;
    }
}
