/*
 * @(#)MensajeDestinatarioId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MensajeDestinatarioId generated by hbm2java
 */
public class MensajeDestinatarioId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer msgdCorrel;
    private Integer msgdRutDest;

    /**
     *
     */
    public MensajeDestinatarioId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMsgdCorrel() {
        return this.msgdCorrel;
    }

    /**
     * Method description
     *
     * @param msgdCorrel
     */
    public void setMsgdCorrel(Integer msgdCorrel) {
        this.msgdCorrel = msgdCorrel;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getMsgdRutDest() {
        return this.msgdRutDest;
    }

    /**
     * Method description
     *
     * @param msgdRutDest
     */
    public void setMsgdRutDest(Integer msgdRutDest) {
        this.msgdRutDest = msgdRutDest;
    }
}
