/*
 * @(#)MensajeAttachId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MensajeAttachId generated by hbm2java
 */
public class MensajeAttachId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer menaCorrelAttach;
    private Integer menaCorrelMsg;

    /**
     *
     */
    public MensajeAttachId() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMenaCorrelMsg() {
        return menaCorrelMsg;
    }

    /**
     * Method description
     *
     *
     * @param menaCorrelMsg
     */
    public void setMenaCorrelMsg(Integer menaCorrelMsg) {
        this.menaCorrelMsg = menaCorrelMsg;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getMenaCorrelAttach() {
        return menaCorrelAttach;
    }

    /**
     * Method description
     *
     *
     * @param menaCorrelAttach
     */
    public void setMenaCorrelAttach(Integer menaCorrelAttach) {
        this.menaCorrelAttach = menaCorrelAttach;
    }    
}
