/*
 * @(#)ModuloHorarioId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ModuloHorarioId generated by hbm2java
 */
public class ModuloHorarioId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer modCod;
    private Integer modVersion;

    /**
     *
     */
    public ModuloHorarioId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getModCod() {
        return this.modCod;
    }

    /**
     * Method description
     *
     * @param modCod
     */
    public void setModCod(Integer modCod) {
        this.modCod = modCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getModVersion() {
        return this.modVersion;
    }

    /**
     * Method description
     *
     * @param modVersion
     */
    public void setModVersion(Integer modVersion) {
        this.modVersion = modVersion;
    }    
}
