/*
 * @(#)ModuloHorarioVersion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ModuloHorarioVersion generated by hbm2java
 */
public class ModuloHorarioVersion implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer modvAnoInicio;
    private Integer modvAnoTermino;
    private Integer modvSemInicio;
    private Integer modvSemTermino;
    private Integer modvVersion;

    /**
     *
     */
    public ModuloHorarioVersion() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getModvVersion() {
        return this.modvVersion;
    }

    /**
     * Method description
     *
     * @param modvVersion
     */
    public void setModvVersion(Integer modvVersion) {
        this.modvVersion = modvVersion;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getModvAnoInicio() {
        return this.modvAnoInicio;
    }

    /**
     * Method description
     *
     * @param modvAnoInicio
     */
    public void setModvAnoInicio(Integer modvAnoInicio) {
        this.modvAnoInicio = modvAnoInicio;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getModvSemInicio() {
        return this.modvSemInicio;
    }

    /**
     * Method description
     *
     * @param modvSemInicio
     */
    public void setModvSemInicio(Integer modvSemInicio) {
        this.modvSemInicio = modvSemInicio;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getModvAnoTermino() {
        return this.modvAnoTermino;
    }

    /**
     * Method description
     *
     * @param modvAnoTermino
     */
    public void setModvAnoTermino(Integer modvAnoTermino) {
        this.modvAnoTermino = modvAnoTermino;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getModvSemTermino() {
        return this.modvSemTermino;
    }

    /**
     * Method description
     *
     * @param modvSemTermino
     */
    public void setModvSemTermino(Integer modvSemTermino) {
        this.modvSemTermino = modvSemTermino;
    }    
}
