/*
 * @(#)ModuloHorario.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * ModuloHorario generated by hbm2java
 */
public class ModuloHorario implements Serializable {

    private static final long serialVersionUID = 1L;
    private Set<Horario> horarios = new HashSet<>(0);
    private ModuloHorarioId id;
    private String modDesde;
    private String modHasta;
    private Integer modOrder;
    private ModuloHorarioVersion moduloHorarioVersion;
    private String modTipo;

    /**
     *
     */
    public ModuloHorario() {
    }

    /**
     * Method description
     *
     * @return
     */
    public ModuloHorarioId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(ModuloHorarioId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public ModuloHorarioVersion getModuloHorarioVersion() {
        return this.moduloHorarioVersion;
    }

    /**
     * Method description
     *
     * @param moduloHorarioVersion
     */
    public void setModuloHorarioVersion(ModuloHorarioVersion moduloHorarioVersion) {
        this.moduloHorarioVersion = moduloHorarioVersion;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getModDesde() {
        return this.modDesde;
    }

    /**
     * Method description
     *
     * @param modDesde
     */
    public void setModDesde(String modDesde) {
        this.modDesde = modDesde;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getModHasta() {
        return this.modHasta;
    }

    /**
     * Method description
     *
     * @param modHasta
     */
    public void setModHasta(String modHasta) {
        this.modHasta = modHasta;
    }

    /**
     * Method description
     *
     * @return
     */
    public Set<Horario> getHorarios() {
        return this.horarios;
    }

    /**
     * Method description
     *
     * @param horarios
     */
    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }

    public Integer getModOrder() {
        return modOrder;
    }

    public void setModOrder(Integer modOrder) {
        this.modOrder = modOrder;
    }

    public String getModTipo() {
        return modTipo;
    }

    public void setModTipo(String modTipo) {
        this.modTipo = modTipo;
    }

}
