/*
 * @(#)NominaCarrera.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 13-09-2010 05:58:20 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * NominaCarrera generated by hbm2java
 */
public class NominaCarrera implements Serializable {

    private static final long serialVersionUID = 1L;
    private NominaCarreraId id;
    private Integer ncAgno;
    private Integer ncSem;

    /**
     *
     */
    public NominaCarrera() {
    }

    /**
     * Method description
     *
     * @return
     */
    public NominaCarreraId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(NominaCarreraId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getNcAgno() {
        return this.ncAgno;
    }

    /**
     * Method description
     *
     * @param ncAgno
     */
    public void setNcAgno(Integer ncAgno) {
        this.ncAgno = ncAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getNcSem() {
        return this.ncSem;
    }

    /**
     * Method description
     *
     * @param ncSem
     */
    public void setNcSem(Integer ncSem) {
        this.ncSem = ncSem;
    }
}
