/*
 * @(#)NominaCarreraId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 13-09-2010 05:58:20 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * NominaCarreraId generated by hbm2java
 */
public class NominaCarreraId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer ncCodCar;
    private Integer ncCodMen;
    private Integer ncCorrel;

    /**
     *
     */
    public NominaCarreraId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public int getNcCorrel() {
        return this.ncCorrel;
    }

    /**
     * Method description
     *
     * @param ncCorrel
     */
    public void setNcCorrel(int ncCorrel) {
        this.ncCorrel = ncCorrel;
    }

    /**
     * Method description
     *
     * @return
     */
    public int getNcCodCar() {
        return this.ncCodCar;
    }

    /**
     * Method description
     *
     * @param ncCodCar
     */
    public void setNcCodCar(int ncCodCar) {
        this.ncCodCar = ncCodCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getNcCodMen() {
        return this.ncCodMen;
    }

    /**
     * Method description
     *
     * @param ncCodMen
     */
    public void setNcCodMen(Integer ncCodMen) {
        this.ncCodMen = ncCodMen;
    }
}
