/*
 * @(#)Pais.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Pais generated by hbm2java
 */
public class Pais implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer paiCod;
    private String paiNom;

    /**
     *
     */
    public Pais() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPaiCod() {
        return this.paiCod;
    }

    /**
     * Method description
     *
     * @param paiCod
     */
    public void setPaiCod(Integer paiCod) {
        this.paiCod = paiCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getPaiNom() {
        return this.paiNom;
    }

    /**
     * Method description
     *
     * @param paiNom
     */
    public void setPaiNom(String paiNom) {
        this.paiNom = paiNom;
    }
}
