/*
 * @(#)Parametro.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ParametroService generated by hbm2java
 */
public class Parametro implements Serializable {

    private static final long serialVersionUID = 1L;
    private String parDescripcion;
    private String parNomVar;
    private String parValor;

    /**
     *
     */
    public Parametro() {
    }

    /**
     * Method description
     *
     * @return
     */
    public String getParNomVar() {
        return this.parNomVar;
    }

    /**
     * Method description
     *
     * @param parNomVar
     */
    public void setParNomVar(String parNomVar) {
        this.parNomVar = parNomVar;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getParValor() {
        return this.parValor;
    }

    /**
     * Method description
     *
     * @param parValor
     */
    public void setParValor(String parValor) {
        this.parValor = parValor;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getParDescripcion() {
        return this.parDescripcion;
    }

    /**
     * Method description
     *
     * @param parDescripcion
     */
    public void setParDescripcion(String parDescripcion) {
        this.parDescripcion = parDescripcion;
    }
}
