/*
 * @(#)MencionId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * MencionId generated by hbm2java
 */
public class ParametroMencionId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer pmenCodCar;
    private Integer pmenCodMen;

    /**
     *
     */
    public ParametroMencionId() {
    }

    /**
     *
     * @return
     */
    public Integer getPmenCodCar() {
        return pmenCodCar;
    }

    /**
     *
     * @param pmenCodCar
     */
    public void setPmenCodCar(Integer pmenCodCar) {
        this.pmenCodCar = pmenCodCar;
    }

    /**
     *
     * @return
     */
    public Integer getPmenCodMen() {
        return pmenCodMen;
    }

    /**
     *
     * @param pmenCodMen
     */
    public void setPmenCodMen(Integer pmenCodMen) {
        this.pmenCodMen = pmenCodMen;
    }
}
