/*
 * @(#)Mencion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
/**
 * Mencion generated by hbm2java
 */
public class ParametroMencion implements Serializable {

    private static final long serialVersionUID = 1L;
    private ParametroMencionId id;
    private Integer pmenAgnoAct;
    private Integer pmenSemAct;
    private Integer pmenAgnoIns;
    private Integer pmenSemIns;
    private Integer pmenAgnoEnc;
    private Integer pmenSemEnc;
    private Integer pmenAgnoCal;
    private Integer pmenSemCal;
    private Date pmenInsPostInicio;
    private Date pmenInsPostTermino;
    private Date pmenInsAdmTermino;
    private Date pmenInsModTermino;
    private Date pmenInsEliminTermino;
    private String pmenInsLock;
    private Integer pmenInsMaxAsign;
    private Integer pmenInsMaxNivelAdelanto;

    /**
     *
     */
    public ParametroMencion() {
    }

    /**
     *
     * @return
     */
    public ParametroMencionId getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(ParametroMencionId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Integer getPmenAgnoAct() {
        return pmenAgnoAct;
    }

    /**
     *
     * @param pmenAgnoAct
     */
    public void setPmenAgnoAct(Integer pmenAgnoAct) {
        this.pmenAgnoAct = pmenAgnoAct;
    }

    /**
     *
     * @return
     */
    public Integer getPmenSemAct() {
        return pmenSemAct;
    }

    /**
     *
     * @param pmenSemAct
     */
    public void setPmenSemAct(Integer pmenSemAct) {
        this.pmenSemAct = pmenSemAct;
    }

    /**
     *
     * @return
     */
    public Integer getPmenAgnoIns() {
        return pmenAgnoIns;
    }

    /**
     *
     * @param pmenAgnoIns
     */
    public void setPmenAgnoIns(Integer pmenAgnoIns) {
        this.pmenAgnoIns = pmenAgnoIns;
    }

    /**
     *
     * @return
     */
    public Integer getPmenSemIns() {
        return pmenSemIns;
    }

    /**
     *
     * @param pmenSemIns
     */
    public void setPmenSemIns(Integer pmenSemIns) {
        this.pmenSemIns = pmenSemIns;
    }

    /**
     *
     * @return
     */
    public Integer getPmenAgnoEnc() {
        return pmenAgnoEnc;
    }

    /**
     *
     * @param pmenAgnoEnc
     */
    public void setPmenAgnoEnc(Integer pmenAgnoEnc) {
        this.pmenAgnoEnc = pmenAgnoEnc;
    }

    /**
     *
     * @return
     */
    public Integer getPmenSemEnc() {
        return pmenSemEnc;
    }

    /**
     *
     * @param pmenSemEnc
     */
    public void setPmenSemEnc(Integer pmenSemEnc) {
        this.pmenSemEnc = pmenSemEnc;
    }

    /**
     *
     * @return
     */
    public Integer getPmenAgnoCal() {
        return pmenAgnoCal;
    }

    /**
     *
     * @param pmenAgnoCal
     */
    public void setPmenAgnoCal(Integer pmenAgnoCal) {
        this.pmenAgnoCal = pmenAgnoCal;
    }

    /**
     *
     * @return
     */
    public Integer getPmenSemCal() {
        return pmenSemCal;
    }

    /**
     *
     * @param pmenSemCal
     */
    public void setPmenSemCal(Integer pmenSemCal) {
        this.pmenSemCal = pmenSemCal;
    }

    /**
     *
     * @return
     */
    public Date getPmenInsPostInicio() {
        return pmenInsPostInicio;
    }

    /**
     *
     * @param pmenInsPostInicio
     */
    public void setPmenInsPostInicio(Date pmenInsPostInicio) {
        this.pmenInsPostInicio = pmenInsPostInicio;
    }

    /**
     *
     * @return
     */
    public Date getPmenInsPostTermino() {
        return pmenInsPostTermino;
    }

    /**
     *
     * @param pmenInsPostTermino
     */
    public void setPmenInsPostTermino(Date pmenInsPostTermino) {
        this.pmenInsPostTermino = pmenInsPostTermino;
    }

    public Date getPmenInsAdmTermino() {
        return pmenInsAdmTermino;
    }

    public void setPmenInsAdmTermino(Date pmenInsAdmTermino) {
        this.pmenInsAdmTermino = pmenInsAdmTermino;
    }

    /**
     *
     * @return
     */
    public Date getPmenInsModTermino() {
        return pmenInsModTermino;
    }

    /**
     *
     * @param pmenInsModTermino
     */
    public void setPmenInsModTermino(Date pmenInsModTermino) {
        this.pmenInsModTermino = pmenInsModTermino;
    }

    /**
     *
     * @return
     */
    public Date getPmenInsEliminTermino() {
        return pmenInsEliminTermino;
    }

    /**
     *
     * @param pmenInsEliminTermino
     */
    public void setPmenInsEliminTermino(Date pmenInsEliminTermino) {
        this.pmenInsEliminTermino = pmenInsEliminTermino;
    }

    /**
     *
     * @return
     */
    public Integer getPmenInsMaxAsign() {
        return pmenInsMaxAsign;
    }

    /**
     *
     * @param pmenInsMaxAsign
     */
    public void setPmenInsMaxAsign(Integer pmenInsMaxAsign) {
        this.pmenInsMaxAsign = pmenInsMaxAsign;
    }

    /**
     *
     * @return
     */
    public Integer getPmenInsMaxNivelAdelanto() {
        return pmenInsMaxNivelAdelanto;
    }

    /**
     *
     * @param pmenInsMaxNivelAdelanto
     */
    public void setPmenInsMaxNivelAdelanto(Integer pmenInsMaxNivelAdelanto) {
        this.pmenInsMaxNivelAdelanto = pmenInsMaxNivelAdelanto;
    }

    public String getPmenInsLock() {
        return pmenInsLock;
    }

    public void setPmenInsLock(String pmenInsLock) {
        this.pmenInsLock = pmenInsLock;
    }
}