/*
 * @(#)Plan.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Plan generated by hbm2java
 */
public class Plan implements Serializable {

    private static final long serialVersionUID = 1L;    
    private PlanId id;
    private Mencion mencion;
    private String plaResoluciones;
    private Character plaVigente;
    private Regimen regimen;
    private PlanLogro planLogro;

    /**
     *
     */
    public Plan() {
    }

    /**
     * Method description
     *
     * @return
     */
    public PlanId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(PlanId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public Regimen getRegimen() {
        return this.regimen;
    }

    /**
     * Method description
     *
     * @param regimen
     */
    public void setRegimen(Regimen regimen) {
        this.regimen = regimen;
    }

    /**
     * Method description
     *
     * @return
     */
    public Mencion getMencion() {
        return this.mencion;
    }

    /**
     * Method description
     *
     * @param mencion
     */
    public void setMencion(Mencion mencion) {
        this.mencion = mencion;
    }

    /**
     * Method description
     *
     * @return
     */
    public Character getPlaVigente() {
        return this.plaVigente;
    }

    /**
     * Method description
     *
     * @param plaVigente
     */
    public void setPlaVigente(Character plaVigente) {
        this.plaVigente = plaVigente;
    }
    
    /**
     * Method description
     *
     * @return
     */
    public String getPlaResoluciones() {
        return plaResoluciones;
    }

    /**
     * Method description
     *
     * @param plaResoluciones
     */
    public void setPlaResoluciones(String plaResoluciones) {
        this.plaResoluciones = plaResoluciones;
    }

    public PlanLogro getPlanLogro() {
        return planLogro;
    }

    public void setPlanLogro(PlanLogro planLogro) {
        this.planLogro = planLogro;
    }
    
    

    /**
     * BUSINESS LOGIC
     *
     * @return
     */
    public String getNombreCarreraFull() {
        return this.mencion.getNombreCarreraFull();
    }
}
