/*
 * @(#)PlanId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * PlanId generated by hbm2java
 */
public class PlanId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer plaCod;
    private Integer plaCodCar;
    private Integer plaCodMen;

    /**
     *
     */
    public PlanId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPlaCodCar() {
        return this.plaCodCar;
    }

    /**
     * Method description
     *
     * @param plaCodCar
     */
    public void setPlaCodCar(Integer plaCodCar) {
        this.plaCodCar = plaCodCar;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getPlaCodMen() {
        return plaCodMen;
    }

    /**
     * Method description
     *
     *
     * @param plaCodMen
     */
    public void setPlaCodMen(Integer plaCodMen) {
        this.plaCodMen = plaCodMen;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPlaCod() {
        return this.plaCod;
    }

    /**
     * Method description
     *
     * @param plaCod
     */
    public void setPlaCod(Integer plaCod) {
        this.plaCod = plaCod;
    }    
}
