/*
 * @(#)Practica.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;


import java.io.Serializable;
import java.util.Date;

//Generated 03-05-2011 07:44:47 PM by Hibernate Tools 3.2.1.GA

/**
 * Practica generated by hbm2java
 */
public class Practica implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private Asignatura asignatura;
    private Date praFechaInicio;
    private Date praFechaTermino;
    private PracticaId id;
    private Empleador empleador;
    private String praTelefonoEmp;
    private String praLabor;
    private Comuna comuna;
    private String praDireccion;
    private Persona autoriza;
    private String praTelefonoAut;
    private String praCalidadAut;
    private String praEstado;
    private Solicitud solicitud;
    private String praEmail;

    /**
     *
     */
    public Practica() {
    }

    public AluCar getAluCar() {
        return aluCar;
    }

    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    public Asignatura getAsignatura() {
        return asignatura;
    }

    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }

    public Date getPraFechaInicio() {
        return praFechaInicio;
    }

    public void setPraFechaInicio(Date praFechaInicio) {
        this.praFechaInicio = praFechaInicio;
    }

    public Date getPraFechaTermino() {
        return praFechaTermino;
    }

    public void setPraFechaTermino(Date praFechaTermino) {
        this.praFechaTermino = praFechaTermino;
    }

    public PracticaId getId() {
        return id;
    }

    public void setId(PracticaId id) {
        this.id = id;
    }

    public Empleador getEmpleador() {
        return empleador;
    }

    public void setEmpleador(Empleador empleador) {
        this.empleador = empleador;
    }

    public String getPraTelefonoEmp() {
        return praTelefonoEmp;
    }

    public void setPraTelefonoEmp(String praTelefonoEmp) {
        this.praTelefonoEmp = praTelefonoEmp;
    }

    public String getPraLabor() {
        return praLabor;
    }

    public void setPraLabor(String praLabor) {
        this.praLabor = praLabor;
    }

    public Comuna getComuna() {
        return comuna;
    }

    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }

    public String getPraDireccion() {
        return praDireccion;
    }

    public void setPraDireccion(String praDireccion) {
        this.praDireccion = praDireccion;
    }

    public Persona getAutoriza() {
        return autoriza;
    }

    public void setAutoriza(Persona autoriza) {
        this.autoriza = autoriza;
    }

    public String getPraTelefonoAut() {
        return praTelefonoAut;
    }

    public void setPraTelefonoAut(String praTelefonoAut) {
        this.praTelefonoAut = praTelefonoAut;
    }

    public String getPraCalidadAut() {
        return praCalidadAut;
    }

    public void setPraCalidadAut(String praCalidadAut) {
        this.praCalidadAut = praCalidadAut;
    }

    public String getPraEstado() {
        return praEstado;
    }

    public void setPraEstado(String praEstado) {
        this.praEstado = praEstado;
    }

    public Solicitud getSolicitud() {
        return solicitud;
    }

    public void setSolicitud(Solicitud solicitud) {
        this.solicitud = solicitud;
    }

    public String getPraEmail() {
        return praEmail;
    }

    public void setPraEmail(String praEmail) {
        this.praEmail = praEmail;
    }
}
