/*
 * @(#)PregEncta.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * PregEncta generated by hbm2java
 */
public class PregEncta implements Serializable {

    private static final long serialVersionUID = 1L;
    private EncuestaDocente encuestaDocente;
    private PregEnctaId id;
    private String pregDes;
    private Integer pregNroItems;
    private String pregPrefijo;
    private String pregSufijo;

    /**
     *
     */
    public PregEncta() {
    }

    /**
     * Method description
     *
     * @return
     */
    public PregEnctaId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(PregEnctaId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public EncuestaDocente getEncuestaDocente() {
        return encuestaDocente;
    }

    /**
     *
     * @param encuestaDocente
     */
    public void setEncuestaDocente(EncuestaDocente encuestaDocente) {
        this.encuestaDocente = encuestaDocente;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getPregDes() {
        return this.pregDes;
    }

    /**
     * Method description
     *
     * @param pregDes
     */
    public void setPregDes(String pregDes) {
        this.pregDes = pregDes;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getPregPrefijo() {
        return this.pregPrefijo;
    }

    /**
     * Method description
     *
     * @param pregPrefijo
     */
    public void setPregPrefijo(String pregPrefijo) {
        this.pregPrefijo = pregPrefijo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getPregSufijo() {
        return this.pregSufijo;
    }

    /**
     * Method description
     *
     * @param pregSufijo
     */
    public void setPregSufijo(String pregSufijo) {
        this.pregSufijo = pregSufijo;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPregNroItems() {
        return this.pregNroItems;
    }

    /**
     * Method description
     *
     * @param pregNroItems
     */
    public void setPregNroItems(Integer pregNroItems) {
        this.pregNroItems = pregNroItems;
    }
}
