/*
 * @(#)PregEncta.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * PregEncta generated by hbm2java
 */
public class PreguntaAutoEvaluacion implements Serializable {

    private static final long serialVersionUID = 1L;
    private EncuestaDocente encuestaDocente;
    private PreguntaAutoEvaluacionId id;
    private String padDes;

    /**
     *
     */
    public PreguntaAutoEvaluacion() {
    }

    public EncuestaDocente getEncuestaDocente() {
        return encuestaDocente;
    }

    public void setEncuestaDocente(EncuestaDocente encuestaDocente) {
        this.encuestaDocente = encuestaDocente;
    }

    public PreguntaAutoEvaluacionId getId() {
        return id;
    }

    public void setId(PreguntaAutoEvaluacionId id) {
        this.id = id;
    }

    public String getPadDes() {
        return padDes;
    }

    public void setPadDes(String padDes) {
        this.padDes = padDes;
    }
}
