/*
 * @(#)PregEnctaId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * PregEnctaId generated by hbm2java
 */
public class PregEnctaId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer pregEnc;
    private Integer pregNro;

    /**
     *
     */
    public PregEnctaId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPregEnc() {
        return this.pregEnc;
    }

    /**
     * Method description
     *
     * @param pregEnc
     */
    public void setPregEnc(Integer pregEnc) {
        this.pregEnc = pregEnc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPregNro() {
        return this.pregNro;
    }

    /**
     * Method description
     *
     * @param pregNro
     */
    public void setPregNro(Integer pregNro) {
        this.pregNro = pregNro;
    }
}
