/*
 * @(#)PrerequisitoElectivoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * PrerequisitoElectivoId generated by hbm2java
 */
public class PrerequisitoElectivoId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer preeAgno;
    private Integer preeAsign;
    private Integer preeAsignPre;
    private String preeElect;
    private Integer preeSem;

    /**
     *
     */
    public PrerequisitoElectivoId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPreeAsign() {
        return this.preeAsign;
    }

    /**
     * Method description
     *
     * @param preeAsign
     */
    public void setPreeAsign(Integer preeAsign) {
        this.preeAsign = preeAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getPreeElect() {
        return this.preeElect;
    }

    /**
     * Method description
     *
     * @param preeElect
     */
    public void setPreeElect(String preeElect) {
        this.preeElect = preeElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPreeAgno() {
        return this.preeAgno;
    }

    /**
     * Method description
     *
     * @param preeAgno
     */
    public void setPreeAgno(Integer preeAgno) {
        this.preeAgno = preeAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPreeSem() {
        return this.preeSem;
    }

    /**
     * Method description
     *
     * @param preeSem
     */
    public void setPreeSem(Integer preeSem) {
        this.preeSem = preeSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getPreeAsignPre() {
        return this.preeAsignPre;
    }

    /**
     * Method description
     *
     * @param preeAsignPre
     */
    public void setPreeAsignPre(Integer preeAsignPre) {
        this.preeAsignPre = preeAsignPre;
    }
}
