/*
 * @(#)ProcedenciaCalificacion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 13-09-2010 05:58:20 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ProcedenciaCalificacion generated by hbm2java
 */
public class ProcedenciaCalificacion implements Serializable {
    private static final long serialVersionUID = 1L;

    private String procCod;
    private String procDes;

    /**
     *
     */
    public ProcedenciaCalificacion() {
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProcCod() {
        return this.procCod;
    }

    /**
     * Method description
     *
     * @param procCod
     */
    public void setProcCod(String procCod) {
        this.procCod = procCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProcDes() {
        return this.procDes;
    }

    /**
     * Method description
     *
     * @param procDes
     */
    public void setProcDes(String procDes) {
        this.procDes = procDes;
    }
}
