/*
 * @(#)ProcesoInscripcion.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ViaIngreso generated by hbm2java
 */
public class ProcesoInscripcion implements Serializable {

    private static final long serialVersionUID = 1L;
    private String pinsCod;
    private String pinsDes;

    /**
     *
     */
    public ProcesoInscripcion() {
    }

    public String getPinsCod() {
        return pinsCod;
    }

    public void setPinsCod(String pinsCod) {
        this.pinsCod = pinsCod;
    }

    public String getPinsDes() {
        return pinsDes;
    }

    public void setPinsDes(String pinsDes) {
        this.pinsDes = pinsDes;
    }
}
