/*
 * @(#)Profesor.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import infrastructure.util.ActionUtil;
import infrastructure.util.ContextUtil;
import static infrastructure.util.DateUtil.getDateGetterSetter;
import infrastructure.util.common.CommonUsersUtil;
import infrastructure.util.common.CommonUtil;
import java.util.stream.Collectors;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
/**
 * Profesor generated by hbm2java
 */
public class Profesor implements Serializable {

    private static final long serialVersionUID = 1L;
    private Set<CursoProfesor> cursos = new HashSet<>(0);
    private List<Curso> carga;
    private List<Curso> cargaHistorica;
    private Comuna comuna;    
    private String profDireccion;
    private String profDv;
    private String profEmail;
    private Date profFechaNac;
    private String profFono;
    private Date profLastLogin;
    private String profMat;
    private String profNom;
    private String profNombreSimple;
    private String profPat;
    private Integer profRut;
    private String profSexo;
    private Date profUpdated;

    /**
     *
     */
    public Profesor() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getProfRut() {
        return this.profRut;
    }

    /**
     * Method description
     *
     * @param profRut
     */
    public void setProfRut(Integer profRut) {
        this.profRut = profRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfNom() {
        return this.profNom;
    }

    /**
     * Method description
     *
     * @param profNom
     */
    public void setProfNom(String profNom) {
        this.profNom = profNom;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfPat() {
        return this.profPat;
    }

    /**
     * Method description
     *
     * @param profPat
     */
    public void setProfPat(String profPat) {
        this.profPat = profPat;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfMat() {
        return this.profMat;
    }

    /**
     * Method description
     *
     * @param profMat
     */
    public void setProfMat(String profMat) {
        this.profMat = profMat;
    }

    /**
     * Method description
     *
     * @return
     */
    public Set<CursoProfesor> getCursos() {
        return this.cursos;
    }

    /**
     * Method description
     *
     * @param cursos
     */
    public void setCursos(Set<CursoProfesor> cursos) {
        this.cursos = cursos;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfDv() {
        return profDv;
    }

    /**
     * Method description
     *
     * @param profDv
     */
    public void setProfDv(String profDv) {
        this.profDv = profDv;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfEmail() {
        return profEmail;
    }

    /**
     * Method description
     *
     * @param profEmail
     */
    public void setProfEmail(String profEmail) {
        this.profEmail = profEmail;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getProfLastLogin() {
        return getDateGetterSetter(profLastLogin);
    }

    /**
     * Method description
     *
     * @param profLastLogin
     */
    public void setProfLastLogin(Date profLastLogin) {
        this.profLastLogin = getDateGetterSetter(profLastLogin);
    }

    /**
     * Method description
     *
     * @return
     */
    public List<Curso> getCarga() {
        return this.carga;
    }    

    /**
     * Method description
     */
    public void setCarga() {
        this.carga = ContextUtil.getDAO().getProfesorRepository(ActionUtil.getDBUser()).findCargaAcademica(this.profRut);
    }

    /**
     * Method description
     *
     * @return
     */
    public List<Curso> getCargaHistorica() {
        return this.cargaHistorica;
    }

    /**
     * Method description
     */
    public void setCargaHistorica() {
        this.cargaHistorica = ContextUtil.getDAO().getProfesorRepository(ActionUtil.getDBUser()).findCargaHistorica(this.profRut);
    }

    /**
     * Method description
     *
     * @param lista
     */
    public void setCargaHistorica(List<Curso> lista) {
        this.cargaHistorica = lista;
    }

    /**
     * Method description
     *
     * @return
     */
    public Comuna getComuna() {
        return comuna;
    }

    /**
     * Method description
     *
     * @param comuna
     */
    public void setComuna(Comuna comuna) {
        this.comuna = comuna;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfDireccion() {
        return profDireccion;
    }

    /**
     * Method description
     *
     * @param profDireccion
     */
    public void setProfDireccion(String profDireccion) {
        this.profDireccion = profDireccion;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getProfFechaNac() {
        return getDateGetterSetter(profFechaNac);
    }

    /**
     * Method description
     *
     * @param profFechaNac
     */
    public void setProfFechaNac(Date profFechaNac) {
        this.profFechaNac = getDateGetterSetter(profFechaNac);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfFono() {
        return profFono;
    }

    /**
     * Method description
     *
     * @param profFono
     */
    public void setProfFono(String profFono) {
        this.profFono = profFono;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfSexo() {
        return profSexo;
    }

    /**
     * Method description
     *
     * @param profSexo
     */
    public void setProfSexo(String profSexo) {
        this.profSexo = profSexo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getProfNombreSimple() {
        return profNombreSimple;
    }

    /**
     * Method description
     *
     * @param profNombreSimple
     */
    public void setProfNombreSimple(String profNombreSimple) {
        this.profNombreSimple = profNombreSimple;
    }

    /**
     * BUSINESS LOGIC
     *
     * @return
     */
    public String getNombre() {
        return CommonUsersUtil.getNombre(this.profPat, this.profMat, this.profNom);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreStd() {
        return CommonUsersUtil.getNombreStd(this.profPat, this.profMat, this.profNom);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getNombreMensaje() {
        return CommonUsersUtil.getNombreMensaje(this.profPat, this.profMat, this.profNom);
    }

    public Date getProfUpdated() {
        return profUpdated;
    }

    public void setProfUpdated(Date profUpdated) {
        this.profUpdated = profUpdated;
    }    
    
    public String getEmailUsach(){
        return CommonUtil.getEmailUsach(profEmail);
    }
    
    public String getEmailNoUsach()
    {      
        List<String> emailList = Arrays.asList(profEmail.split(","));

        List<String> lRet =  emailList.stream()
                        .filter(email -> !email.contains("usach.cl"))
                        .collect(Collectors.toList());
        
        return lRet.stream().collect(Collectors.joining(","));
    }
}
