/*
 * @(#)ReporteClase.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * ReporteClase generated by hbm2java
 */
public class ReporteClase implements Serializable {

    private static final long serialVersionUID = 1L;
    private Curso curso;
    private ReporteClaseId id;
    private String rclaAttach;
    private String rclaContenido;
    private Date rclaFecGen;
    private Date rclaFecRecupera;
    private String rclaMetodo;
    private String rclaObApren;
    private String rclaObs;
    private Integer rclaSesion;

    /**
     *
     */
    public ReporteClase() {
    }

    /**
     * Method description
     *
     * @return
     */
    public ReporteClaseId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(ReporteClaseId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getRclaFecGen() {
        return getDateGetterSetter(rclaFecGen);
    }

    /**
     * Method description
     *
     * @param rclaFecGen
     */
    public void setRclaFecGen(Date rclaFecGen) {
        this.rclaFecGen = getDateGetterSetter(rclaFecGen);
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRclaObApren() {
        return this.rclaObApren;
    }

    /**
     * Method description
     *
     * @param rclaObApren
     */
    public void setRclaObApren(String rclaObApren) {
        this.rclaObApren = rclaObApren;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRclaContenido() {
        return this.rclaContenido;
    }

    /**
     * Method description
     *
     * @param rclaContenido
     */
    public void setRclaContenido(String rclaContenido) {
        this.rclaContenido = rclaContenido;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRclaMetodo() {
        return this.rclaMetodo;
    }

    /**
     * Method description
     *
     * @param rclaMetodo
     */
    public void setRclaMetodo(String rclaMetodo) {
        this.rclaMetodo = rclaMetodo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRclaObs() {
        return this.rclaObs;
    }

    /**
     * Method description
     *
     * @param rclaObs
     */
    public void setRclaObs(String rclaObs) {
        this.rclaObs = rclaObs;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRclaSesion() {
        return this.rclaSesion;
    }

    /**
     * Method description
     *
     * @param rclaSesion
     */
    public void setRclaSesion(Integer rclaSesion) {
        this.rclaSesion = rclaSesion;
    }

    /**
     * Method description
     *
     * @return
     */
    public Curso getCurso() {
        return curso;
    }

    /**
     * Method description
     *
     * @param curso
     */
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRclaAttach() {
        return rclaAttach;
    }

    /**
     * Method description
     *
     * @param rclaAttach
     */
    public void setRclaAttach(String rclaAttach) {
        this.rclaAttach = rclaAttach;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getRclaFecRecupera() {
        return getDateGetterSetter(rclaFecRecupera);
    }

    /**
     * Method description
     *
     * @param rclaFecRecupera
     */
    public void setRclaFecRecupera(Date rclaFecRecupera) {
        this.rclaFecRecupera = getDateGetterSetter(rclaFecRecupera);
    }
}
