/*
 * @(#)ReporteClaseId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * ReporteClaseId generated by hbm2java
 */
public class ReporteClaseId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer rclaAgno;
    private Integer rclaAsign;
    private String rclaCoord;
    private String rclaDia;
    private String rclaElect;
    private Date rclaFecClase;
    private Integer rclaModulo;
    private Integer rclaSecc;
    private Integer rclaSem;
    private String rclaComp;

    /**
     *
     */
    public ReporteClaseId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRclaAsign() {
        return this.rclaAsign;
    }

    /**
     * Method description
     *
     * @param rclaAsign
     */
    public void setRclaAsign(Integer rclaAsign) {
        this.rclaAsign = rclaAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRclaElect() {
        return this.rclaElect;
    }

    /**
     * Method description
     *
     * @param rclaElect
     */
    public void setRclaElect(String rclaElect) {
        this.rclaElect = rclaElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRclaCoord() {
        return this.rclaCoord;
    }

    /**
     * Method description
     *
     * @param rclaCoord
     */
    public void setRclaCoord(String rclaCoord) {
        this.rclaCoord = rclaCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRclaSecc() {
        return this.rclaSecc;
    }

    /**
     * Method description
     *
     * @param rclaSecc
     */
    public void setRclaSecc(Integer rclaSecc) {
        this.rclaSecc = rclaSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRclaAgno() {
        return this.rclaAgno;
    }

    /**
     * Method description
     *
     * @param rclaAgno
     */
    public void setRclaAgno(Integer rclaAgno) {
        this.rclaAgno = rclaAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRclaSem() {
        return this.rclaSem;
    }

    /**
     * Method description
     *
     * @param rclaSem
     */
    public void setRclaSem(Integer rclaSem) {
        this.rclaSem = rclaSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRclaDia() {
        return this.rclaDia;
    }

    /**
     * Method description
     *
     * @param rclaDia
     */
    public void setRclaDia(String rclaDia) {
        this.rclaDia = rclaDia;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRclaModulo() {
        return this.rclaModulo;
    }

    /**
     * Method description
     *
     * @param rclaModulo
     */
    public void setRclaModulo(Integer rclaModulo) {
        this.rclaModulo = rclaModulo;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getRclaFecClase() {
        return getDateGetterSetter(rclaFecClase);
    }

    /**
     * Method description
     *
     * @param rclaFecClase
     */
    public void setRclaFecClase(Date rclaFecClase) {
        this.rclaFecClase = getDateGetterSetter(rclaFecClase);
    }

    public String getRclaComp() {
        return rclaComp;
    }

    public void setRclaComp(String rclaComp) {
        this.rclaComp = rclaComp;
    }
}
