/*
 * @(#)RequisitoLogroAdicional.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RequisitoLogroAdicional generated by hbm2java
 */
public class RequisitoLogroAdicional implements Serializable {

    private static final long serialVersionUID = 1L;
    private RequisitoLogroAdicionalId id;
    private PlanLogro planLogro;
    private Integer rlaHorasCred;
    private Integer rlaOrder;
    private Integer rlaTipoOpc;
    private TrequisitoLogroAdicional trequisitoLogroAdicional;

    /**
     *
     */
    public RequisitoLogroAdicional() {
    }

    /**
     * Method description
     *
     * @return
     */
    public RequisitoLogroAdicionalId getId() {
        return id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(RequisitoLogroAdicionalId id) {
        this.id = id;
    }

    public PlanLogro getPlanLogro() {
        return planLogro;
    }

    public void setPlanLogro(PlanLogro planLogro) {
        this.planLogro = planLogro;
    }
    
    public Integer getRlaHorasCred() {
        return rlaHorasCred;
    }

    public void setRlaHorasCred(Integer rlaHorasCred) {
        this.rlaHorasCred = rlaHorasCred;
    }

    public Integer getRlaOrder() {
        return rlaOrder;
    }

    public void setRlaOrder(Integer rlaOrder) {
        this.rlaOrder = rlaOrder;
    }

    public Integer getRlaTipoOpc() {
        return rlaTipoOpc;
    }

    public void setRlaTipoOpc(Integer rlaTipoOpc) {
        this.rlaTipoOpc = rlaTipoOpc;
    }
   
    public TrequisitoLogroAdicional getTrequisitoLogroAdicional() {
        return trequisitoLogroAdicional;
    }

    public void setTrequisitoLogroAdicional(TrequisitoLogroAdicional trequisitoLogroAdicional) {
        this.trequisitoLogroAdicional = trequisitoLogroAdicional;
    }
}
