/*
 * @(#)RequisitoLogroAdicionalId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RequisitoLogroAdicionalId generated by hbm2java
 */
public class RequisitoLogroAdicionalId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer rlaCodCar;
    private Integer rlaCodMen;
    private Integer rlaCodPlan;
    private Integer rlaCorrel;
    private Integer rlaReq;

    /**
     *
     */
    public RequisitoLogroAdicionalId() {
    }

    public Integer getRlaCodCar() {
        return rlaCodCar;
    }

    public void setRlaCodCar(Integer rlaCodCar) {
        this.rlaCodCar = rlaCodCar;
    }

    public Integer getRlaCodMen() {
        return rlaCodMen;
    }

    public void setRlaCodMen(Integer rlaCodMen) {
        this.rlaCodMen = rlaCodMen;
    }

    public Integer getRlaCodPlan() {
        return rlaCodPlan;
    }

    public void setRlaCodPlan(Integer rlaCodPlan) {
        this.rlaCodPlan = rlaCodPlan;
    }

    public Integer getRlaCorrel() {
        return rlaCorrel;
    }

    public void setRlaCorrel(Integer rlaCorrel) {
        this.rlaCorrel = rlaCorrel;
    }

    public Integer getRlaReq() {
        return rlaReq;
    }

    public void setRlaReq(Integer rlaReq) {
        this.rlaReq = rlaReq;
    }
}
