/*
 * @(#)RespuestaAutoEvaluacionAcademicoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RespEnctaId generated by hbm2java
 */
public class RespuestaAutoEvaluacionAcademicoId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer raaAgno;
    private Integer raaAsign;
    private String raaCoord;
    private String raaElect;
    private Integer raaEnc;
    private Integer raaPreg;
    private Integer raaResp;
    private Integer raaRut;
    private Integer raaSecc;
    private Integer raaSem;
    private String raaComp;

    /**
     *
     */
    public RespuestaAutoEvaluacionAcademicoId() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRaaAgno() {
        return raaAgno;
    }

    /**
     * Method description
     *
     *
     * @param raaAgno
     */
    public void setRaaAgno(Integer raaAgno) {
        this.raaAgno = raaAgno;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRaaAsign() {
        return raaAsign;
    }

    /**
     * Method description
     *
     *
     * @param raaAsign
     */
    public void setRaaAsign(Integer raaAsign) {
        this.raaAsign = raaAsign;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getRaaCoord() {
        return raaCoord;
    }

    /**
     * Method description
     *
     *
     * @param raaCoord
     */
    public void setRaaCoord(String raaCoord) {
        this.raaCoord = raaCoord;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getRaaElect() {
        return raaElect;
    }

    /**
     * Method description
     *
     *
     * @param raaElect
     */
    public void setRaaElect(String raaElect) {
        this.raaElect = raaElect;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRaaEnc() {
        return raaEnc;
    }

    /**
     * Method description
     *
     *
     * @param raaEnc
     */
    public void setRaaEnc(Integer raaEnc) {
        this.raaEnc = raaEnc;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRaaPreg() {
        return raaPreg;
    }

    /**
     * Method description
     *
     *
     * @param raaPreg
     */
    public void setRaaPreg(Integer raaPreg) {
        this.raaPreg = raaPreg;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRaaResp() {
        return raaResp;
    }

    /**
     * Method description
     *
     *
     * @param raaResp
     */
    public void setRaaResp(Integer raaResp) {
        this.raaResp = raaResp;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRaaRut() {
        return raaRut;
    }

    /**
     * Method description
     *
     *
     * @param raaRut
     */
    public void setRaaRut(Integer raaRut) {
        this.raaRut = raaRut;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRaaSecc() {
        return raaSecc;
    }

    /**
     * Method description
     *
     *
     * @param raaSecc
     */
    public void setRaaSecc(Integer raaSecc) {
        this.raaSecc = raaSecc;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRaaSem() {
        return raaSem;
    }

    /**
     * Method description
     *
     *
     * @param raaSem
     */
    public void setRaaSem(Integer raaSem) {
        this.raaSem = raaSem;
    }

    public String getRaaComp() {
        return raaComp;
    }

    public void setRaaComp(String raaComp) {
        this.raaComp = raaComp;
    }    
}
