/*
 * @(#)RespEnctaHistId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RespEnctaHistId generated by hbm2java
 */
public class RespEnctaHistId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer respAgno;
    private Integer respAsign;
    private String respCoord;
    private String respElect;
    private Integer respEnc;
    private Integer respPreg;
    private Integer respResp;
    private Integer respSecc;
    private Integer respSem;

    /**
     *
     */
    public RespEnctaHistId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRespEnc() {
        return this.respEnc;
    }

    /**
     * Method description
     *
     * @param respEnc
     */
    public void setRespEnc(Integer respEnc) {
        this.respEnc = respEnc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRespAgno() {
        return this.respAgno;
    }

    /**
     * Method description
     *
     * @param respAgno
     */
    public void setRespAgno(Integer respAgno) {
        this.respAgno = respAgno;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRespSem() {
        return this.respSem;
    }

    /**
     * Method description
     *
     * @param respSem
     */
    public void setRespSem(Integer respSem) {
        this.respSem = respSem;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRespAsign() {
        return this.respAsign;
    }

    /**
     * Method description
     *
     * @param respAsign
     */
    public void setRespAsign(Integer respAsign) {
        this.respAsign = respAsign;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRespElect() {
        return this.respElect;
    }

    /**
     * Method description
     *
     * @param respElect
     */
    public void setRespElect(String respElect) {
        this.respElect = respElect;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getRespCoord() {
        return this.respCoord;
    }

    /**
     * Method description
     *
     * @param respCoord
     */
    public void setRespCoord(String respCoord) {
        this.respCoord = respCoord;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRespSecc() {
        return this.respSecc;
    }

    /**
     * Method description
     *
     * @param respSecc
     */
    public void setRespSecc(Integer respSecc) {
        this.respSecc = respSecc;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRespPreg() {
        return this.respPreg;
    }

    /**
     * Method description
     *
     * @param respPreg
     */
    public void setRespPreg(Integer respPreg) {
        this.respPreg = respPreg;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getRespResp() {
        return this.respResp;
    }

    /**
     * Method description
     *
     * @param respResp
     */
    public void setRespResp(Integer respResp) {
        this.respResp = respResp;
    }
}
