/*
 * @(#)RespuestaEncuestaAyudanteId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RespEnctaId generated by hbm2java
 */
public class RespuestaEncuestaAyudanteId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer reaAgno;
    private Integer reaAgnoIng;
    private Integer reaAsign;
    private Integer reaCodCar;
    private String reaCoord;
    private String reaElect;
    private Integer reaEnc;
    private Integer reaPreg;
    private Integer reaResp;
    private Integer reaRut;
    private Integer reaRutAyu;
    private Integer reaSecc;
    private Integer reaSem;
    private Integer reaSemIng;
    private String reaComp;

    /**
     *
     */
    public RespuestaEncuestaAyudanteId() {
    }

    /**
     *
     * @return
     */
    public Integer getReaAgno() {
        return reaAgno;
    }

    /**
     *
     * @param reaAgno
     */
    public void setReaAgno(Integer reaAgno) {
        this.reaAgno = reaAgno;
    }

    /**
     *
     * @return
     */
    public Integer getReaAgnoIng() {
        return reaAgnoIng;
    }

    /**
     *
     * @param reaAgnoIng
     */
    public void setReaAgnoIng(Integer reaAgnoIng) {
        this.reaAgnoIng = reaAgnoIng;
    }

    /**
     *
     * @return
     */
    public Integer getReaAsign() {
        return reaAsign;
    }

    /**
     *
     * @param reaAsign
     */
    public void setReaAsign(Integer reaAsign) {
        this.reaAsign = reaAsign;
    }

    /**
     *
     * @return
     */
    public Integer getReaCodCar() {
        return reaCodCar;
    }

    /**
     *
     * @param reaCodCar
     */
    public void setReaCodCar(Integer reaCodCar) {
        this.reaCodCar = reaCodCar;
    }

    /**
     *
     * @return
     */
    public String getReaCoord() {
        return reaCoord;
    }

    /**
     *
     * @param reaCoord
     */
    public void setReaCoord(String reaCoord) {
        this.reaCoord = reaCoord;
    }

    /**
     *
     * @return
     */
    public String getReaElect() {
        return reaElect;
    }

    /**
     *
     * @param reaElect
     */
    public void setReaElect(String reaElect) {
        this.reaElect = reaElect;
    }

    /**
     *
     * @return
     */
    public Integer getReaEnc() {
        return reaEnc;
    }

    /**
     *
     * @param reaEnc
     */
    public void setReaEnc(Integer reaEnc) {
        this.reaEnc = reaEnc;
    }

    /**
     *
     * @return
     */
    public Integer getReaPreg() {
        return reaPreg;
    }

    /**
     *
     * @param reaPreg
     */
    public void setReaPreg(Integer reaPreg) {
        this.reaPreg = reaPreg;
    }

    /**
     *
     * @return
     */
    public Integer getReaResp() {
        return reaResp;
    }

    /**
     *
     * @param reaResp
     */
    public void setReaResp(Integer reaResp) {
        this.reaResp = reaResp;
    }

    /**
     *
     * @return
     */
    public Integer getReaRut() {
        return reaRut;
    }

    /**
     *
     * @param reaRut
     */
    public void setReaRut(Integer reaRut) {
        this.reaRut = reaRut;
    }

    /**
     *
     * @return
     */
    public Integer getReaRutAyu() {
        return reaRutAyu;
    }

    /**
     *
     * @param reaRutAyu
     */
    public void setReaRutAyu(Integer reaRutAyu) {
        this.reaRutAyu = reaRutAyu;
    }

    /**
     *
     * @return
     */
    public Integer getReaSecc() {
        return reaSecc;
    }

    /**
     *
     * @param reaSecc
     */
    public void setReaSecc(Integer reaSecc) {
        this.reaSecc = reaSecc;
    }

    /**
     *
     * @return
     */
    public Integer getReaSem() {
        return reaSem;
    }

    /**
     *
     * @param reaSem
     */
    public void setReaSem(Integer reaSem) {
        this.reaSem = reaSem;
    }

    /**
     *
     * @return
     */
    public Integer getReaSemIng() {
        return reaSemIng;
    }

    /**
     *
     * @param reaSemIng
     */
    public void setReaSemIng(Integer reaSemIng) {
        this.reaSemIng = reaSemIng;
    }

    public String getReaComp() {
        return reaComp;
    }

    public void setReaComp(String reaComp) {
        this.reaComp = reaComp;
    }
}
