/*
 * @(#)RespuestaEncuestaDocenteId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RespEnctaId generated by hbm2java
 */
public class RespuestaEncuestaDocenteId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer redAgno;
    private Integer redAgnoIng;
    private Integer redAsign;
    private Integer redCodCar;
    private String redCoord;
    private String redElect;
    private Integer redEnc;
    private Integer redPreg;
    private Integer redResp;
    private Integer redRut;
    private Integer redRutProf;
    private Integer redSecc;
    private Integer redSem;
    private Integer redSemIng;
    private Integer redApartado;
    private String redComp;

    /**
     *
     */
    public RespuestaEncuestaDocenteId() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedAgno() {
        return redAgno;
    }

    /**
     * Method description
     *
     *
     * @param redAgno
     */
    public void setRedAgno(Integer redAgno) {
        this.redAgno = redAgno;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedAgnoIng() {
        return redAgnoIng;
    }

    /**
     * Method description
     *
     *
     * @param redAgnoIng
     */
    public void setRedAgnoIng(Integer redAgnoIng) {
        this.redAgnoIng = redAgnoIng;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedAsign() {
        return redAsign;
    }

    /**
     * Method description
     *
     *
     * @param redAsign
     */
    public void setRedAsign(Integer redAsign) {
        this.redAsign = redAsign;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedCodCar() {
        return redCodCar;
    }

    /**
     * Method description
     *
     *
     * @param redCodCar
     */
    public void setRedCodCar(Integer redCodCar) {
        this.redCodCar = redCodCar;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getRedCoord() {
        return redCoord;
    }

    /**
     * Method description
     *
     *
     * @param redCoord
     */
    public void setRedCoord(String redCoord) {
        this.redCoord = redCoord;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getRedElect() {
        return redElect;
    }

    /**
     * Method description
     *
     *
     * @param redElect
     */
    public void setRedElect(String redElect) {
        this.redElect = redElect;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedEnc() {
        return redEnc;
    }

    /**
     * Method description
     *
     *
     * @param redEnc
     */
    public void setRedEnc(Integer redEnc) {
        this.redEnc = redEnc;
    }


    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedPreg() {
        return redPreg;
    }

    /**
     * Method description
     *
     *
     * @param redPreg
     */
    public void setRedPreg(Integer redPreg) {
        this.redPreg = redPreg;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedResp() {
        return redResp;
    }

    /**
     * Method description
     *
     *
     * @param redResp
     */
    public void setRedResp(Integer redResp) {
        this.redResp = redResp;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedRut() {
        return redRut;
    }

    /**
     * Method description
     *
     *
     * @param redRut
     */
    public void setRedRut(Integer redRut) {
        this.redRut = redRut;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedSecc() {
        return redSecc;
    }

    /**
     * Method description
     *
     *
     * @param redSecc
     */
    public void setRedSecc(Integer redSecc) {
        this.redSecc = redSecc;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedSem() {
        return redSem;
    }

    /**
     * Method description
     *
     *
     * @param redSem
     */
    public void setRedSem(Integer redSem) {
        this.redSem = redSem;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedSemIng() {
        return redSemIng;
    }

    /**
     * Method description
     *
     *
     * @param redSemIng
     */
    public void setRedSemIng(Integer redSemIng) {
        this.redSemIng = redSemIng;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getRedRutProf() {
        return redRutProf;
    }

    /**
     * Method description
     *
     *
     * @param redRutProf
     */
    public void setRedRutProf(Integer redRutProf) {
        this.redRutProf = redRutProf;
    }

    public Integer getRedApartado() {
        return redApartado;
    }

    public void setRedApartado(Integer redApartado) {
        this.redApartado = redApartado;
    }  

    public String getRedComp() {
        return redComp;
    }

    public void setRedComp(String redComp) {
        this.redComp = redComp;
    }
}
