/*
 * @(#)RespuestaEncuestaDocente.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RespEncta generated by hbm2java
 */
public class RespuestaEncuestaDocente implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private CursoProfesor cursoProfesor;
    private RespuestaEncuestaDocenteId id;
    private Integer redCorrel;

    /**
     *
     */
    public RespuestaEncuestaDocente() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public AluCar getAluCar() {
        return aluCar;
    }

    /**
     * Method description
     *
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public CursoProfesor getCursoProfesor() {
        return cursoProfesor;
    }

    /**
     * Method description
     *
     *
     * @param cursoProfesor
     */
    public void setCursoProfesor(CursoProfesor cursoProfesor) {
        this.cursoProfesor = cursoProfesor;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public RespuestaEncuestaDocenteId getId() {
        return id;
    }

    /**
     * Method description
     *
     *
     * @param id
     */
    public void setId(RespuestaEncuestaDocenteId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Integer getRedCorrel() {
        return redCorrel;
    }

    /**
     *
     * @param redCorrel
     */
    public void setRedCorrel(Integer redCorrel) {
        this.redCorrel = redCorrel;
    }
}
