/*
 * @(#)RespuestaEncuestaAyudante.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RespEncta generated by hbm2java
 */
public class RespuestaEncuestaAyudante implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private CursoAyudante cursoAyudante;
    private RespuestaEncuestaAyudanteId id;
    private Integer reaCorrel;


    /**
     *
     */
    public RespuestaEncuestaAyudante() {
    }

    /**
     *
     * @return
     */
    public AluCar getAluCar() {
        return aluCar;
    }

    /**
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     *
     * @return
     */
    public CursoAyudante getCursoAyudante() {
        return cursoAyudante;
    }

    /**
     *
     * @param cursoAyudante
     */
    public void setCursoAyudante(CursoAyudante cursoAyudante) {
        this.cursoAyudante = cursoAyudante;
    }

    /**
     *
     * @return
     */
    public RespuestaEncuestaAyudanteId getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(RespuestaEncuestaAyudanteId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Integer getReaCorrel() {
        return reaCorrel;
    }

    /**
     *
     * @param reaCorrel
     */
    public void setReaCorrel(Integer reaCorrel) {
        this.reaCorrel = reaCorrel;
    }

}
