/*
 * @(#)RespuestaAutoEvaluacionAcademico.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RespEncta generated by hbm2java
 */
public class RespuestaAutoEvaluacionAcademico implements Serializable {

    private static final long serialVersionUID = 1L;
    private CursoProfesor cursoProfesor;
    private RespuestaAutoEvaluacionAcademicoId id;
    private Integer raaCorrel;

    /**
     *
     */
    public RespuestaAutoEvaluacionAcademico() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public CursoProfesor getCursoProfesor() {
        return cursoProfesor;
    }

    /**
     * Method description
     *
     *
     * @param cursoProfesor
     */
    public void setCursoProfesor(CursoProfesor cursoProfesor) {
        this.cursoProfesor = cursoProfesor;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public RespuestaAutoEvaluacionAcademicoId getId() {
        return id;
    }

    /**
     * Method description
     *
     *
     * @param id
     */
    public void setId(RespuestaAutoEvaluacionAcademicoId id) {
        this.id = id;
    }

    public Integer getRaaCorrel() {
        return raaCorrel;
    }

    public void setRaaCorrel(Integer raaCorrel) {
        this.raaCorrel = raaCorrel;
    }
}
