/*
 * @(#)RespEnctaHist.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * RespEnctaHist generated by hbm2java
 */
public class RespEnctaHist implements Serializable {

    private static final long serialVersionUID = 1L;
    private RespEnctaHistId id;

    /**
     *
     */
    public RespEnctaHist() {
    }

    /**
     * Method description
     *
     * @return
     */
    public RespEnctaHistId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(RespEnctaHistId id) {
        this.id = id;
    }
}
