/*
 * @(#)Sacarrera.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import static infrastructure.util.DateUtil.getDateGetterSetter;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA

/**
 * Sacarrera generated by hbm2java
 */
public class Sacarrera implements Serializable {

    private static final long serialVersionUID = 1L;
    private AluCar aluCar;
    private SacarreraId id;
    private Integer sacAgnoInic;
    private Integer sacAgnoTerm;
    private Integer sacDocAcep;
    private Integer sacDocPres;
    private Integer sacDurac;
    private Date sacFecMod;
    private Date sacFechaAcep;
    private Date sacFechaPres;
    private Integer sacSemInic;
    private Integer sacSemTerm;
    private Tsacademica tsacademica;

    /**
     *
     */
    public Sacarrera() {
    }

    /**
     * Method description
     *
     * @return
     */
    public SacarreraId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(SacarreraId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return this.aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public Tsacademica getTsacademica() {
        return this.tsacademica;
    }

    /**
     * Method description
     *
     * @param tsacademica
     */
    public void setTsacademica(Tsacademica tsacademica) {
        this.tsacademica = tsacademica;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacDurac() {
        return this.sacDurac;
    }

    /**
     * Method description
     *
     * @param sacDurac
     */
    public void setSacDurac(Integer sacDurac) {
        this.sacDurac = sacDurac;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacSemInic() {
        return this.sacSemInic;
    }

    /**
     * Method description
     *
     * @param sacSemInic
     */
    public void setSacSemInic(Integer sacSemInic) {
        this.sacSemInic = sacSemInic;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacAgnoInic() {
        return this.sacAgnoInic;
    }

    /**
     * Method description
     *
     * @param sacAgnoInic
     */
    public void setSacAgnoInic(Integer sacAgnoInic) {
        this.sacAgnoInic = sacAgnoInic;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacSemTerm() {
        return this.sacSemTerm;
    }

    /**
     * Method description
     *
     * @param sacSemTerm
     */
    public void setSacSemTerm(Integer sacSemTerm) {
        this.sacSemTerm = sacSemTerm;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacAgnoTerm() {
        return this.sacAgnoTerm;
    }

    /**
     * Method description
     *
     * @param sacAgnoTerm
     */
    public void setSacAgnoTerm(Integer sacAgnoTerm) {
        this.sacAgnoTerm = sacAgnoTerm;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacDocPres() {
        return this.sacDocPres;
    }

    /**
     * Method description
     *
     * @param sacDocPres
     */
    public void setSacDocPres(Integer sacDocPres) {
        this.sacDocPres = sacDocPres;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getSacFechaPres() {
        return getDateGetterSetter(sacFechaPres);
    }

    /**
     * Method description
     *
     * @param sacFechaPres
     */
    public void setSacFechaPres(Date sacFechaPres) {
        this.sacFechaPres = getDateGetterSetter(sacFechaPres);
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getSacFechaAcep() {
        return getDateGetterSetter(sacFechaAcep);
    }

    /**
     * Method description
     *
     * @param sacFechaAcep
     */
    public void setSacFechaAcep(Date sacFechaAcep) {
        this.sacFechaAcep = getDateGetterSetter(sacFechaAcep);
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacDocAcep() {
        return this.sacDocAcep;
    }

    /**
     * Method description
     *
     * @param sacDocAcep
     */
    public void setSacDocAcep(Integer sacDocAcep) {
        this.sacDocAcep = sacDocAcep;
    }

    /**
     * Method description
     *
     * @return a defensive copy of the field. The caller may change the state of
     * the returned object in any way, without affecting the internals of this
     * class.
     */
    public Date getSacFecMod() {
        return getDateGetterSetter(sacFecMod);
    }

    /**
     * Method description
     *
     * @param sacFecMod
     */
    public void setSacFecMod(Date sacFecMod) {
        this.sacFecMod = getDateGetterSetter(sacFecMod);
    }
}
