/*
 * @(#)SacarreraId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * SacarreraId generated by hbm2java
 */
public class SacarreraId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer sacAgnoIng;
    private Integer sacCcarr;
    private Integer sacCorrel;
    private Integer sacRut;
    private Integer sacSemIng;

    /**
     *
     */
    public SacarreraId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacRut() {
        return this.sacRut;
    }

    /**
     * Method description
     *
     * @param sacRut
     */
    public void setSacRut(Integer sacRut) {
        this.sacRut = sacRut;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacCcarr() {
        return this.sacCcarr;
    }

    /**
     * Method description
     *
     * @param sacCcarr
     */
    public void setSacCcarr(Integer sacCcarr) {
        this.sacCcarr = sacCcarr;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacAgnoIng() {
        return this.sacAgnoIng;
    }

    /**
     * Method description
     *
     * @param sacAgnoIng
     */
    public void setSacAgnoIng(Integer sacAgnoIng) {
        this.sacAgnoIng = sacAgnoIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacSemIng() {
        return this.sacSemIng;
    }

    /**
     * Method description
     *
     * @param sacSemIng
     */
    public void setSacSemIng(Integer sacSemIng) {
        this.sacSemIng = sacSemIng;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSacCorrel() {
        return this.sacCorrel;
    }

    /**
     * Method description
     *
     * @param sacCorrel
     */
    public void setSacCorrel(Integer sacCorrel) {
        this.sacCorrel = sacCorrel;
    }
}
