/*
 * @(#)Sala.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.awt.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import static infrastructure.util.common.CommonSalaUtil.getColorPDF;

/**
 * Sala generated by hbm2java
 */
public class Sala implements Serializable {

    private static final long serialVersionUID = 1L;
    private Set<Horario> horarios = new HashSet<>(0);
    private Unidad unidad;
    private Unidad unidadVesp;
    private Integer salaCapacidad;
    private String salaDescrip;
    private String salaNum;

    /**
     *
     */
    public Sala() {
    }

    public Unidad getUnidad() {
        return unidad;
    }

    public void setUnidad(Unidad unidad) {
        this.unidad = unidad;
    }

    public Unidad getUnidadVesp() {
        return unidadVesp;
    }

    public void setUnidadVesp(Unidad unidadVesp) {
        this.unidadVesp = unidadVesp;
    }
    
    
    /**
     * Method description
     *
     * @return
     */
    public Set<Horario> getHorarios() {
        return horarios;
    }

    /**
     * Method description
     *
     * @param horarios
     */
    public void setHorarios(Set<Horario> horarios) {
        this.horarios = horarios;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getSalaCapacidad() {
        return salaCapacidad;
    }

    /**
     * Method description
     *
     * @param salaCapacidad
     */
    public void setSalaCapacidad(Integer salaCapacidad) {
        this.salaCapacidad = salaCapacidad;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getSalaDescrip() {
        return salaDescrip;
    }

    /**
     * Method description
     *
     * @param salaDescrip
     */
    public void setSalaDescrip(String salaDescrip) {
        this.salaDescrip = salaDescrip;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getSalaNum() {
        return salaNum;
    }

    /**
     * Method description
     *
     * @param salaNum
     */
    public void setSalaNum(String salaNum) {
        this.salaNum = salaNum;
    }

    /**
     * BUSINESS LOGIC
     *
     */


    /**
     * Method description
     *
     * @return
     */
    public Color getColorSalaPDF() {
        return getColorPDF(this);
    }
}
