/*
 * @(#)Solicitud.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import infrastructure.support.SolicitudSupport;
import static infrastructure.util.DateUtil.getFormattedDate;
import static infrastructure.util.SystemParametersUtil.DATE_FULL_FORMAT;
import infrastructure.util.common.CommonSolicitudUtil;

//Generated 13-09-2010 05:58:20 PM by Hibernate Tools 3.2.1.GA
/**
 * Solicitud generated by hbm2java
 */
public class Solicitud implements Serializable {

    private static final long serialVersionUID = 1L;
    private List<SolicitudAttach> solicitudAttachList;
    private AluCar aluCar;
    private EstadoSolicitud estadoSolicitud;
    private int solFolio;
    private String solInformeRegCurr;
    private String solSolicita;
    private String solMotivo;
    private String solResolucion;
    private Tsolicitud tsolicitud;
    private String solRespuesta;
    private Integer solAgno;
    private Integer solSem;
    private Date solFecha;
    private Date solFechaInicio;
    private Date solFechaTermino;
    

    /**
     *
     */
    public Solicitud() {
    }

    /**
     * Method description
     *
     * @return
     */
    public AluCar getAluCar() {
        return aluCar;
    }

    /**
     * Method description
     *
     * @param aluCar
     */
    public void setAluCar(AluCar aluCar) {
        this.aluCar = aluCar;
    }

    /**
     * Method description
     *
     * @return
     */
    public EstadoSolicitud getEstadoSolicitud() {
        return estadoSolicitud;
    }

    /**
     * Method description
     *
     * @param estadoSolicitud
     */
    public void setEstadoSolicitud(EstadoSolicitud estadoSolicitud) {
        this.estadoSolicitud = estadoSolicitud;
    }

    /**
     * Method description
     *
     * @return
     */
    public int getSolFolio() {
        return solFolio;
    }

    /**
     * Method description
     *
     * @param solFolio
     */
    public void setSolFolio(int solFolio) {
        this.solFolio = solFolio;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getSolMotivo() {
        return solMotivo;
    }

    /**
     * Method description
     *
     * @param solMotivo
     */
    public void setSolMotivo(String solMotivo) {
        this.solMotivo = solMotivo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getSolInformeRegCurr() {
        return solInformeRegCurr;
    }

    /**
     * Method description
     *
     * @param solInformeRegCurr
     */
    public void setSolInformeRegCurr(String solInformeRegCurr) {
        this.solInformeRegCurr = solInformeRegCurr;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getSolResolucion() {
        return solResolucion;
    }

    /**
     * Method description
     *
     * @param solResolucion
     */
    public void setSolResolucion(String solResolucion) {
        this.solResolucion = solResolucion;
    }

    /**
     * Method description
     *
     * @return
     */
    public Tsolicitud getTsolicitud() {
        return tsolicitud;
    }

    /**
     * Method description
     *
     * @param tsolicitud
     */
    public void setTsolicitud(Tsolicitud tsolicitud) {
        this.tsolicitud = tsolicitud;
    }

    /**
     * Method description
     *
     * @return
     */
    public List<SolicitudAttach> getDocumentos() {
        return new SolicitudSupport(this).getDocumentos();
    }

    /**
     *
     * @return
     */
    public String getSolSolicita() {
        return solSolicita;
    }

    /**
     *
     * @param solSolicita
     */
    public void setSolSolicita(String solSolicita) {
        this.solSolicita = solSolicita;
    }

    /**
     *
     * @return
     */
    public String getResolucion()
    {
        return CommonSolicitudUtil.getResolucion(solResolucion);
    }

    /**
     *
     * @return
     */
    public String getSolRespuesta() {
        return solRespuesta;
    }

    /**
     *
     * @param solRespuesta
     */
    public void setSolRespuesta(String solRespuesta) {
        this.solRespuesta = solRespuesta;
    }

    /**
     *
     * @return
     */
    public List<SolicitudAttach> getSolicitudAttachList() {
        return solicitudAttachList;
    }

    /**
     *
     * @param solicitudAttachList
     */
    public void setSolicitudAttachList(List<SolicitudAttach> solicitudAttachList) {
        this.solicitudAttachList = solicitudAttachList;
    }

    public Integer getSolAgno() {
        return solAgno;
    }

    public void setSolAgno(Integer solAgno) {
        this.solAgno = solAgno;
    }

    public Integer getSolSem() {
        return solSem;
    }

    public void setSolSem(Integer solSem) {
        this.solSem = solSem;
    }

    public Date getSolFecha() {
        return solFecha;
    }

    public void setSolFecha(Date solFecha) {
        this.solFecha = solFecha;
    }

    public String getFormattedFullDate() {
        return getFormattedDate(solFecha, DATE_FULL_FORMAT);
    }

    public Date getSolFechaInicio() {
        return solFechaInicio;
    }

    public void setSolFechaInicio(Date solFechaInicio) {
        this.solFechaInicio = solFechaInicio;
    }

    public Date getSolFechaTermino() {
        return solFechaTermino;
    }

    public void setSolFechaTermino(Date solFechaTermino) {
        this.solFechaTermino = solFechaTermino;
    }
    
    
}
