/*
 * @(#)Tcalidad.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Tcalidad generated by hbm2java
 */
public class Tcalidad implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer tcaCod;
    private String tcaDescrip;

    /**
     *
     */
    public Tcalidad() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getTcaCod() {
        return this.tcaCod;
    }

    /**
     * Method description
     *
     * @param tcaCod
     */
    public void setTcaCod(Integer tcaCod) {
        this.tcaCod = tcaCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTcaDescrip() {
        return this.tcaDescrip;
    }

    /**
     * Method description
     *
     * @param tcaDescrip
     */
    public void setTcaDescrip(String tcaDescrip) {
        this.tcaDescrip = tcaDescrip;
    }
}
