/*
 * @(#)Tcarrera.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Tcarrera generated by hbm2java
 */
public class Tcarrera implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer tcrCtip;
    private String tcrNom;

    /**
     *
     */
    public Tcarrera() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getTcrCtip() {
        return tcrCtip;
    }

    /**
     * Method description
     *
     * @param tcrCtip
     */
    public void setTcrCtip(Integer tcrCtip) {
        this.tcrCtip = tcrCtip;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTcrNom() {
        return tcrNom;
    }

    /**
     * Method description
     *
     * @param tcrNom
     */
    public void setTcrNom(String tcrNom) {
        this.tcrNom = tcrNom;
    }
}
