/*
 * @(#)Tcertificado.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Tcertificado generated by hbm2java
 */
public class Tcertificado implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer tceCod;
    private String tceDes;
    private String tceDesCorta;    
    private Integer tceOrder;
    private String tceAviso;

    /**
     *
     */
    public Tcertificado() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getTceCod() {
        return tceCod;
    }

    /**
     * Method description
     *
     * @param tceCod
     */
    public void setTceCod(Integer tceCod) {
        this.tceCod = tceCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTceDes() {
        return tceDes;
    }

    /**
     * Method description
     *
     * @param tceDes
     */
    public void setTceDes(String tceDes) {
        this.tceDes = tceDes;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTceDesCorta() {
        return tceDesCorta;
    }

    /**
     * Method description
     *
     * @param tceDesCorta
     */
    public void setTceDesCorta(String tceDesCorta) {
        this.tceDesCorta = tceDesCorta;
    }

    public Integer getTceOrder() {
        return tceOrder;
    }

    public void setTceOrder(Integer tceOrder) {
        this.tceOrder = tceOrder;
    }

    public String getTceAviso() {
        return tceAviso;
    }

    public void setTceAviso(String tceAviso) {
        this.tceAviso = tceAviso;
    }
}
