package domain.model;
// Generated 14-08-2014 03:40:22 PM by Hibernate Tools 3.2.1.GA

/**
 * Testudio generated by hbm2java
 */
public class Testudio implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer testId;
    private String testNombre;

    /**
     *
     */
    public Testudio() {
    }

    /**
     *
     * @param testId
     */
    public Testudio(Integer testId) {
        this.testId = testId;
    }

    /**
     *
     * @return
     */
    public Integer getTestId() {
        return this.testId;
    }

    /**
     *
     * @param testId
     */
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    /**
     *
     * @return
     */
    public String getTestNombre() {
        return this.testNombre;
    }

    /**
     *
     * @param testNombre
     */
    public void setTestNombre(String testNombre) {
        this.testNombre = testNombre;
    }
}
