package domain.model;
// Generated 14-08-2014 03:40:22 PM by Hibernate Tools 3.2.1.GA

/**
 * TipoTrabajo generated by hbm2java
 */
public class TipoTrabajo implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private Integer ttraId;
    private String ttraNombre;

    /**
     *
     */
    public TipoTrabajo() {
    }

    /**
     *
     * @param ttraId
     */
    public TipoTrabajo(Integer ttraId) {
        this.ttraId = ttraId;
    }

    /**
     *
     * @return
     */
    public Integer getTtraId() {
        return this.ttraId;
    }

    /**
     *
     * @param ttraId
     */
    public void setTtraId(Integer ttraId) {
        this.ttraId = ttraId;
    }

    /**
     *
     * @return
     */
    public String getTtraNombre() {
        return this.ttraNombre;
    }

    /**
     *
     * @param ttraNombre
     */
    public void setTtraNombre(String ttraNombre) {
        this.ttraNombre = ttraNombre;
    }
}
