/*
 * @(#)TmensajeBarraDestino.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * TmensajeBarraDestino generated by hbm2java
 */
public class TmensajeBarraDestino implements Serializable {

    private static final long serialVersionUID = 1L;
    private TmensajeBarraDestinoId id;
    private TmensajeDestino tmensajeDestinoSegmento;

    /**
     *
     */
    public TmensajeBarraDestino() {
    }

    /**
     * Method description
     *
     * @return
     */
    public TmensajeBarraDestinoId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(TmensajeBarraDestinoId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public TmensajeDestino getTmensajeDestinoSegmento() {
        return this.tmensajeDestinoSegmento;
    }

    /**
     * Method description
     *
     * @param tmensajeDestinoSegmento
     */
    public void setTmensajeDestinoSegmento(TmensajeDestino tmensajeDestinoSegmento) {
        this.tmensajeDestinoSegmento = tmensajeDestinoSegmento;
    }
}
