/*
 * @(#)TmensajeOrigenDestinoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 26-oct-2009 19:46:29 by Hibernate Tools 3.2.4.GA
import java.io.Serializable;

/**
 * TmensajeOrigenDestinoId generated by hbm2java
 */
public class TmensajeOrigenDestinoId implements Serializable {

    private static final long serialVersionUID = 1L;
    private String todDestino;
    private String todOrigen;

    /**
     *
     */
    public TmensajeOrigenDestinoId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTodOrigen() {
        return this.todOrigen;
    }

    /**
     * Method description
     *
     * @param todOrigen
     */
    public void setTodOrigen(String todOrigen) {
        this.todOrigen = todOrigen;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTodDestino() {
        return this.todDestino;
    }

    /**
     * Method description
     *
     * @param todDestino
     */
    public void setTodDestino(String todDestino) {
        this.todDestino = todDestino;
    }    
}
