/*
 * @(#)TmensajeOrigenDestino.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 26-oct-2009 19:46:29 by Hibernate Tools 3.2.4.GA
import java.io.Serializable;

/**
 * TmensajeOrigenDestino generated by hbm2java
 */
public class TmensajeOrigenDestino implements Serializable {

    private static final long serialVersionUID = 1L;
    private TmensajeOrigenDestinoId id;
    private TmensajeDestino tmensajeDestino;

    /**
     *
     */
    public TmensajeOrigenDestino() {
    }

    /**
     * Method description
     *
     * @return
     */
    public TmensajeOrigenDestinoId getId() {
        return this.id;
    }

    /**
     * Method description
     *
     * @param id
     */
    public void setId(TmensajeOrigenDestinoId id) {
        this.id = id;
    }

    /**
     * Method description
     *
     * @return
     */
    public TmensajeDestino getTmensajeDestino() {
        return this.tmensajeDestino;
    }

    /**
     * Method description
     *
     * @param tmensajeDestino
     */
    public void setTmensajeDestino(TmensajeDestino tmensajeDestino) {
        this.tmensajeDestino = tmensajeDestino;
    }
}
