/*
 * @(#)TmensajeOrigen.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * TmensajeOrigen generated by hbm2java
 */
public class TmensajeOrigen implements Serializable {

    private static final long serialVersionUID = 1L;
    private String tmoCod;
    private String tmoDes;

    /**
     *
     */
    public TmensajeOrigen() {
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTmoCod() {
        return this.tmoCod;
    }

    /**
     * Method description
     *
     * @param tmoCod
     */
    public void setTmoCod(String tmoCod) {
        this.tmoCod = tmoCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTmoDes() {
        return this.tmoDes;
    }

    /**
     * Method description
     *
     * @param tmoDes
     */
    public void setTmoDes(String tmoDes) {
        this.tmoDes = tmoDes;
    }
}
