/*
 * @(#)TmensajeDestino.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 26-oct-2009 19:46:29 by Hibernate Tools 3.2.4.GA
import java.io.Serializable;

/**
 * TmensajeDestino generated by hbm2java
 */
public class TmensajeDestino implements Serializable {

    private static final long serialVersionUID = 1L;
    private Character tmdBarra;
    private String tmdCod;
    private Integer tmdCorrel;
    private String tmdDes;
    private Character tmdLista;

    /**
     *
     */
    public TmensajeDestino() {
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTmdCod() {
        return this.tmdCod;
    }

    /**
     * Method description
     *
     * @param tmdCod
     */
    public void setTmdCod(String tmdCod) {
        this.tmdCod = tmdCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTmdDes() {
        return this.tmdDes;
    }

    /**
     * Method description
     *
     * @param tmdDes
     */
    public void setTmdDes(String tmdDes) {
        this.tmdDes = tmdDes;
    }

    /**
     * Method description
     *
     * @return
     */
    public Character getTmdBarra() {
        return this.tmdBarra;
    }

    /**
     * Method description
     *
     * @param tmdBarra
     */
    public void setTmdBarra(Character tmdBarra) {
        this.tmdBarra = tmdBarra;
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getTmdCorrel() {
        return this.tmdCorrel;
    }

    /**
     * Method description
     *
     * @param tmdCorrel
     */
    public void setTmdCorrel(Integer tmdCorrel) {
        this.tmdCorrel = tmdCorrel;
    }

    /**
     * Method description
     *
     * @return
     */
    public Character getTmdLista() {
        return this.tmdLista;
    }

    /**
     * Method description
     *
     * @param tmdLista
     */
    public void setTmdLista(Character tmdLista) {
        this.tmdLista = tmdLista;
    }
}
