/*
 * @(#)TmensajeBarraDestinoId.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * TmensajeBarraDestinoId generated by hbm2java
 */
public class TmensajeBarraDestinoId implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer tbdCorrel;
    private String tbdDestino;

    /**
     *
     */
    public TmensajeBarraDestinoId() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getTbdCorrel() {
        return this.tbdCorrel;
    }

    /**
     * Method description
     *
     * @param tbdCorrel
     */
    public void setTbdCorrel(Integer tbdCorrel) {
        this.tbdCorrel = tbdCorrel;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTbdDestino() {
        return this.tbdDestino;
    }

    /**
     * Method description
     *
     * @param tbdDestino
     */
    public void setTbdDestino(String tbdDestino) {
        this.tbdDestino = tbdDestino;
    }    
}
