/*
 * @(#)Tramite.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Tramite generated by hbm2java
 */
public class Tramite implements Serializable {

    private static final long serialVersionUID = 1L;
    private String traDescripcion;
    private String traDescripcionCorta;
    private Character traExcentoPago;
    private String traPrefijo;
    private Integer traTramite;

    /**
     *
     */
    public Tramite() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getTraTramite() {
        return this.traTramite;
    }

    /**
     * Method description
     *
     * @param traTramite
     */
    public void setTraTramite(Integer traTramite) {
        this.traTramite = traTramite;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTraDescripcion() {
        return this.traDescripcion;
    }

    /**
     * Method description
     *
     * @param traDescripcion
     */
    public void setTraDescripcion(String traDescripcion) {
        this.traDescripcion = traDescripcion;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTraPrefijo() {
        return this.traPrefijo;
    }

    /**
     * Method description
     *
     * @param traPrefijo
     */
    public void setTraPrefijo(String traPrefijo) {
        this.traPrefijo = traPrefijo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTraDescripcionCorta() {
        return this.traDescripcionCorta;
    }

    /**
     * Method description
     *
     * @param traDescripcionCorta
     */
    public void setTraDescripcionCorta(String traDescripcionCorta) {
        this.traDescripcionCorta = traDescripcionCorta;
    }

    /**
     * Method description
     *
     * @return
     */
    public Character getTraExcentoPago() {
        return this.traExcentoPago;
    }

    /**
     * Method description
     *
     * @param traExcentoPago
     */
    public void setTraExcentoPago(Character traExcentoPago) {
        this.traExcentoPago = traExcentoPago;
    }

    /**
     * BUSINESS LOGIC
     *
     * @param tramiteList
     * @return
     */
    public Map<Integer, Tramite> getTramiteMap(List<Tramite> tramiteList) {
        return tramiteList.stream()
                .collect(Collectors.toMap(tramite -> tramite.traTramite, tramite -> tramite));
    }
}
