/*
 * @(#)Tsacademica.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Tsacademica generated by hbm2java
 */
public class Tsacademica implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer tsaCod;
    private String tsaDescrip;
    private String tsaReglam;

    /**
     *
     */
    public Tsacademica() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getTsaCod() {
        return this.tsaCod;
    }

    /**
     * Method description
     *
     * @param tsaCod
     */
    public void setTsaCod(Integer tsaCod) {
        this.tsaCod = tsaCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTsaDescrip() {
        return this.tsaDescrip;
    }

    /**
     * Method description
     *
     * @param tsaDescrip
     */
    public void setTsaDescrip(String tsaDescrip) {
        this.tsaDescrip = tsaDescrip;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTsaReglam() {
        return this.tsaReglam;
    }

    /**
     * Method description
     *
     * @param tsaReglam
     */
    public void setTsaReglam(String tsaReglam) {
        this.tsaReglam = tsaReglam;
    }        
}
