/*
 * @(#)Tsolicitud.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 13-09-2010 05:58:20 PM by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Tsolicitud generated by hbm2java
 */
public class Tsolicitud implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer tsolCodigo;
    private String tsolDescrip;
    private String tsolTipo;

    /**
     *
     */
    public Tsolicitud() {
    }

    /**
     * Method description
     *
     * @return
     */
    public Integer getTsolCodigo() {
        return this.tsolCodigo;
    }

    /**
     * Method description
     *
     * @param tsolCodigo
     */
    public void setTsolCodigo(Integer tsolCodigo) {
        this.tsolCodigo = tsolCodigo;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getTsolDescrip() {
        return this.tsolDescrip;
    }

    /**
     * Method description
     *
     * @param tsolDescrip
     */
    public void setTsolDescrip(String tsolDescrip) {
        this.tsolDescrip = tsolDescrip;
    }

    public String getTsolTipo() {
        return tsolTipo;
    }

    public void setTsolTipo(String tsolTipo) {
        this.tsolTipo = tsolTipo;
    }
}
