/*
 * @(#)Unidad.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * Unidad generated by hbm2java
 */
public class Unidad implements Serializable {
    private static final long serialVersionUID = 1L;

    private Integer uniCC;
    private Integer uniCod;
    private String uniNom;
    private Unidad uniAcadMayor;
    private Unidad uniAdmMayor;
    private Unidad uniMayor;
    private Unidad uniSuperior;
    private String uniUrl;
    private Integer uniTipo;
    private String uniColorSala;
    private Integer atributoUniAcadMayor;
    private Integer atributoUniAdmMayor;
    private Integer atributoUniMayor;
    private Integer atributoUniSuperior;

    /**
     *
     */
    public Unidad() {
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getUniCC() {
        return uniCC;
    }

    /**
     * Method description
     *
     *
     * @param uniCC
     */
    public void setUniCC(Integer uniCC) {
        this.uniCC = uniCC;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public Integer getUniCod() {
        return uniCod;
    }

    /**
     * Method description
     *
     *
     * @param uniCod
     */
    public void setUniCod(Integer uniCod) {
        this.uniCod = uniCod;
    }

    /**
     * Method description
     *
     *
     * @return
     */
    public String getUniNom() {
        return uniNom;
    }

    /**
     * Method description
     *
     *
     * @param uniNom
     */
    public void setUniNom(String uniNom) {
        this.uniNom = uniNom;
    }

    /**
     *
     * @return
     */
    public Unidad getUniAcadMayor() {
        return uniAcadMayor;
    }

    /**
     *
     * @param uniAcadMayor
     */
    public void setUniAcadMayor(Unidad uniAcadMayor) {
        this.uniAcadMayor = uniAcadMayor;
    }

    /**
     *
     * @return
     */
    public Unidad getUniAdmMayor() {
        return uniAdmMayor;
    }

    /**
     *
     * @param uniAdmMayor
     */
    public void setUniAdmMayor(Unidad uniAdmMayor) {
        this.uniAdmMayor = uniAdmMayor;
    }

    public Unidad getUniMayor() {
        return uniMayor;
    }

    public void setUniMayor(Unidad uniMayor) {
        this.uniMayor = uniMayor;
    }

    public Unidad getUniSuperior() {
        return uniSuperior;
    }

    public void setUniSuperior(Unidad uniSuperior) {
        this.uniSuperior = uniSuperior;
    }

    public String getUniUrl() {
        return uniUrl;
    }

    public void setUniUrl(String uniUrl) {
        this.uniUrl = uniUrl;
    }

    public Integer getUniTipo() {
        return uniTipo;
    }

    public void setUniTipo(Integer uniTipo) {
        this.uniTipo = uniTipo;
    }

    public String getUniColorSala() {
        return uniColorSala;
    }

    public void setUniColorSala(String uniColorSala) {
        this.uniColorSala = uniColorSala;
    }

    public Integer getAtributoUniAcadMayor() {
        return atributoUniAcadMayor;
    }

    public void setAtributoUniAcadMayor(Integer atributoUniAcadMayor) {
        this.atributoUniAcadMayor = atributoUniAcadMayor;
    }

    public Integer getAtributoUniAdmMayor() {
        return atributoUniAdmMayor;
    }

    public void setAtributoUniAdmMayor(Integer atributoUniAdmMayor) {
        this.atributoUniAdmMayor = atributoUniAdmMayor;
    }

    public Integer getAtributoUniMayor() {
        return atributoUniMayor;
    }

    public void setAtributoUniMayor(Integer atributoUniMayor) {
        this.atributoUniMayor = atributoUniMayor;
    }

    public Integer getAtributoUniSuperior() {
        return atributoUniSuperior;
    }

    public void setAtributoUniSuperior(Integer atributoUniSuperior) {
        this.atributoUniSuperior = atributoUniSuperior;
    }    
}
