/*
 * @(#)ViaIngreso.java
 *
 * Copyright (c) 2025 FAE-USACH
 */
package domain.model;

//Generated 24-mar-2009 15:19:39 by Hibernate Tools 3.2.1.GA
import java.io.Serializable;

/**
 * ViaIngreso generated by hbm2java
 */
public class ViaIngreso implements Serializable {

    private static final long serialVersionUID = 1L;
    private Integer viiCod;
    private String viiDes;

    /**
     *
     */
    public ViaIngreso() {
    }
    /**
     * Method description
     *
     * @return
     */
    public Integer getViiCod() {
        return viiCod;
    }

    /**
     * Method description
     *
     * @param viiCod
     */
    public void setViiCod(Integer viiCod) {
        this.viiCod = viiCod;
    }

    /**
     * Method description
     *
     * @return
     */
    public String getViiDes() {
        return viiDes;
    }

    /**
     * Method description
     *
     * @param viiDes
     */
    public void setViiDes(String viiDes) {
        this.viiDes = viiDes;
    }
}
